### ISSUE TITLE
Different processors use different time steps

### ISSUE THREAD

**Issue by abarret** [IBAMR/IBAMR#1022]
https://github.com/IBAMR/IBAMR/blob/59afafa326986b0f27e5e957b8c09e87a8ef3a69/ibtk/src/utilities/HierarchyIntegrator.cpp#L330-L350

@boyceg Is there a reason why we don't do a `minReduction` when we compute time step sizes? I'm getting patches that run at different timesteps depending on how the patches are laid out on processors.

**Comment by boyceg** [comment]
I think the reduction should be in `getMinimumTimeStepSizeSpecialized()`.

**Comment by boyceg** [comment]
however this `std::max()` looks like it should be a `std::min()`?

**Comment by abarret** [comment]
There's no reduction happening in `AdvDiffHierarchyIntegrator` or `HierarchyIntegrator` for computing time step sizes.

**Comment by abarret** [comment]
We do a reduction in `INSHierarchyIntegrator` however. This sounds like a bug in `AdvDiffHierarchyIntegrator`. I'll submit a PR.

**Comment by boyceg** [comment]
Wherever the time step size is computed, the result should be consistent across processors. There is nothing being computed in this particular routine.
