### ISSUE TITLE
0.7.1 release

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1028]
We fixed a few things since the release. Since two involve compiler problems I think we should go ahead and do a bugfix release by cherry-picking the following:

#1021
#1023
#1026
#1030
#1031

**Comment by drwells** [comment]
Lets try to get this out the door by Thursday. Lets finalize the list of patches by Wednesday.

**Comment by boyceg** [comment]
List looks good to me.

**Comment by drwells** [comment]
Somehow #1017 didn't get cherry-picked for the release branch so I added it too.

**Comment by drwells** [comment]
The website and #1032 are in so I am going to declare this done.
