### ISSUE TITLE
Get lag data notes into manual

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1040]
@abarret I saw that you responded to an email on the mailing list with some notes on lag data (using `ibamr_lag_data.pdf`). Are these notes inside the manual? If not, would you please add them?

**Comment by abarret** [comment]
What does "inside the manual" mean? Should I put it in the documentation somewhere?

**Comment by drwells** [comment]
Yes - by 'manual' I really mean 'inside the generated doxygen documentation'.

**Comment by drwells** [comment]
Can you commit to getting this done by the next release?

**Comment by drwells** [comment]
:tada:

**Comment by drwells** [comment]
@abarret Will this be done by the end of the month?

**Comment by abarret** [comment]
Yes. I'll try to have this finished by next week.
