### ISSUE TITLE
Nightly Build

### ISSUE THREAD

**Issue by deleeke** [IBAMR/IBAMR#111]
@boyceg 

I am going to enable nightly builds of master on Jenkins. There two options about how the build status is displayed on GitHub:

1) Set build status with a checkmark, red "x", or yellow "unstable/pending" ball on [the branches page](https://github.com/IBAMR/IBAMR/branches) next to branch name

2) [Put build status badge in README](https://wiki.jenkins-ci.org/display/JENKINS/Embeddable+Build+Status+Plugin)

And/or there is the option to get emails:

3) Receive an email only when it is unstable with the console output in the email and another notification then when it returns to passing.

4) Receive an email for every build.

Of those four options which would you like (you can do any combination)?

**Comment by boyceg** [comment]
I think that I would prefer not to receive additional emails.

I think that putting nightly build status in a README or generated webpage would be best. Otherwise wouldn't it always be "pending" --- every night there is a new build?

**Comment by deleeke** [comment]
Ok I'll work on that.

**Comment by deleeke** [comment]
@boyceg 
Well I spoke too soon about being able to use the embedded image showing the build status -- because, again, in order to be able to see the image the viewer must have access to the VM because it is essentially just a URL that links to the VM. 

The LLVM and GCC jobs ran last night with no problems and set their build results on the [branches page with a green checkmark.](https://github.com/IBAMR/IBAMR/branches)
