### ISSUE TITLE
Prefer std::function to function pointers

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1110]
C++11 added `std::function` which can correctly handle member functions, function pointers, functors, lambda functions, etc. with one callable interface. We should convert our use of function pointers to these because of their increased flexibility and saner syntax.

**Comment by drwells** [comment]
Looking back at this almost a year later - a lot of our API expects users to pass in function pointers. I think we shouldn't bother converting only half of the API (i.e., what we store internally). Hence, if we aren't changing it, this should be closed.

**Comment by boyceg** [comment]
Does it _really_ change the API to change from C-style function pointers to `std::function`?

**Comment by drwells** [comment]
That was my original intent in this issue - I'm not sure I understand your question.

**Comment by boyceg** [comment]
I guess I didn't understand your comment. Anyway, I think we should do this! I think that the C++11 `std::function` syntax is much clearer than the C-style function pointer syntax.

**Comment by drwells** [comment]
My original statement was vague. I'll try to describe it better here.

Right now users write their own callbacks as C functions and pass them to APIs like
```cpp
        IBFEMethod::LagBodyForceFcnData block_tether_force_data(block_tether_force_function);
        ib_method_ops->registerLagBodyForceFunction(block_tether_force_data, 0);
        ib_method_ops->registerLagBodyForceFunction(block_tether_force_data, 1);
```
where the first argument to `LagBodyForceFcnData` is a `LagBodyForceFcnPtr` defined (by alias) as
```cpp
using ScalarMeshFcnPtr =
    void (*)(double& F,
             const libMesh::TensorValue<double>& FF,
             const libMesh::Point& x,
             const libMesh::Point& X,
             libMesh::Elem* elem,
             const std::vector<const std::vector<double>*>& system_var_data,
             const std::vector<const std::vector<libMesh::VectorValue<double> >*>& system_grad_var_data,
             double data_time,
             void* ctx);
```

If we replace this we would instead write

```cpp
using ScalarMeshFcnPtr =
    std::function<void(double& F,
                       const libMesh::TensorValue<double>& FF,
                       const libMesh::Point& x,
                       const libMesh::Point& X,
                       libMesh::Elem* elem,
                       const std::vector<const std::vector<double>*>& system_var_data,
                       const std::vector<const std::vector<libMesh::VectorValue<double> >*>& system_grad_var_data,
                       double data_time,
                       void* ctx)>;
```
if a reader wants to figure out the type they now also need to figure out what a `std::function` is and have some idea of why you can convert a function pointer to one. Its not difficult, but its another layer of complication that was previously not necessary.

Another problem with this conversion is that `std::function<>` does a lot more than function pointers (it can do object methods, can be rebound to different functions at run-time, etc). Relevantly, I think there is always the overhead of an extra function call when a `std::function` is invoked when things are not all in the same compilation unit. This is something we should avoid since we will call a `std::function` at every single quadrature point: we are going to make things slower for very simple forces (like a tether) for only mild semantic improvements to the API.

**Comment by boyceg** [comment]
OK; got it.

It sounds like we should actually _prefer_ C-style function pointers to `std::function`.

It looks like we do not actually use `std::function` in the library currently. All I found a comment (in `ConstraintIBMethod.h`) saying that we should update to using it. Should we remove that comment and close this issue?

**Comment by drwells** [comment]
I think so. Since we always pass `void *ctx` as an argument we don't really utilize the primary benefit of `std::function` (namely that it can store state and it works with member functions), so we should stick with plain function pointers.
