### ISSUE TITLE
Approximate floating point comparison with 0.0

### ISSUE THREAD

**Issue by abarret** [IBAMR/IBAMR#1177]
The `SAMRAI::tbox::MathUtilities<double>::equalEps()` function checks relative differences between numbers. This gives a more stringent check for values close to zero than for larger values. In particular:

`MathUtilities<double>::equalEps(0.0, std::numeric_limits<double>::epsilon())` returns `false`
while
`MathUtilities<double>::equalEps(1.0, 1.0 + std::numeric_limits<double>::epsilon())` returns `true`.

A better comparison (in some cases), would be an absolute comparison. We should implement a `rel_equal_eps()` and a `abs_equal_eps()`, and make sure these are used appropriately in the library.

**Comment by drwells** [comment]
@abarret do you want to push anything else for the 0.8.0 release?

**Comment by abarret** [comment]
> @abarret do you want to push anything else for the 0.8.0 release?

When do you plan on putting out 0.8.0? I can probably get to it tomorrow.

The only thing left is to switch over from using `MathUtilities<double>::equalEps` to the correct `IBTK` version. It shouldn't (fingers crossed) actually change the code paths, but if it does, determining what the "right" behavior is might be difficult.

**Comment by drwells** [comment]
> When do you plan on putting out 0.8.0? I can probably get to it tomorrow.

I want to be done by the start of the semester so ideally all patches need to be in this week (so I have a week to fix anything that fell through the cracks).

**Comment by drwells** [comment]
@abarret will you get this done by January?

**Comment by abarret** [comment]
It is on my to-do list.

I ran into issues before because changing to the `IBTK` versions caused some tests to fail. I will revisit this and see what's going on.

**Comment by abarret** [comment]
@drwells, replacing the SAMRAI `equalEps` with the appropriate `IBTK` version causes a change in the test `explicit_ex4_2d.displace.mpirun=4`. The difference is only in one line in calculating the maximum node displacement:
```
----------------
##4404    #:7   <== 0.002533931815
                ==> 0.002533934630
@ Absolute error = 2.8150000000e-9, Relative error = 1.1109217633e-6
```

**Comment by drwells** [comment]
That's unexpected. Is that branch publicly available?

**Comment by abarret** [comment]
Yes, you can find it here
https://github.com/abarret/ibamr/tree/replace_equal_eps

There's potential that very small values could now be ignored with the patch, but it's surprising that it's only one line of one test.

I have tried to determine the correct intention behind `equalEps` and replace it with the appropriate relative or absolute comparison. Another possibility is to instead switch from `equalEps` directly to `abs_equal_eps` which is essentially just a switch in namespace.

**Comment by drwells** [comment]
It looks like that patch includes a bunch of changes, e.g., comparing timesteps to within `0.1*dt` instead of the current condition. How about we pull out all the stuff that should be the same as SAMRAI to start? Those changes shouldn't alter the output.
