### ISSUE TITLE
Add input options to control whether quadrature rules can use negative weights

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#1187]

**Comment by boyceg** [comment]
@cpuelz, @xxjaehoxx

**Comment by boyceg** [comment]
On `TET` elements, by default libMesh will use Gauss-like rules with negative weights for orders `THIRD`, `FOURTH`, and `SEVENTH` or higher.

**Comment by boyceg** [comment]
The rules with negative weights are much more efficient, so if we can get away with it, we should use them.

**Comment by drwells** [comment]
Oh, it will? That's unfortunate. We should probably disable them by default.

> The rules with negative weights are much more efficient, so if we can get away with it, we should use them.

They are efficient in terms of order but not necessarily point density. We still need to come up with a better scheme for picking quadrature rules.

**Comment by boyceg** [comment]
See: https://libmesh.github.io/doxygen/classlibMesh_1_1QBase.html#a6f1f4bb99c359f881b0b5b2695bb2cde

**Comment by boyceg** [comment]
> They are efficient in terms of order but not necessarily point density.

You mean in terms of the _distribution_ of quadrature points? In some sense, `QGRID` would be the best, but it doesn't seem to be stable. I wonder if it would work if we consistently used it in evaluating forces and also in spreading/interpolating.
