### ISSUE TITLE
Updates to FischerGuess require Eigen 3.3 or newer

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#1213]
#1211 uses `bcdSvd` in Eigen to compute the SVD of a small dense matrix. This function appears only to be available in Eigen 3.3 or later. We should either update the required version of Eigen, or switch to a different method. @drwells do you have a preference?

(cc: @cpuelz)

**Comment by drwells** [comment]
Good catch. `bcdSvd` is new in that version of Eigen, but it does have a slower and older algorithm too - we can conditionally switch between them. I'll put up a patch in a few minutes.
