### ISSUE TITLE
Add a simple IBLevelSet example for an oscillating cylinder

### ISSUE THREAD

**Issue by amneetb** [IBAMR/IBAMR#1217]
We should have a simple example showing IBLevelSet doing single phase FSI.

@Raamkrishnan and @Kaustubh-Khedkar : Please add an oscillating cylinder example from ConstraintIB folder
https://github.com/IBAMR/IBAMR/tree/master/examples/ConstraintIB/oscillating_rigid_cylinder

Remove all the stuff related to libMesh, air-water interfaces, and make it a pure Eulerian example (no need to surround the cylinder with a block of Lagrangian markers either)

**Comment by drwells** [comment]
This would be really useful to have, and would help a lot of people asking these kinds of questions - thanks for taking the lead on this!

**Comment by sach1** [comment]
Is there any interest in a simple example like this one: https://streamable.com/8oczj ?

Its like a combo of mpf_ex5 + ibfe_ex2 so a regular ibamr user can easily create it if they wish.
Its just that the current mpf examples that use ibfe are rigid. I haven't gone through the newer examples that have been pushed so ignore my comment if there are already examples with mpf + hyperelastic ibfe. Thanks.

**Comment by amneetb** [comment]
@sach1 : This would be a nice example to have it in the library. Can you create a PR?

**Comment by sach1** [comment]
@amneetb Got it! I will clean it up, make sure its up to spec and submit a PR.

**Comment by drwells** [comment]
Fixed by #1220.
