### ISSUE TITLE
Ban the Eigen version that doesn't work with 2x2 in-place inverses

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1230]
@kkeonho what version of Eigen had this problem?

**Comment by kkeonho** [comment]
@drwells configure:27300: checking for Eigen version >= 3.2.5

**Comment by drwells** [comment]
That doesn't answer the question - that line states that we check for a version newer than 3.2.5 but it doesn't state what version we use. What version did you use?

**Comment by kkeonho** [comment]
Sorry..! I'm using eigen-3.3.7.

**Comment by drwells** [comment]
I want to wrap this up in time for the release, but, two things:
1. @kkeonho You may be using Eigen 3.3.7, but that's the version of Eigen bundled with IBAMR - are you sure that's the one with the bug?
2. I cannot reproduce any sort of accuracy problem with any supported version of Eigen. With this test program:

```cpp
#include <Eigen/Core>
#include <Eigen/LU>

#include <cmath>
#include <iostream>

int main()
{
    Eigen::Matrix<double, 2, 2> matrix;

    matrix(0, 0) = 1.0;
    matrix(0, 1) = 1.0 + 100.23*(std::nexttoward(matrix(0, 0), 10.0) - matrix(0, 0));
    matrix(1, 0) = 1.0 + 300.45*(std::nexttoward(matrix(0, 1), 10.0) - matrix(0, 1));
    matrix(1, 1) = 1.0 + 500.67*(std::nexttoward(matrix(1, 0), 10.0) - matrix(1, 0));

    decltype(matrix) inv = matrix.inverse();
    decltype(matrix) error = decltype(matrix)::Identity() - inv * matrix;

    std::cout << "Eigen3 version " << EIGEN_WORLD_VERSION << '.'
              << EIGEN_MAJOR_VERSION << '.' << EIGEN_MINOR_VERSION << std::endl;
    std::cout << inv << std::endl;
    std::cout << "error = " << error.norm() << std::endl;
}
```

and this test runner (and every relevant version of eigen in the working directory)
```sh
#!/bin/bash

for DIR in $(ls | grep eigen | grep -v gz)
do
rm a.out
g++ -O3 -march=native -I./$DIR test.cc 2>/dev/null
./a.out
done
```

I get
```
Eigen3 version 3.2.10
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.2.5
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.2.6
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.2.7
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.2.8
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.2.9
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.3.0
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.3.1
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.3.2
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.3.3
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.3.4
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.3.5
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.3.6
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.3.7
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.3.8
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
Eigen3 version 3.3.9
 4.45901e+13 -4.45901e+13
-4.45901e+13  4.45901e+13
error = 0
```
The inverse has only two correct digits but that's expected given that only the last three digits make the matrix invertible. More relevantly, all supported versions of Eigen return the same value.

**Comment by drwells** [comment]
Alternatively, if there is some other inverse function, then we should take a look at that.

**Comment by kkeonho** [comment]
Yes I'm using Eigen-3.3.7 now.

https://github.com/IBAMR/IBAMR/blob/kkeonho/immersed-peridynamics/src/IB/IBPDForceGen.cpp#L570-L602

This is the only place where I compute an inverse matrix. I just tested using Eigen to compute a 2x2 inverse matrix, but there is an error in inversion. 

```
Before the inversion =>0.403576  0.27598
 0.27598 0.827524
After the inversion =>  3.2099 -1.07051
-1.07051  12.4509
```

**Comment by drwells** [comment]
Thanks - I'll take another look.

**Comment by drwells** [comment]
This is a bug in Eigen, but not the bug you think it is. The signature of that function is
```
inline void MatrixBase<Derived>::computeInverseAndDetWithCheck(
    ResultType& inverse,
    typename ResultType::Scalar& determinant,
    bool& invertible,
    const RealScalar& absDeterminantThreshold
  ) const
```
i.e., if `inverse == *this` then you are invoking undefined behavior - they should assert that this cannot happen, but they do not. Hence every version of Eigen contains this bug - I'll report it.

@kkeonho would you like to put together a patch that fixes this in IBAMR? The right way to do this is what I had above:
```cpp
    const decltype(matrix) inv = matrix.inverse();
```

**Comment by drwells** [comment]
https://gitlab.com/libeigen/eigen/-/issues/2285

**Comment by drwells** [comment]
@kkeonho that code is on your branch, not IBAMR, so we don't need to fix anything in IBAMR itself.

Since this is a (minor) bug in every version of Eigen and there is no code in IBAMR that actually calls this function I am going to close the issue.

**Comment by drwells** [comment]
You should still fix the code on your branch though :)
