### ISSUE TITLE
Children integrators are not properly traversed by parent integrators

### ISSUE THREAD

**Issue by abarret** [IBAMR/IBAMR#1260]
When an implementation of `INSHierarchyIntegrator` has an `AdvDiffHierarchyIntegrator` registered and is also registered with `IBHierarchyIntegrator`, the `AdvDiffHierarchyIntegrator` is not seen as a child of `IBHierarchyIntegrator`. Functions such as `AdvDiffHierarchyIntegrator::regridHierarchyEndSpecialized()` (and others) are not called.

This can be fixed in some ways by registering a callback function with the topmost hierarchy integrator, but that does not work with every function currently (`regridHierarchyEndSpecialized()` in particular) and is cumbersome if you need to register multiple callbacks.

The issue seems to be that `HierarchyIntegrator` is only set up for a tree of height one. We could extend this to build a proper tree.

**Comment by abarret** [comment]
Actually, it seems to only be a problem with `regridHierarchy[Begin|End]Specialized()`

**Comment by boyceg** [comment]
My original intention was to traverse the whole tree of solvers so that, e.g., each can apply its own tagging criteria.

Could you put together a PR to rationalize the implementation? 😁

**Comment by abarret** [comment]
Yes. I have a fix incoming.
