### ISSUE TITLE
Start using clang-format

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1299]
It shouldn't be that hard to add another GitHub action that runs clang format and somehow communicates the result to the PR author. Some options:
- we could rig things up to set up a PR onto the callers PR that fixes indentation
- minimally, we can generate a patch for them to apply

I think the second one is probably okay - we've gotten away with less than that in the deal.II CI. In particular, we have an `indent` target in CMake that runs clang-format which makes it very easy for users to just fix the indentation locally on their own.

Hence, lets do the following:
- [ ] borrow `download_clang_format` and `make indent` from deal.II
- [ ] set up a CI test that makes sure PRs conform to clang-format
- [ ] have the CI indenter generate a patch

**Comment by drwells** [comment]
If we pick a specific version we should also pick a new language standard so that lambdas are formatted correctly.

**Comment by boyceg** [comment]
Sounds good.
