### ISSUE TITLE
Convert the GSL integrals to use boost

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1358]
boost 1.66 was released in 2017 and it includes support for Gauss-Kronrod quadrature (the quadrature we use in eel3d):

https://www.boost.org/users/history/version_1_66_0.html

I'd like to update our minimum and bundled versions of boost so we can use this instead of GSL - this way users don't need one more dependency just to run this example.

AFAICT we only use GSL in this one place and we should be able to convert it pretty easily to use the boost version instead. Thoughts?

**Comment by amneetb** [comment]
> AFAICT we only use GSL in this one place and we should be able to convert it pretty easily to use the boost version instead. Thoughts?

That would be great! On some systems GSL is installed without header files (non-dev version) and this causes agony in getting configure work with the user-installed version of it.
