### ISSUE TITLE
IBAMR 0.10 Release

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1384]
It's time to take what we have and put together another release. If you think something should be in the release then please put it in the milestone.

*Please finish any outstanding patches by January 3. I'll put together the release with what we have at some point that week.*

# IBAMR release tasks

## static analysis

- [x] verify that neither `namespaces.h` nor `app_namespaces.h` are in IBTK or
  IBAMR headers
- [x] clear basic compilation warnings with GCC and clang on linux
- [x] compile with the latest libMesh release (which should be configured with
  `--disable-deprecated`) to verify that we do not use any deprecated
  functionality (this will cause compilation errors if we do use them). Add
  version checks: for example, here is one (lightly edited) in
  `IBFEInstrumentPannel.cpp` that uses a macro defined in `libmesh_version.h`:
```cpp
    // new API in 1.4.0
#if LIBMESH_VERSION_LESS_THAN(1, 4, 0)
    boundary_info.build_node_list(nodes, bcs);
#else
    const auto node_list = boundary_info.build_node_list();
    for (const auto& pair : node_list)
    {
        nodes.push_back(std::get<0>(pair));
        bcs.push_back(std::get<1>(pair));
    }
#endif
```
  around APIs to keep backwards compatibility with older versions of libMesh.
- [x] check the test suite with the oldest (3.7.0) and newest (latest release)
  versions of PETSc. Also check with the oldest (1.1.0) and newest (latest
  release) versions of libMesh.
- [x] clear basic compilation warnings with GCC and clang on linux and macOS
- [x] run cppcheck via
```
  cppcheck --force -j4 --enable=all -I./include/ -I./ibtk/include/  \
  $(find ./src ./ibtk/src -name '*.cpp') >cppcheck-results.txt 2>&1
```
- [x] Check that we don't call functions like
  `ReplicatedMesh::active_local_elements_end()` inside `for`-loop declarations
  since the end iterator is expensive to compute.
- [x] Check that we always get unique `HierarchyDataOps` by passing `true` as
  the third argument to `getOperationsDouble` et al. This prevents memory leaks
  where a statically stored `HierarchyDataOps` object keeps a patch hierarchy
  alive that is otherwise inaccessible.
- [x] Run clang-format on the entire code base.

## testing

- [x] Send out a message to the mailing list about the release asking about the
  status of any open PRs or bugs. (skipped)
- [x] Run the test suite on a cluster where libMesh and PETSc were built without
  HDF5 support and HDF5 was installed as a user (see #687). Make sure all
  examples can compile and link.
- [x] Check that everything works on macOS where dependencies are installed with
  HomeBrew.
- [x] In general, run the test suite on as many platforms and configurations as
  possible to weed out problems.

## Copyright

- [x] Ensure that the top level file `COPYRIGHT` has the release year in it.
- [x] Check that new files that have been added since the last release have the
  correct copyright header. Try, for example,
```
  git log --diff-filter=A --numstat --pretty='COMMIT: %H %cd' v0.5.1..master
```
  to print all added files between `0.5.1` and `master` or just run
```
grep -L 'by the IBAMR developers' -R ./include/ ./ibtk/include/ ./src/ \
  ./ibtk/src/ | grep -v Makefile.in'
```
  to print all relevant (i.e., files not generated by automake) files which
  currently lack the copyright statement.
- [x] Run `scripts/maintenance/update_copyright.sh` to update copyright for
  standard file types.

## creating the release

- [x] Collate the changelog entries on `master`. At the current time this is
  done manually. Open a PR for this on GitHub: only proceed once it is merged.
- [x] Create a new branch `IBAMR-X.Y` locally off of master and increment the
  version in `VERSION` correctly. Push to GitHub without a PR:
```
  git push https://github.com/ibamr/ibamr.git IBAMR-X.Y
```
  where `X` and `Y` are the version numbers for the release (e.g., for the
  `0.5.0` release they are `0` and `5`). Note that the bugfix number does not go
  into the branch name.
- [x] Increment the version number on `master` to, e.g., `0.6.0-pre` to signify
  that `master` now corresponds to a prerelease state. Put this in a PR.
- [x] At this point the release branch and `master` will have diverged. Create a
  release candidate from the `IBAMR-X.Y` branch on GitHub and tag it as a
  prerelease (the tag should be `vX.Y.Z-rc1`). Be sure to include instructions
  on how to patch and compile SAMRAI.
- [x] If necessary, patch `IBAMR-X.Y` should the release candidate uncover more
  bugs.
- [x] Once `IBAMR-X.Y` is in good shape tag a proper release, i.e., `vX.Y.Z` and
  create a non-draft release on GitHub.
- [x] Send out a message to the mailing list about the release.
- [x] Add a note on the release to the web page.
- [x] Update version numbers on the build instructions web page.
- [x] Celebrate!

**Comment by drwells** [comment]
Lets get the following in:
- [ ] #1244
- [ ] #1366 
- [ ] #1371 
- [ ] #1382 
- [ ] #1383 
- [ ] #1385
- [ ] #1386 
- [ ] #1388

For future-proofing, we also need to update the SAMRAI patch to avoid using `mallinfo` which is now deprecated.

**Comment by drwells** [comment]
In order to proceed with the release (in this case, mass copyright updates) we need to merge the last few PRs listed above - @IBAMR/ibamr-admin-team could someone take a look?

**Comment by abarret** [comment]
I can press the button to approve the IIM PR if @boyceg or @AminKolah are not available, but I don't know enough to comment on correctness.

**Comment by AminKolah** [comment]
Thanks Aaron for poking on this. I didn't initially get any notification (I'm not in the admin-team)....I just reviewed the files. Everything looks good to me except a couple of minor things in the example input files. Thank you David for adding those new features. I must have totally missed them!

**Comment by drwells** [comment]
I had to make some educated guesses for the input files to get them running - if you have better fixes I would be happy to take them!

**Comment by AminKolah** [comment]
Sure thing. I already made a 3 small comments but it seems like you might have not received them. It says "pending" on my side whatever that means (probably because some sort of permissions are required for a user to comment here). In any case, I took a snapshop and attached it here. With these, everything is 100% good for the release on my side. Thanks!

<img width="752" alt="Screen Shot 2022-01-08 at 11 31 31 AM" src="https://user-images.githubusercontent.com/11001629/148652099-1c99b911-cc88-48d3-907b-0a361c0d5f8d.png">
.

**Comment by AminKolah** [comment]
Sorry it seems like I forgot to "submit" my comments at the end last night.

**Comment by AminKolah** [comment]
With those changes everything else looks good as for the IIM release. For the next release, I can clean up a few more examples so that we can add them as rigid and flexible demonstrations of full FSI using IIM/ILE.

**Comment by drwells** [comment]
We're done!
