### ISSUE TITLE
Jenkins key phrases

### ISSUE THREAD

**Issue by deleeke** [IBAMR/IBAMR#143]
@boyceg 

So, at the moment, all jobs test every PR when it is made and when new commits are pushed.

Additionally, I have set up some new key phrases for the Jenkins PR jobs to watch out for -- these can be in comments or in commit messages I believe.

**retest this please** _builtin to GHPRB, runs all jobs watching this PR_
**opt test**    _runs opt job only_
**skip opt** _skips opt job, put this in commit message or along with "retest this please"_

 _the rest follow same pattern as above_

**llvm test** 
**skip llvm** 
**gcc test**
**skip gcc**

Does that sound good?
(note: at the moment, all members of IBAMR organization can trigger these builds)

**Comment by boyceg** [comment]
@deleeke This all sounds good. Can you point me to where to set this up in Jenkins?

**Comment by deleeke** [comment]
These settings successfully migrated to the new jenkins (so it is allready set up for GCC, clang, and opt builds).

There are two levels of configuration. You can globally configure under `Main Page > Manage Jenkins > Configure System` or an individual job at `Main Page > (click on job) > Configure`.

There is a section called "GitHub Pull Request Builder". You have to expand all the menus by clicking on some "Advanced" buttons that expand hidden options.

The job config looks like this:
![screenshot from 2017-11-05 09-12-31](https://user-images.githubusercontent.com/15056268/32415604-4c5efedc-c20a-11e7-99ef-1d22495615b6.png)

**Comment by drwells** [comment]
We aren't using Jenkins anymore so lets close.
