### ISSUE TITLE
make sure that our SAMRAI patch works with C++17/C++20/C++2b

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1448]
This was mentioned on the mailing list - I haven't noticed a problem but we should double-check, especially now that libMesh requires C++17.

**Comment by boyceg** [comment]
We basically need to remove `register` everywhere.

**Comment by drwells** [comment]
I got a copy of GCC 12 this weekend and updated the patch.

[patch-11.tar.gz](https://github.com/IBAMR/IBAMR/files/8702666/patch-11.tar.gz)

**Comment by drwells** [comment]
This is all fixed in the release.
