### ISSUE TITLE
0.11 Release

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#1454]
Lets try to get this in by the end of June (I'll be gone a lot in July). I added relevant issues to the milestone. In addition, we should get the new examples @AminKolah used in the ILM paper into the repository.

**Comment by drwells** [comment]
# IBAMR release tasks

## Summary

This document describes the process for creating a new release of IBAMR on
GitHub.

## static analysis

- [ ] verify that neither `namespaces.h` nor `app_namespaces.h` are in IBTK or
  IBAMR headers
- [ ] clear basic compilation warnings with GCC and clang on linux
- [ ] compile with the latest libMesh release (which should be configured with
  `--disable-deprecated`) to verify that we do not use any deprecated
  functionality (this will cause compilation errors if we do use them). Add
  version checks: for example, here is one (lightly edited) in
  `IBFEInstrumentPannel.cpp` that uses a macro defined in `libmesh_version.h`:
```cpp
    // new API in 1.4.0
#if LIBMESH_VERSION_LESS_THAN(1, 4, 0)
    boundary_info.build_node_list(nodes, bcs);
#else
    const auto node_list = boundary_info.build_node_list();
    for (const auto& pair : node_list)
    {
        nodes.push_back(std::get<0>(pair));
        bcs.push_back(std::get<1>(pair));
    }
#endif
```
  around APIs to keep backwards compatibility with older versions of libMesh.
- [ ] check the test suite with the oldest (3.7.0) and newest (latest release)
  versions of PETSc. Also check with the oldest (1.1.0) and newest (latest
  release) versions of libMesh.
- [ ] clear basic compilation warnings with GCC and clang on linux and macOS
- [ ] run cppcheck via
```
  cppcheck --force -j4 --enable=all -I./include/ -I./ibtk/include/  \
  $(find ./src ./ibtk/src -name '*.cpp') >cppcheck-results.txt 2>&1
```
- [ ] Check that we don't call functions like
  `ReplicatedMesh::active_local_elements_end()` inside `for`-loop declarations
  since the end iterator is expensive to compute.
- [ ] Check that we always get unique `HierarchyDataOps` by passing `true` as
  the third argument to `getOperationsDouble` et al. This prevents memory leaks
  where a statically stored `HierarchyDataOps` object keeps a patch hierarchy
  alive that is otherwise inaccessible.
- [ ] Run clang-format on the entire code base.
- [ ] Check that we don't use `Eigen::Index` anywhere: that is not available in
  older versions of Eigen. Instead, write
```cpp
    // Older versions of Eigen don't make Eigen::Index publicly available
#if EIGEN_VERSION_AT_LEAST(3, 3, 0)
    using IndexType = Eigen::Index;
#else
    using IndexType = typename MatrixType::Index;
#endif
```
  where needed.

## testing

- [ ] Send out a message to the mailing list about the release asking about the
  status of any open PRs or bugs.
- [ ] Run the test suite on a cluster where libMesh and PETSc were built without
  HDF5 support and HDF5 was installed as a user (see #687). Make sure all
  examples can compile and link.
- [ ] Check that everything works on macOS where dependencies are installed with
  HomeBrew.
- [ ] Double check that all examples compile cleanly with both autotools and
  CMake.
- [ ] In general, run the test suite on as many platforms and configurations as
  possible to weed out problems.

## Copyright

- [ ] Ensure that the top level file `COPYRIGHT` has the release year in it.
- [ ] Check that new files that have been added since the last release have the
  correct copyright header. Try, for example,
```
  git log --diff-filter=A --numstat --pretty='COMMIT: %H %cd' v0.5.1..master
```
  to print all added files between `0.5.1` and `master` or just run
```
grep -L 'by the IBAMR developers' -R ./include/ ./ibtk/include/ ./src/ \
  ./ibtk/src/ | grep -v Makefile.in'
```
  to print all relevant (i.e., files not generated by automake) files which
  currently lack the copyright statement.
- [ ] Run `scripts/maintenance/update_copyright.sh` to update copyright for
  standard file types.

## creating the release

- [ ] Collate the changelog entries on `master` with
  `scripts/maintenance/generate-changes.sh`. Open a PR for this on GitHub: only
  proceed once it is merged.
- [ ] Create a new branch `IBAMR-X.Y` locally off of master and increment the
  version in `VERSION` correctly. Push to GitHub without a PR:
```
  git push https://github.com/ibamr/ibamr.git IBAMR-X.Y
```
  where `X` and `Y` are the version numbers for the release (e.g., for the
  `0.5.0` release they are `0` and `5`). Note that the bugfix number does not go
  into the branch name.
- [ ] Increment the version number on `master` to, e.g., `0.6.0-pre` to signify
  that `master` now corresponds to a prerelease state. Put this in a PR.
- [ ] At this point the release branch and `master` will have diverged. Create a
  release candidate from the `IBAMR-X.Y` branch on GitHub and tag it as a
  prerelease (the tag should be `vX.Y.Z-rc1`). Be sure to include instructions
  on how to patch and compile SAMRAI.
- [ ] If necessary, patch `IBAMR-X.Y` should the release candidate uncover more
  bugs.
- [ ] Once `IBAMR-X.Y` is in good shape tag a proper release, i.e., `vX.Y.Z` and
  create a non-draft release on GitHub.
- [ ] Send out a message to the mailing list about the release.
- [ ] Add a note on the release to the web page.
- [ ] Update version numbers on the build instructions web page.
- [ ] Celebrate!

**Comment by drwells** [comment]
@AminKolah are the examples in paper-IIM-weak_jumps ready to be added to IBAMR?

**Comment by AminKolah** [comment]
On it now ..btw, is there any preference for which examples to include from these 3 preprints? Aside from the flow past a cylinder (currently included), I think we would want to include a few examples for stationary, rigid, and flexible FSI, all under IIM or IIM-ILE folder.

**Comment by drwells** [comment]
My only preference here is to focus more capabilities than applications - e.g., one rigid body example is probably enough, so we should ideally have one of each of the types you listed.

**Comment by AminKolah** [comment]
I just started a branch to add the examples. I will create an issue once I'm done adding all of them, later tonight or tomorrow.

**Comment by drwells** [comment]
We're done!
