### ISSUE TITLE
patching SAMRAI configure to work with newer Macs

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#1496]
This seems to make SAMRAI `configure` work on newer Macs. I needed to run `autoreconf` to rebuild `configure`.

A problem that I ran into was that the Apple `sed` does not seem to work as anticipated by the original authors of `configure.in`, and so in a few places I had to replace `sed` with `gsed`. This is not ideal, but `gsed` is only used in generating `configure`, but is not used by `configure` itself.

Another problem that I encountered was that the m4 files defining some of the `BTNG_XXX` macros were missing, and the macros were only defined in `config/aclocal.m4`. To get those macros, I just copied the original `config/aclocal.m4` into a new file named `config/btng_macros.m4`. I _should_ have stripped out everything else from that file that wasn't needed, but I _didn't_. (Sorry!)

[configure-patch.txt](https://github.com/IBAMR/IBAMR/files/9822674/configure-patch.txt)

**Comment by boyceg** [comment]
This makes things appear to work on my M1 MacBook Pro.

**Comment by drwells** [comment]
Here's an updated patch:

[samrai-2.4.4-patch-ibamr-0.12-pre.txt](https://github.com/IBAMR/IBAMR/files/9833310/samrai-2.4.4-patch-ibamr-0.12-pre.txt)

We can probably bundle this patch with the next release. I'm checking it with autoibamr now.

**Comment by drwells** [comment]
This is bundled with the present release so I will mark this as 'done'.
