### ISSUE TITLE
require C++17

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#1497]
It looks like libMesh now requires ~~C++14~~ C++17. Should we increase our compiler requirements (and start using C++17 features) accordingly?

**Comment by boyceg** [comment]
Actually, I am running into some compilation errors that suggest that libMesh is now using C++17 features even though I specified C++14 as the standard when running `configure`.

**Comment by drwells** [comment]
The present version of libMesh requires C++17. We should automatically detect whichever version they use and set up the correct C++ standard for ourselves. Did something not work on our side?

**Comment by boyceg** [comment]
It is necessary to use `-std=c++17` to compile IBAMR with libMesh, since there are now some C++17-isms in the libMesh public interface.

**Comment by drwells** [comment]
I suspect that the 'detect which version of C++ is available' m4 macro is out of sync with the one shipped by libMesh these days. We should just copy and paste their new version so that we always set up the same flags. The detection mechanism is somewhat cleaner in CMake.

**Comment by boyceg** [comment]
The other part of this is --- if we need to compile with C++17, should we also go ahead and start using C++17 constructs in IBAMR?

**Comment by drwells** [comment]
We only need C++17 if people are using the most recent version of libMesh. C++17 support is pretty good now but people running older systems might not have access to compilers supporting it. Hence I think we should stick with C++11 as the minimum unless we have good non-libMesh reasons to move up.

**Comment by drwells** [comment]
That should be set: the oldest CI configuration uses CENTOS 7 which uses gcc 4.8 or so and libMesh 1.1.0: definitely C++11.

**Comment by boyceg** [comment]
Maybe in 2027. 😆
