### ISSUE TITLE
Inconsistency in HierarchyIntegrator classes when number of levels change during a simulation

### ISSUE THREAD

**Issue by amneetb** [IBAMR/IBAMR#1553]
- Currently we assume that the number of levels (max_levels) stay the same throughout the simulation.

- If they decrease (and maybe for the increasing case as well) the operators (e.g., CCLaplace, HierarchyCellDataOps, etc.) and solvers (e.g., HelmholtzSolver) stay in a stale state. 

- There two reasons for that: 

1.  First is that SAMRAI's gridding algorithm does not call `resetHierarchyConfiguration()` when the simulation has only one level at a particular time step. This can happen when all finer levels have dropped from the domain. 
2. Second, we do not clear the operators and solvers before making call to regriding code 

```
switch (d_regrid_mode)
    {
    case STANDARD:
        d_gridding_alg->regridAllFinerLevels(d_hierarchy, coarsest_ln, d_integrator_time, d_tag_buffer);
        break;
    case AGGRESSIVE:
        for (int k = 0; k < d_gridding_alg->getMaxLevels(); ++k)
        {
            d_gridding_alg->regridAllFinerLevels(d_hierarchy, coarsest_ln, d_integrator_time, d_tag_buffer);
        }
        break;
    default:
        TBOX_ERROR(d_object_name << "::regridHierarchy():\n"
                                 << "  unrecognized regrid mode: " << enum_to_string<RegridMode>(d_regrid_mode) << "."
                                 << std::endl);
    }
```

in `HierarchyIntegrator::regridHierarchy()`.

- We should clear all the operators and solvers in `HierarchyIntegrator::regridHierarchyBeginSpecialized()` which is called before the above piece of code.

- An example of this fix is committed in the branch https://github.com/IBAMR/IBAMR/tree/fix_regriding_issues. 

- The main changes are summarized below for an ease of reference:

1. https://github.com/IBAMR/IBAMR/blob/fix_regriding_issues/ibtk/src/utilities/HierarchyIntegrator.cpp#L443-L447

2. https://github.com/IBAMR/IBAMR/blob/fix_regriding_issues/src/phase_change/PhaseChangeHierarchyIntegrator.cpp#L624-L637

3. https://github.com/IBAMR/IBAMR/blob/fix_regriding_issues/src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp#L910-L923

**Comment by amneetb** [comment]
@drwells : I tried 3 levels also. The fix is working. Attached pics show refining and subsequent coarsening 

<img width="898" alt="1" src="https://user-images.githubusercontent.com/7378152/222285244-07e6bb20-8ad1-4767-8f84-7abe6a76d7bf.png">

<img width="892" alt="2" src="https://user-images.githubusercontent.com/7378152/222285300-1009bb22-741b-458e-9e13-1638f653101e.png">

<img width="908" alt="3" src="https://user-images.githubusercontent.com/7378152/222285352-6b2de001-9350-4e6e-88b1-28ee560611f2.png">

<img width="912" alt="4" src="https://user-images.githubusercontent.com/7378152/222285404-231e53e9-3914-43cb-bf80-23b09f2da7b3.png">

<img width="900" alt="5" src="https://user-images.githubusercontent.com/7378152/222285472-2581634b-2ad3-4979-af5e-c576716e6432.png">

**Comment by drwells** [comment]
This is addressed in the release but we've run out of time to do more testing - I think its fixed but lets leave this issue open until we have some more conclusive evidence.

**Comment by drwells** [comment]
Has this been a problem in the last six months? If not then lets close this issue.

**Comment by amneetb** [comment]
@drwells : yes, this has been fixed. We can close it. If some bug pops up again, I will re-open it.
