### ISSUE TITLE
example/ConstraintIB/falling_sphere

### ISSUE THREAD

**Issue by jxgxx** [IBAMR/IBAMR#157]
I noticed that GNU library was not used in example/ConstraintIB/falling_sphere case. However, we can't make examples/run it without installing GNU library. 
Is it possible to fix this issue?

Tks.

**Comment by amneetb** [comment]
@deleeke This conditional should not be there.
https://github.com/IBAMR/IBAMR/blob/master/examples/ConstraintIB/falling_sphere/Makefile.am#L4

Also, is there a way to pick user installed GSL than system GSL? Some users are stuck with system GSL that is not properly liked to libraries like CBLAS. Can we do something about it?

**Comment by boyceg** [comment]
> @deleeke <https://github.com/deleeke> This conditional should not be there.
> https://github.com/IBAMR/IBAMR/blob/master/examples/ConstraintIB/falling_sphere/Makefile.am#L4 <https://github.com/IBAMR/IBAMR/blob/master/examples/ConstraintIB/falling_sphere/Makefile.am#L4>Elijah is doing a summer internship and probably won't be able to get to this any time soon. I am pretty sure you could manage to remove it. :-)
> Also, is there a way to pick user installed GSL than system GSL? Some users are stuck with system GSL that is not properly liked to libraries like CBLAS. Can we do something about it?
> 
If the system library is broken, it is hard to do anything about it. As you know, it is hard to convince the linker to avoid system installed libraries.

**Comment by amneetb** [comment]
@jxgxx  

In IBAMR source dir, go to examples/ConstraintIB/falling_sphere. Modify Makefile.am

1) Remove line:
 https://github.com/IBAMR/IBAMR/blob/master/examples/ConstraintIB/falling_sphere/Makefile.am#L4 

2) Remove lines
https://github.com/IBAMR/IBAMR/blob/master/examples/ConstraintIB/falling_sphere/Makefile.am#L49-L55

3) Run bootstrap in IBAMR source directory (top source dir)

4) rebuild IBAMR (it will hopefully reconfigure automatically)

**Comment by boyceg** [comment]
I am fixing this now.

**Comment by jxgxx** [comment]
Hi Prof. Griffith and Amneet,

I followed Amneet's steps, and it is working now. Thanks so much.

**Comment by boyceg** [comment]
Fixed by #158.
