### ISSUE TITLE
Error when compiling IBAMR

### ISSUE THREAD

**Issue by Sfiguz7** [IBAMR/IBAMR#1574]
Good day,

I am trying to install IBAMR, following the tutorial at https://ibamr.github.io/linux, but I am getting an error at the very end of the process which prevents me from compiling and testing the examples.

I have followed the procedure using the versions of the required libraries as closely as possible, namely:
1. Boost 1.66.0 (Installed 1.60.0 as the tutorial but when compiling IBAMR version 1.66 or newer is required so I upgraded)
2. Eigen 3.4.0
3. HDF5 1.10.6
4. Silo 4.10.2 (4.10.0 is nowhere to be found on the internet, this is the closest I could get)
5. muParser N/A (bundled with IBAMR so no external installation)
6. OpenMPI 4.0.2
7. Hypre N/A (installed with PETSc per the tutorial)
8. PETSc 3.13.4 (downgraded to Python2 to compile it as configuration was crashing, from what I could find the issue is due to [this](https://gitlab.com/petsc/petsc/-/commit/ca038c9da3f72a552927e65605dfb6b0efa10215)
9. SAMRAI 2.4.4 (applying the suggested patch)
10. LibMesh 1.6.2
11. IBAMR 0.12.0

The whole process goes smoothly up to even installing IBAMR, so I assume everything is linked properly. When trying to compile the examples to test them, though, I get an error which prevents the main2d executable from being built.
I have tried to compile IBAMR with .configure and with CMake just in case but both lead to similar errors when compiling the examples: below I report those obtained using the CMake process as the tutorial mentions it as the preferred method.

I have also found a solved issue from some time back with similar issues but I was unable to figure out a solution especially because all of the libraries are compiled specifying the compiler flags per the tutorial commands: https://github.com/IBAMR/IBAMR/issues/427

How do you suggest I proceed from here on?

Thank you in advance!

---------------------------------------------------------------------------------------------

Compiling error in .txt:
[Error.txt](https://github.com/IBAMR/IBAMR/files/11140041/Error.txt)

<details>
<summary>Compiling error as collapsible content:</summary>

[100%] Linking CXX executable main2d
[100%] Linking CXX executable main2d
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `ompi_mpi_cxx_op_intercept'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Win::Free()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Datatype::Free()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `ompi_mpi_cxx_op_intercept'
collect2: error: ld returned 1 exit status
make[3]: *** [examples/IB/explicit/ex6/CMakeFiles/IB-ex6.dir/build.make:144: examples/IB/explicit/ex6/main2d] Error 1
make[2]: *** [CMakeFiles/Makefile2:8840: examples/IB/explicit/ex6/CMakeFiles/IB-ex6.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Win::Free()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Datatype::Free()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Comm::Comm()'
collect2: error: ld returned 1 exit status
make[3]: *** [examples/IB/explicit/ex5/CMakeFiles/IB-ex5-2d.dir/build.make:128: examples/IB/explicit/ex5/main2d] Error 1
make[2]: *** [CMakeFiles/Makefile2:8784: examples/IB/explicit/ex5/CMakeFiles/IB-ex5-2d.dir/all] Error 2
[100%] Linking CXX executable main2d
/usr/bin/ld: ../../../../lib/libIBTK3d.so: undefined reference to `ompi_mpi_cxx_op_intercept'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `ompi_mpi_cxx_op_intercept'
/usr/bin/ld: ../../../../lib/libIBTK3d.so: undefined reference to `MPI::Win::Free()'
/usr/bin/ld: ../../../../lib/libIBTK3d.so: undefined reference to `MPI::Datatype::Free()'
/usr/bin/ld: ../../../../lib/libIBTK3d.so: undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Win::Free()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Datatype::Free()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Comm::Comm()'
collect2: error: ld returned 1 exit status
make[3]: *** [examples/IB/explicit/ex5/CMakeFiles/IB-ex5-3d.dir/build.make:128: examples/IB/explicit/ex5/main3d] Error 1
make[2]: *** [CMakeFiles/Makefile2:8812: examples/IB/explicit/ex5/CMakeFiles/IB-ex5-3d.dir/all] Error 2
collect2: error: ld returned 1 exit status
make[3]: *** [examples/IB/explicit/ex3/CMakeFiles/IB-ex3.dir/build.make:128: examples/IB/explicit/ex3/main2d] Error 1
make[2]: *** [CMakeFiles/Makefile2:8728: examples/IB/explicit/ex3/CMakeFiles/IB-ex3.dir/all] Error 2
/usr/bin/ld: ../../../../lib/libIBTK3d.so: undefined reference to `ompi_mpi_cxx_op_intercept'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `ompi_mpi_cxx_op_intercept'
/usr/bin/ld: ../../../../lib/libIBTK3d.so: undefined reference to `MPI::Win::Free()'
/usr/bin/ld: ../../../../lib/libIBTK3d.so: undefined reference to `MPI::Datatype::Free()'
/usr/bin/ld: ../../../../lib/libIBTK3d.so: undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Win::Free()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Datatype::Free()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Comm::Comm()'
collect2: error: ld returned 1 exit status
make[3]: *** [examples/IB/explicit/ex2/CMakeFiles/IB-ex2-3d.dir/build.make:128: examples/IB/explicit/ex2/main3d] Error 1
make[2]: *** [CMakeFiles/Makefile2:8700: examples/IB/explicit/ex2/CMakeFiles/IB-ex2-3d.dir/all] Error 2
collect2: error: ld returned 1 exit status
make[3]: *** [examples/IB/explicit/ex1/CMakeFiles/IB-ex1.dir/build.make:128: examples/IB/explicit/ex1/main2d] Error 1
make[2]: *** [CMakeFiles/Makefile2:8644: examples/IB/explicit/ex1/CMakeFiles/IB-ex1.dir/all] Error 2
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `ompi_mpi_cxx_op_intercept'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Win::Free()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Datatype::Free()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Comm::Comm()'
collect2: error: ld returned 1 exit status
make[3]: *** [examples/IB/explicit/ex2/CMakeFiles/IB-ex2-2d.dir/build.make:128: examples/IB/explicit/ex2/main2d] Error 1
make[2]: *** [CMakeFiles/Makefile2:8672: examples/IB/explicit/ex2/CMakeFiles/IB-ex2-2d.dir/all] Error 2
/usr/bin/ld: ../../../../lib/libIBTK3d.so: undefined reference to `ompi_mpi_cxx_op_intercept'
/usr/bin/ld: ../../../../lib/libIBTK3d.so: undefined reference to `MPI::Win::Free()'
/usr/bin/ld: ../../../../lib/libIBTK3d.so: undefined reference to `MPI::Datatype::Free()'
/usr/bin/ld: ../../../../lib/libIBTK3d.so: undefined reference to `MPI::Comm::Comm()'
collect2: error: ld returned 1 exit status
make[3]: *** [examples/IB/explicit/ex4/CMakeFiles/IB-ex4.dir/build.make:128: examples/IB/explicit/ex4/main2d] Error 1
make[2]: *** [CMakeFiles/Makefile2:8756: examples/IB/explicit/ex4/CMakeFiles/IB-ex4.dir/all] Error 2
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `ompi_mpi_cxx_op_intercept'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Win::Free()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Datatype::Free()'
/usr/bin/ld: ../../../../lib/libIBTK2d.so: undefined reference to `MPI::Comm::Comm()'
collect2: error: ld returned 1 exit status
make[3]: *** [examples/IB/explicit/ex0/CMakeFiles/IB-ex0.dir/build.make:128: examples/IB/explicit/ex0/main2d] Error 1
make[2]: *** [CMakeFiles/Makefile2:8616: examples/IB/explicit/ex0/CMakeFiles/IB-ex0.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:7690: examples/CMakeFiles/examples-IB.dir/rule] Error 2
make: *** [Makefile:2610: examples-IB] Error 2

</details>

**Comment by drwells** [comment]
Thanks for reporting this - we need to fix the minor problems with version numbers. Aside from that - it looks like the library is not linking against the MPI C++ bindings. Can you post the generated `CMakeCache.txt` file here?

**Comment by knepley** [comment]
@drwells Aren't the MPI C++ bindings deprecated, and removed from MPI 3.0?

**Comment by drwells** [comment]
Actually - it looks like the problem is with SAMRAI. If we disable linkage with MPI_CXX then we get problems with or without libMesh.

**Comment by Sfiguz7** [comment]
I am unsure if this is still needed judging by the conversation above but just in case it is, this is the last CMakeCache from earlier this afternoon:
[CMakeCache.txt](https://github.com/IBAMR/IBAMR/files/11141454/CMakeCache.txt)

**Comment by drwells** [comment]
Seeing that helps - in particular I see
```
//MPI CXX libraries to link against
MPI_CXX_LIB_NAMES:STRING=mpi
```
i.e., it isn't picking up `mpi_cxx`, but one of our dependencies picked it up. Can you show me the contents of `/home/colombo/sfw/linux/openmpi/4.0.2/lib`?

**Comment by drwells** [comment]
Thanks. Do you have another copy of MPI on this computer? It looks like SAMRAI or libMesh are picking up `mpi_cxx` from some point.

**Comment by Sfiguz7** [comment]
I am quite likely to since I have an installation of deal.II on the same machine, although `mpicc -show` does point to the correct installation:
![image](https://user-images.githubusercontent.com/37039432/229604904-76933ec2-7d5f-486f-b5c6-d0ab3104e9cd.png)

Here is what a quick find query gave as all possible candidates, if it is of any help:
![image](https://user-images.githubusercontent.com/37039432/229605652-c7d3c1c3-bc00-413d-a572-e4a9b07214bb.png)
![image](https://user-images.githubusercontent.com/37039432/229605758-e669927b-4d59-40cb-839c-026d42437f39.png)

**Comment by drwells** [comment]
Can you do `mpic++ -show`?

**Comment by Sfiguz7** [comment]
![image](https://user-images.githubusercontent.com/37039432/229608749-f1d4b1f2-e69f-4dd8-8446-d54e760f2b93.png)

**Comment by drwells** [comment]
One more check: Can you do
```
find /home/colombo/sfw/linux/openmpi -name mpicxx.h`
```
Something is picking up the C++ MPI bindings even though it looks like the library isn't installed.

**Comment by drwells** [comment]
Regarding deal.II - candi requires that you already have MPI installed on your computer. How did you install MPI in that case?

**Comment by Sfiguz7** [comment]
Just in case, I ran it without specifying the path too to no avail
![image](https://user-images.githubusercontent.com/37039432/229614172-14208538-c843-4fd2-b83c-3cc25ce9baef.png)

As for Deal.II/candi, I do not recall needing to install MPI, although I am not 100% sure. By looking through the "install" logs with `grep /var/log/dpkg.log " install "` I have found these (I stopped screenshotting after the first few):
![image](https://user-images.githubusercontent.com/37039432/229616196-ba54560a-ee1b-4f54-b8a9-9c24e5a2d17b.png)
![image](https://user-images.githubusercontent.com/37039432/229616229-b4885dec-54b7-483d-83a9-0556b7c0826f.png)
![image](https://user-images.githubusercontent.com/37039432/229616288-32ca0516-5849-413e-9436-c3521cfee007.png)
![image](https://user-images.githubusercontent.com/37039432/229616405-6ce39e6f-e059-476d-b48e-148e1085bdac.png)

Judging by the times, I assume they were installed by the automated pipeline.

If helpful, I also attach below what I believe to be the list of all compilers installed:
![image](https://user-images.githubusercontent.com/37039432/229617845-d9ed6e23-f9be-4f27-8b2b-a616927f3186.png)

**Comment by drwells** [comment]
This is an interesting case because either SAMRAI or libMesh picked up the installation with mpi_cxx whereas the one you used to compile IBAMR did not. I suspect SAMRAI is the problem - we check that libMesh is linked against the same MPI implementation but we cannot do that with SAMRAI.

If you have `openmpi-bin` installed then you don't need to compile your own version of MPI - can you try recompiling IBAMR's dependencies with those MPI compiler wrappers instead of the one you installed yourself?

**Comment by Sfiguz7** [comment]
Excuse the delayed answer, timezones came into play.
It worked! Thank you again for the availability and on point support!

------

For future reference, if anyone encounters the same issues:
- I have repeated the entire process starting from a clean slate, re-installing even Boost and Eigen to be sure.
- I have cleared the .bashrc of every additional line added during the process before restarting
- I have skipped the OpenMPI installation step
- From that step on, I have replaced the compiler flags everywhere with `CC=mpicc`, `CXX=mpicxx`, `FC=mpifort`, `F77=mpifort`
- For the ibamr compilation, the `-DMPI_ROOT` flag was set to `/usr/lib/x86_64-linux-gnu/openmpi/lib`, which was found through `mpicc --showme:link`; the output of that command needs to be trimmed a little, you can see here below what I had and trim yours accordingly
![image](https://user-images.githubusercontent.com/37039432/229746729-1f350c0e-c96f-4142-a9f9-9cec25c19ff7.png)


-----

The versions I have used for my installation are the ones reported at the top of the page: I still had to use python2 to compile PETSc (for some reason downgrading to Python 3.8 and below did not fix the issue), which was done by changing the `$HOME/sfw/petsc/3.13.4/configure.txt` file, at line 4, to search through the python implementations in the corresponding order. You can use the `update-alternatives` commands to install multiple python implementations and switch between them too, if you wish.
