### ISSUE TITLE
IMPInitializer::registerMesh()

### ISSUE THREAD

**Issue by amneetb** [IBAMR/IBAMR#16]
a) Ref: https://github.com/IBAMR/IBAMR/blob/f03aed6d0e1fa56d2e03478b1d6346883002db6f/src/IB/IMPInitializer.cpp#L172-L173
```
  d_vertex_offset[level_number].resize(d_vertex_offset[level_number].size() + 1,
                                         mesh_idx == 0 ? 0 : d_num_vertex[level_number][mesh_idx - 1]);
```
It looks like `d_vertex_offset` is just storing the number of vertices of previous mesh registered with this routine, instead of sum of all the number of previously registered mesh vertices.

b) This info is getting used in IMPInitializer::getCanonicalLagrangianIndex() routine and initializeLSiloDataWriter():
https://github.com/IBAMR/IBAMR/blob/f03aed6d0e1fa56d2e03478b1d6346883002db6f/src/IB/IMPInitializer.cpp#L569

**Comment by boyceg** [comment]
Please add in a link to the code in question (see details [here](http://andrew.yurisich.com/work/2014/07/16/dont-link-that-line-number) on how to do this the "right" way).

**Comment by amneetb** [comment]
Does this look ok?

**Comment by boyceg** [comment]
Not quite; please try to follow the directions from the linked article (and let me know if this doesn't work):

First, highlight the code that you want to link to, just like in the examples above. Then, tap the "y" key to jump to the last commit found for that region.

**Comment by boyceg** [comment]
I think that you are correct --- it looks like there should be an accumulation that is being omitted here.
