### ISSUE TITLE
HierarchyMathOps::grad CC->SC,FC not behaving as expected

### ISSUE THREAD

**Issue by nishantnangia** [IBAMR/IBAMR#160]
If I want to store
U <- alpha * grad Phi + beta * U

for constant alpha and beta, SC U and CC Phi, one can use HierarchyMathOps::grad() as seen here:
https://github.com/IBAMR/IBAMR/blob/master/src/navier_stokes/StaggeredStokesProjectionPreconditioner.cpp#L322

which works fine because the underlying Fortran code takes into account the grad Phi and beta * U together: 
https://github.com/IBAMR/IBAMR/blob/master/ibtk/src/math/fortran/grad2d.f.m4#L430

However, if I want to do the same gradient computation using variable SC alpha, the underlying Fortran code first computes alpha grad Phi terms:
https://github.com/IBAMR/IBAMR/blob/master/ibtk/src/math/fortran/flux2d.f.m4#L328

and then 'axpys' the beta U term: 
https://github.com/IBAMR/IBAMR/blob/master/ibtk/src/math/PatchMathOps.cpp#L3585
https://github.com/IBAMR/IBAMR/blob/master/ibtk/src/math/PatchMathOps.cpp#L3644

However in these axpy statements, src2 now holds alpha*grad Phi because it is the same patch data as dst, so what is eventually returned by HierarchyMathOps::grad() is 
U <- beta*alpha*grad Phi +alpha*grad Phi

instead of 

U <- beta*U + alpha*grad*Phi

==
Similar issues for FC U and src2.
Should we be able to call HierarchyMathOps::grad() with dst == src2 for non-constant alpha (as is the case with constant alpha)?

**Comment by boyceg** [comment]
> Should we be able to call HierarchyMathOps::grad() with dst == src2 for non-constant alpha (as is the case with constant alpha)?

This is certainly how the code is meant to work. It sounds like there is a missing code branch for that case --- or is the existing code branch just buggy?

**Comment by nishantnangia** [comment]
The existing code branch is just buggy due to the axpy occurring after the gradient computation. Computing the gradient and adding beta U concurrently as is done for the constant alpha case should fix it (as is done here https://github.com/IBAMR/IBAMR/blob/master/ibtk/src/math/fortran/grad2d.f.m4#L430).

**Comment by boyceg** [comment]
> On Sep 7, 2017, at 10:59 AM, Nishant Nangia <notifications@github.com> wrote:
> 
> The existing code branch is just buggy due to the axpy occurring after the gradient computation. Computing the gradient and adding beta U concurrently as is done for the constant alpha case should fix it (as is done here https://github.com/IBAMR/IBAMR/blob/master/ibtk/src/math/fortran/grad2d.f.m4#L430 <https://github.com/IBAMR/IBAMR/blob/master/ibtk/src/math/fortran/grad2d.f.m4#L430>).
> 
Is it clear how to fixe the bug? Or do you need for me to investigate?

**Comment by nishantnangia** [comment]
No need to investigate -- I'll submit a PR with the fix tomorrow.

**Comment by boyceg** [comment]
Nishant, did you get a PR in for this issue?

**Comment by nishantnangia** [comment]
Oops I forgot to fix this, thanks for reminding me :)

I'll try to do it soon.

**Comment by boyceg** [comment]
Closed by #177.
