### ISSUE TITLE
Bug in IBTK_MPI::allGather()

### ISSUE THREAD

**Issue by amneetb** [IBAMR/IBAMR#1656]
We do not handle the corner case of x_in being nullptr or x_in_size being zero properly. A processor may not have anything to contribute to the all gather operation. Presently the code seg faults because we do 

`mpi_type_id(x_in[0])` 

here: https://github.com/IBAMR/IBAMR/blob/master/ibtk/include/ibtk/private/IBTK_MPI-inl.h#L147

 If `x_in` is nullptr or has no memory then there is an error. Possible fix that I did locally:

```    
    T dummy_value;
    MPI_Allgatherv(x_in,
                   size_in,
                   mpi_type_id(dummy_value),
                   x_out,
                   rcounts.data(),
                   disps.data(),
                   mpi_type_id(dummy_value),
                   IBTK_MPI::getCommunicator());
```

MPI_Allgatherv seems to handle the case of x_in == nullptr and x_in_size == 0 properly. It is our mpi_type passing that causes segfault.

**Comment by amneetb** [comment]
Maybe this is a more C++ way of doing things (calling the default constructor in place):

```
    MPI_Allgatherv(x_in,
                   size_in,
                   mpi_type_id(T()),
                   x_out,
                   rcounts.data(),
                   disps.data(),
                   mpi_type_id(T()),
                   IBTK_MPI::getCommunicator());

```

**Comment by drwells** [comment]
Nice catch - the present version is definitely wrong and your fix is what we should do.

**Comment by drwells** [comment]
There are a bunch of other things that need to be tidied-up here (e.g., we don't check any MPI return codes). I'll take a look in a week or so once some grant applications are in.
