### ISSUE TITLE
Diffusion time stepping scheme in AdvDiffSemiImplicitHierarchyIntegrator

### ISSUE THREAD

**Issue by Raamkrishnan** [IBAMR/IBAMR#1659]
@drwells @boyceg In AdvDiffSemiImplicitHierarchyIntegrator class, diffusion time stepping schemes such as BACKWARD_EULER and TRAPEZOIDAL_RULE are not implemented correctly. Both of these schemes use only the current value (nth time level):
[
](https://github.com/IBAMR/IBAMR/blob/513bf77a0c6acb1fc6b364dd72a7fa25ffc002f8/src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp#L564)

Please take a look. If you want I can push the patch with the correct time stepping schemes.

**Comment by Raamkrishnan** [comment]
AdvDiffSemiImplicitHierarchyIntegrator:
https://github.com/IBAMR/IBAMR/blob/513bf77a0c6acb1fc6b364dd72a7fa25ffc002f8/src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp#L564

EnthalpyHierarchyIntegrator:
https://github.com/IBAMR/IBAMR/blob/544764fba314d2d0d1e502119ed92463264dbb1c/src/phase_change/EnthalpyHierarchyIntegrator.cpp#L494

I use a new time-level value based on the time-stepping scheme in IntegrateHierarchy here.

**Comment by amneetb** [comment]
@Raamkrishnan : it depends how you are updating C and D here
https://github.com/IBAMR/IBAMR/blob/513bf77a0c6acb1fc6b364dd72a7fa25ffc002f8/src/adv_diff/BrinkmanAdvDiffSemiImplicitHierarchyIntegrator.cpp#L493-L495

Yes, you are passing current patch data indices of C and D, but if they are updated according to their new values in the helper class then it should be fine. Take a close look into how they are getting updated. Do we have new patch data indices of C and D as well?

**Comment by amneetb** [comment]
It looks like this needs to be added to integrateHierarchy as well with `new_time` argument 

https://github.com/IBAMR/IBAMR/blob/513bf77a0c6acb1fc6b364dd72a7fa25ffc002f8/src/adv_diff/BrinkmanAdvDiffSemiImplicitHierarchyIntegrator.cpp#L236-L245

Perhaps similar thing with C_current.

**Comment by amneetb** [comment]
@drwells : This bug has been fixed in #1657 and #1660. Both PRs have been merged, so we can close it.
