### ISSUE TITLE
IMPInitializer::tagCellsForInitialRefinement()

### ISSUE THREAD

**Issue by amneetb** [IBAMR/IBAMR#17]
Ref: https://github.com/IBAMR/IBAMR/blob/f03aed6d0e1fa56d2e03478b1d6346883002db6f/src/IB/IMPInitializer.cpp#L433

```
const bool can_be_refined = level_number + 2 < max_levels;
```
Shouldn't this be:
```
const bool can_be_refined = level_number + 2 <= max_levels;
```
P.S: This info is not getting used in the code as of now.

**Comment by boyceg** [comment]
Please add in a link to the code in question (see details [here](http://andrew.yurisich.com/work/2014/07/16/dont-link-that-line-number) on how to do this the "right" way).

**Comment by amneetb** [comment]
Does this look ok?

**Comment by boyceg** [comment]
Not quite; please try to follow the directions from the linked article (and let me know if this doesn't work):

First, highlight the code that you want to link to, just like in the examples above. Then, tap the "y" key to jump to the last commit found for that region.

**Comment by amneetb** [comment]
Yes, I did that. The link that I posted seems to be doing the right thing in my browser (I can see the highlighted line of the code and the latest commit for IMPInitializer.cpp)

**Comment by boyceg** [comment]
Note that `max_levels` is the maximum number of levels in the hierarchy, and that levels are numbered starting from `0`. `max_levels == 2` means that the level number for the finest possible level is `1`.

Cells on a level can be refined if the next finer level has a level number that is no greater than `max_levels - 1`. So:
```
can_be_refined = level_number + 1 <= max_levels - 1;
```
which is the same thing as:
```
can_be_refined = level_number + 2 <= max_levels;
```
Does this make sense?

**Comment by boyceg** [comment]
@amneetb Please add a helper function (e.g. in IBTK utilities) to perform this operation, which should appear in a few different places.

**Comment by amneetb** [comment]
Sure, I will add a helper function.  

Just to be clear you approve of "<=" instead of "<" in the code?

**Comment by boyceg** [comment]
I think so, but please double-check my logic.
