### ISSUE TITLE
Minor bug in #1707

### ISSUE THREAD

**Issue by Raamkrishnan** [IBAMR/IBAMR#1716]
Hi @drwells,

Recently, when I ran all the examples in the directory ```examples/multiphase_flow```, I encountered an error in the multiphase/ex10 while writing the visit files. When I did lldb, I figured out that the code fails in the following line: 

https://github.com/IBAMR/IBAMR/blob/97340e60e6a9173f6a1581896705f0d2b06d378f/src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp#L1812

This is because ```d_omega_idx``` is already deallocated in the above function (line 1765 in ```INSVCStaggeredHierarchyIntegrator``` class). So it is necessary to allocate ```d_omega_idx``` to plot this variable in the visit.

I can fix this and push it.

**Comment by drwells** [comment]
Thanks - can you add a test to make sure this stays fixed?

**Comment by drwells** [comment]
Fixed by #1717.
