### ISSUE TITLE
check GSL m4

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#179]
It appears that libgslcblas is not being linked to in some cases when checking for libgsl (e.g. using clang on the VM).

**Comment by drwells** [comment]
In case someone else wants to look into this: be aware that libgsl is underlinked: one must link executables that use GSL routines with a cblas library even if the executable itself does not use any cblas functions since libgsl igself requires a cblas.

**Comment by amneetb** [comment]
How about using something like this instead?

https://github.com/ampl/gsl/blob/master/gsl.m4

**Comment by boyceg** [comment]
Is it adequate to follow GSL's own recommendations:

https://www.gnu.org/software/gsl/manual/html_node/Autoconf-Macros.html

**Comment by drwells** [comment]
CMake's own `FindGSL.cmake` is sufficient: I can use it to compile the examples that depend on GSL.

Closed by #1020.
