### ISSUE TITLE
Updating to the current libMesh version

### ISSUE THREAD

**Issue by rossisimone** [IBAMR/IBAMR#191]
With the current version of libMesh C++11 is required and UniquePtr<T> is simply an alias for std::unique_ptr<T>. So calling UniquePtr<T> p(NULL) is not allowed anymore.
For backward compatibility, I believe it could be enough to use the default constructors 
UniquePtr<T> p(NULL); ->  UniquePtr<T> p;
Any thought?

**Comment by boyceg** [comment]
One thing to be careful about is that C++11 flags are used for all libraries using C++. I don't see a way for IBAMR itself to check that, but it can be a problem when it comes to linking. We are going to try to get a Jenkins build setup to verify that the code works with C++11 flags, and to start to use C++11 constructs to simplify some things.

**Comment by rossisimone** [comment]
I configured IBAMR using std=c++11 in the CPPFLAGS.
The only compilation error I got was about the UniquePtr.
Fixing that, everything else compiled and linked with no problems.
The changes I introduced should (hopefully) also be compatible with pre c++11 codes.

I did not run all the tests though.

**Comment by boyceg** [comment]
This is fixed by #192.
