### ISSUE TITLE
Semi Implicit Advection Diffusion solver does not tag cells for refinement

### ISSUE THREAD

**Issue by abarret** [IBAMR/IBAMR#195]
The semi implicit advection diffusion solver does not supply an implementation of applyGradientDetectorSpecialized()

**Comment by amneetb** [comment]
Yep. We are doing that locally in the src.

**Comment by amneetb** [comment]
The stop gap is to register a user-defined function that tags cell. This is more flexible anyways :-)

**Comment by boyceg** [comment]
@abarret, did we get around to fixing this?

**Comment by abarret** [comment]
No. But I don't think there's something to fix. It's unclear what things (if any) should be tagged for refinement. As @amneetb pointed out, you can always register a function that tags cells.
