### ISSUE TITLE
IBMethod::setLinearizedPosition()

### ISSUE THREAD

**Issue by amneetb** [IBAMR/IBAMR#20]
Ref
https://github.com/IBAMR/IBAMR/blob/f03aed6d0e1fa56d2e03478b1d6346883002db6f/src/IB/IBMethod.cpp#L545-#L560

The matrix d_force_jac should be constructed at each timestep to account for updated position of structure.  

```
if (!d_force_jac) 
``` 
should be removed and replaced by 
``` 
MatDestroy(&d_force_jac);
d_force_jac = NULL;
```
followed by other existing statements.

**Comment by amneetb** [comment]
Please review the changes. This seemed to have fixed the PETSc error I was getting.

**Comment by boyceg** [comment]
> On Jun 25, 2015, at 4:48 PM, Amneet Bhalla <notifications@github.com> wrote:
> 
> Ref
> https://github.com/IBAMR/IBAMR/blob/f03aed6d0e1fa56d2e03478b1d6346883002db6f/src/IB/IBMethod.cpp#L545-#L560 <https://github.com/IBAMR/IBAMR/blob/f03aed6d0e1fa56d2e03478b1d6346883002db6f/src/IB/IBMethod.cpp#L545-#L560>
> The matrix d_force_jac should be constructed at each timestep to account for updated position of structure.
> 
> if (!d_force_jac) 
> should be removed and replaced by
> 
> MatDestroy(&d_force_jac);
> d_force_jac = NULL;
> followed by other existing statements.
> 

@amneetb I think that you are on the right track here. However, I think that we want to put the logic into constructLagrangianForceJacobian:

https://github.com/IBAMR/IBAMR/blob/f03aed6d0e1fa56d2e03478b1d6346883002db6f/src/IB/IBMethod.cpp#L780 <https://github.com/IBAMR/IBAMR/blob/f03aed6d0e1fa56d2e03478b1d6346883002db6f/src/IB/IBMethod.cpp#L780>

The Jacobian operator needs to be reset whenever the SNES "decides it needs to be reset"; this is managed via constructLagrangianForceJacobian().

What do you think?

**Comment by amneetb** [comment]
Yeah, makes more sense to put in there.
