### ISSUE TITLE
Fast sweeping method on adaptive mesh refinement

### ISSUE THREAD

**Issue by YafuR** [IBAMR/IBAMR#223]
Hi, I am doing a project and wondering how to get the distance field if we apply FSM on a mesh that has diffrent refinement level. I saw there are methods about FSM but it's empty.

**Comment by amneetb** [comment]
@YafuR There are two examples in the level-set example directory, one using fast sweeping method and the other using relaxation method. The relaxation method provides several discretization schemes like EN03, WENO3, WENO5 with subcell and mass constraints. They should both work on AMR hierarchies. We are in the process of merging multiphase branch in master and we will put some examples showing that.

**Comment by nishantnangia** [comment]
Take a look at the 2D example level_set/ex0 (https://github.com/IBAMR/IBAMR/tree/master/examples/level_set/ex0). By default, it is using the fast sweeping method to find the distance from a circular interface on a partially refined grid.

**Comment by boyceg** [comment]
@YafuR does this address your question?

**Comment by drwells** [comment]
@YafuR I believe the other posters answered your question, so I am going to close this issue.

Let us know if you have more questions or need help running something :)
