### ISSUE TITLE
Bug in constraining overlapping parts

### ISSUE THREAD

**Issue by cpuelz** [IBAMR/IBAMR#239]
https://github.com/IBAMR/IBAMR/blob/aa32c9a1f7ee84a657d8922602db686a06eedd00/src/IB/IBFEMethod.cpp#L515
@boyceg should this be X_system_name?

**Comment by boyceg** [comment]
> On May 30, 2018, at 2:50 PM, Charles Puelz <notifications@github.com> wrote:
> 
> https://github.com/IBAMR/IBAMR/blob/aa32c9a1f7ee84a657d8922602db686a06eedd00/src/IB/IBFEMethod.cpp#L515 <https://github.com/IBAMR/IBAMR/blob/aa32c9a1f7ee84a657d8922602db686a06eedd00/src/IB/IBFEMethod.cpp#L515>
> @boyceg <https://github.com/boyceg> should this be X_system_name?
> 
Uhh.

**Comment by boyceg** [comment]
> On May 30, 2018, at 2:51 PM, Boyce Griffith <boyceg@gmail.com> wrote:
> 
> 
> 
>> On May 30, 2018, at 2:50 PM, Charles Puelz <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> https://github.com/IBAMR/IBAMR/blob/aa32c9a1f7ee84a657d8922602db686a06eedd00/src/IB/IBFEMethod.cpp#L515 <https://github.com/IBAMR/IBAMR/blob/aa32c9a1f7ee84a657d8922602db686a06eedd00/src/IB/IBFEMethod.cpp#L515>
>> @boyceg <https://github.com/boyceg> should this be X_system_name?
>> 
> Uhh.

Although this is mostly harmless — the code is not actually using force DOFs where it should be using displacement DOFs.
