### ISSUE TITLE
INS integrators never call regridHierarchy() in IB simulations

### ISSUE THREAD

**Issue by nishantnangia** [IBAMR/IBAMR#250]
During regridding, IBHierarchyIntegrator::regridHierarchy() calls HierarchyIntegrator::regridHierarchy():

https://github.com/IBAMR/IBAMR/blob/master/src/IB/IBHierarchyIntegrator.cpp#L480

I think this means that regridHierarchy routines implemented by derived INS integrators will *never* be called during regridding (i.e. the ones implemented by INSStaggeredHierarchyIntegrator, etc.). Is this done intentionally, or is this a bug?

==

As an aside, we had added calls to initialize composite grid data to HierarchyIntegrator, so that they would be called during IBHierarchyIntegrators' regrid routine:
https://github.com/IBAMR/IBAMR/blob/master/ibtk/src/utilities/HierarchyIntegrator.cpp#L496

Perhaps these calls need to be moved to the derived integrators' regridHierarchy() routines?

**Comment by amneetb** [comment]
Perhaps these calls need to be moved to the derived integrators' regridHierarchy() routines?

@nishantnangia : not moved but derived classes should also make a call to these routines if they override HierarchyIntegrator::regridHierarchy().

**Comment by nishantnangia** [comment]
@amneetb Right, that seems sensible.

**Comment by boyceg** [comment]
> On Jun 29, 2018, at 8:07 PM, Nishant Nangia <notifications@github.com> wrote:
> 
> During regridding, IBHierarchyIntegrator::regridHierarchy() calls HierarchyIntegrator::regridHierarchy():
> 
> https://github.com/IBAMR/IBAMR/blob/master/src/IB/IBHierarchyIntegrator.cpp#L480 <https://github.com/IBAMR/IBAMR/blob/master/src/IB/IBHierarchyIntegrator.cpp#L480>
> I think this means that regridHierarchy routines implemented by derived INS integrators will never be called during regridding (i.e. the ones implemented by INSStaggeredHierarchyIntegrator, etc.). Is this done intentionally, or is this a bug?
> 
I am not sure about the intention, but I do know that we don't want to call both HierarchyIntegrator::regridHierarchy() and also INSHierarchyIntegrator::regridHierarchy(), because both call GriddingAlgorithm::regridAllFinerLevels().

The right thing to do might be to call INSHierarchyIntegrator::regridHierarchy() instead of HierarchyIntegrator::regridHierarchy().

Maybe a better design would be something like --- HierarchyIntegrator::regridHierarchy() is not virtual, but calls virtual methods (e.g. regridHierarchySpecialized(), or beginRegridHierarchySpecialized() and endRegridHierarchySpecialized()) for all of the composed HierarchyIntegrator objects?
> As an aside, we had added calls to initialize composite grid data to HierarchyIntegrator, so that they would be called during IBHierarchyIntegrators' regrid routine:
> https://github.com/IBAMR/IBAMR/blob/master/ibtk/src/utilities/HierarchyIntegrator.cpp#L496 <https://github.com/IBAMR/IBAMR/blob/master/ibtk/src/utilities/HierarchyIntegrator.cpp#L496>
> Perhaps these calls need to be moved to the derived integrators' regridHierarchy() routines?

**Comment by amneetb** [comment]
Yeah, INSHierarchyIntegrator::regridHierarchy() should be called instead of HierarchyIntegrator::regridHierarchy() for an easy fix.

**Comment by boyceg** [comment]
> Yeah, INSHierarchyIntegrator::regridHierarchy() should be called instead of HierarchyIntegrator::regridHierarchy() for an easy fix.
> 
Can one of you make a PR for this?

**Comment by nishantnangia** [comment]
https://github.com/IBAMR/IBAMR/pull/343

**Comment by drwells** [comment]
Fixed by #524.
