### ISSUE TITLE
Use the technique from #257 on the google tests

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#259]
As far as I can tell, the `gtest`, `gtest-long`, and `gtest-all` targets are structured in the same way as the examples were prior to #257. We should use the same technique to parallelize them.

**Comment by boyceg** [comment]
> As far as I can tell, the gtest, gtest-long, and gtest-all targets are structured in the same way as the examples were prior to #257 <https://github.com/IBAMR/IBAMR/pull/257>. We should use the same technique to parallelize them.

I am not sure if we can run these tests in parallel or not, but I guess that it doesn't hurt to make it possible to do it.

**Comment by drwells** [comment]
I have done some more investigation on the test suite. I don't know a lot about googletest but I figure it might help to record some of my research here.

Here is a typical test file (a truncated version of `examples/IB/explicit/ex0/test_main.cpp`):

```cpp
#include <gtest/gtest.h>
#include "example.cpp"
// other C++ includes

double bench;
// more global static variables

// set NDIM here conditionally

TEST(TEST_CASE_NAME, example_runs){
    EXPECT_TRUE(ex_runs);
}

TEST(TEST_CASE_NAME, u_L1Norm) {
    bench  = bench_u_err[L1_IDX];
    actual =  u_err[L1_IDX];
    EXPECT_LE(std::abs((actual - bench)), (bench*REL_ERROR));
}

// other test cases

int main( int argc, char** argv ) {
    testing::InitGoogleTest( &argc, argv );
    // set up some expected test results
    
    ex_argc = argc;
    ex_argv = argv;
    ex_runs = run_example(ex_argc, ex_argv, u_err, p_err);
    return RUN_ALL_TESTS( );
}
```

i.e., each `test_main.cpp` is compiled as a standalone executable. Running `make gtest` runs each executable in sequence. Put another way: gtest is only used to write and compile the tests and not run them, so it operates at a level independent of parallelization.

Autotools has [some](https://www.gnu.org/software/automake/manual/html_node/Parallel-Test-Harness.html) support for compiling and running a test suite and collecting the results. It should be feasible to reuse the existing tests with the autotools test harness to essentially verify that the output of the examples has not changed significantly.

**Comment by drwells** [comment]
#494 fixes this issue by implementing the test suite in a way independent of the build system.
