### ISSUE TITLE
d_split_forces boolean

### ISSUE THREAD

**Issue by amneetb** [IBAMR/IBAMR#26]
Ref

https://github.com/IBAMR/IBAMR/blob/d097180162281c0980d266ae43ac2e5259dbad82/src/IB/IBFEMethod.cpp#L1309
https://github.com/IBAMR/IBAMR/blob/d097180162281c0980d266ae43ac2e5259dbad82/src/IB/IBFEMethod.cpp#L1351

The above two lines look suspicious. If d_split_forces is true on line 1309, it won't reach the statements of block L 1351. 

Also, what is weak form for external surface forces. Are you including it in the definition of PK1*N or it's treated differently?

**Comment by boyceg** [comment]
> On Aug 4, 2015, at 5:55 PM, Amneet Bhalla <notifications@github.com> wrote:
> 
> Ref
> 
> https://github.com/IBAMR/IBAMR/blob/d097180162281c0980d266ae43ac2e5259dbad82/src/IB/IBFEMethod.cpp#L1309 <https://github.com/IBAMR/IBAMR/blob/d097180162281c0980d266ae43ac2e5259dbad82/src/IB/IBFEMethod.cpp#L1309>
> https://github.com/IBAMR/IBAMR/blob/d097180162281c0980d266ae43ac2e5259dbad82/src/IB/IBFEMethod.cpp#L1351 <https://github.com/IBAMR/IBAMR/blob/d097180162281c0980d266ae43ac2e5259dbad82/src/IB/IBFEMethod.cpp#L1351>
> The above two lines look suspicious. If d_split_forces is true on line 1309, it won't reach the statements of block L 1351.
> 
I think that this is a bug. It at least could be made more clear.

You compute the surface traction forces when evaluating the weak form of the Lagrangian body force density when you **do** **not* want to account for those forces in the body force density. The way to remember this is that if you start out with a force that includes both the interior (div PP) and transmission (e.g., PP N) forces and then integrate by parts, then you will wipe out the transmission force.

The initial implementation basically was: you either split out the the transmission forces (so: include them in this weak form) or you don't (so: do include them in this weak form). We are now talking about splitting out normal but not tangential surface forces. Probably there should be two different flags: split_normal_surface_forces and split_tangential_surface_forces.
> Also, what is weak form for external surface forces. Are you including it in the definition of PK1*N or it's treated differently?
> 
I'm not sure what you are asking. The current implementation only uses a weak form for the interior force density, and assumes you can evaluate any surface forces without resorting to a weak form. If we need to compute derivatives of surface forces, then we will probably need to resort to a weak form for that computation.

**Comment by boyceg** [comment]
This is fixed in #168.
