### ISSUE TITLE
Automating installation of dependencies

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#268]
Split from the discussion in #266.

I talked with @abarret about this at lunch: a major benefit of #188 is that we can download and compile everything with one script. This is a problem that needs to be solved and `easy_install.py` does it.

I do have some reservations, however, about whether or not this is the best way forward: [AFAICT](https://www.mcs.anl.gov/petsc/miscellaneous/external.html) PETSc cannot, presently, download and install several libraries that we need (such as boost, silo, eigen, and libmesh), so we will be on our own for managing those dependencies (and managing their own dependencies and interdependencies, etc).

I think that we can lessen our own maintenance burden by supporting installation of IBAMR through https://github.com/spack/spack: spack (supercomputer package manager) already supports installation of all of the libraries we need (it is from LLNL after all :)) and, more importantly, other people maintain both those build scripts and spack itself (which handles dependency resolution, linking against provided system libraries, etc. etc. etc.). At the end of the day, once someone installs spack and (optionally) points it at their system MPI installation, installing IBAMR will be as easy as `spack install IBAMR`).

Spack seems like a better choice to me since it can already handle all of our external dependencies and has a large developer community (i.e., other people will maintain stuff we need).

Note: AFAICT the issue of dependency resolution is essentially orthogonal to our choice of build system. What we do here does not really impact the advantages and disadvantages of moving to `BuildSystem` in #188, just how much effort we want to expend on `easy_install.py`.

**Comment by boyceg** [comment]
Can spack installation itself be automated? If so, then it seems reasonable to use that to automate autoconf-based configure, and also possibly BuildSystem-based configure.

**Comment by drwells** [comment]
> Can spack installation itself be automated?

I do not think so, but there is not much to install: Margaret Anne and I used spack to install petsc on her laptop and all we had to do was write a configuration file on her machine describing where to find `openssl` (unfortunately, this part was machine dependent), which was approximately

```
packages:
    openssl:
        paths:
            openssl@1.0.2g: /usr
        buildable: False
```

at that point we essentially just ran `spack install petsc` and things worked correctly. I don't fully understand the openssl dependency; I did not have to do that on my workstation but the Macintosh was not happy without out it. There were a few other things we needed to do: I wrote it down on her machine.

> If so, then it seems reasonable to use that to automate autoconf-based configure, and also possibly BuildSystem-based configure.

Yes. For example, here is a truncated version of the PETSc script that comes with spack:
```python
import os
import sys
from spack import *


class Petsc(Package):
    homepage = "http://www.mcs.anl.gov/petsc/index.html"
    # etc.

    maintainers = ['balay', 'barrysmith', 'jedbrown']
    # etc.

    version('3.9.3', '7b71d705f66f9961cb0e2da3f9da79a1')
    version('3.9.2', '8bedc0cd8c8603d54bfd99a6e8f77b3d')
    # etc...
    # support for different versions is controlled by hash

    variant('shared',  default=True,
            description='Enables the build of shared libraries')
    variant('mpi',     default=True,  description='Activates MPI support')
    variant('double',  default=True,
            description='Switches between single and double precision')
    # etc... 

    # ---------------> known conflict resolution <---------------
    conflicts('^intel-mkl', when='@3.8.0')

    # temporary workaround Clang 8.1.0 with XCode 8.3 on macOS, see
    # https://bitbucket.org/petsc/petsc/commits/4f290403fdd060d09d5cb07345cbfd52670e3cbc
    # the patch is an adaptation of the original commit to 3.7.5
    if sys.platform == "darwin":
        patch('macos-clang-8.1.0.diff',
              when='@3.7.5%clang@8.1.0:')
    patch('pkg-config-3.7.6-3.8.4.diff', when='@3.7.6:3.8.4')

    # ---------------> known dependency resolution <---------------

    # Virtual dependencies
    # Git repository needs sowing to build Fortran interface
    depends_on('sowing', when='@develop')

    # PETSc, hypre, superlu_dist when built with int64 use 32 bit integers
    # with BLAS/LAPACK
    depends_on('blas')
    depends_on('lapack')
    depends_on('mpi', when='+mpi')

    # Build dependencies
    depends_on('python@2.6:2.8', type='build')

    # Other dependencies
    depends_on('metis@5:~int64+real64', when='@:3.7.99+metis~int64+double')
    depends_on('metis@5:~int64', when='@:3.7.99+metis~int64~double')
    depends_on('metis@5:+int64+real64', when='@:3.7.99+metis+int64+double')
    depends_on('metis@5:+int64', when='@:3.7.99+metis+int64~double')
    # petsc-3.8+ uses default (float) metis with any (petsc) precision
    depends_on('metis@5:~int64', when='@3.8:+metis~int64')
    depends_on('metis@5:+int64', when='@3.8:+metis+int64')
    # etc...

    def install(self, spec, prefix):
        options = ['--with-ssl=0',
                   '--with-x=0',
                   '--download-c2html=0',
                   '--download-sowing=0',
                   '--download-hwloc=0',
                   'COPTFLAGS=',
                   'FOPTFLAGS=',
                   'CXXOPTFLAGS=']
        options.extend(self.mpi_dependent_options())
        options.extend([
            '--with-precision=%s' % (
                'double' if '+double' in spec else 'single'),
            '--with-scalar-type=%s' % (
                'complex' if '+complex' in spec else 'real'),
            '--with-shared-libraries=%s' % ('1' if '+shared' in spec else '0'),
            '--with-debugging=%s' % ('1' if '+debug' in spec else '0'),
            '--with-64-bit-indices=%s' % ('1' if '+int64' in spec else '0')
        ])
        # Make sure we use exactly the same Blas/Lapack libraries
        # across the DAG. To that end list them explicitly
        lapack_blas = spec['lapack'].libs + spec['blas'].libs
        options.extend([
            '--with-blas-lapack-lib=%s' % lapack_blas.joined()
        ])

        # etc.

        # PETSc has its own way of doing parallel make.
        make('MAKE_NP=%s' % make_jobs, parallel=False)
        make("install")

        # solve Poisson equation in 2D to make sure nothing is broken:
        if ('mpi' in spec) and self.run_tests:
            with working_dir('src/ksp/ksp/examples/tutorials'):
                env['PETSC_DIR'] = self.prefix
                cc = Executable(spec['mpi'].mpicc)
                cc('ex50.c', '-I%s' % prefix.include, '-L%s' % prefix.lib,
                   '-lpetsc', '-lm', '-o', 'ex50')
                run = Executable(join_path(spec['mpi'].prefix.bin, 'mpirun'))
                if 'superlu-dist' in spec:
                    run('ex50',
                        '-da_grid_x', '4',
                        '-da_grid_y', '4',
                        '-pc_type', 'lu',
                        '-pc_factor_mat_solver_package', 'superlu_dist')

                if 'hypre' in spec:
                    run('ex50',
                        '-da_grid_x', '4',
                        '-da_grid_y', '4',
                        '-pc_type', 'hypre',
                        '-pc_hypre_type', 'boomeramg')

# etc...
```

the point being that enough people use spack that it has plenty of expert knowledge baked in: in particular, the petsc build script also comes with two patches for different versions of PETSc to support compilation with clang:
https://github.com/spack/spack/tree/develop/var/spack/repos/builtin/packages/petsc

**Comment by drwells** [comment]
Another advantage to this is that we can get rid of all of our bundled dependencies and let spack handle the versioning problems for us. For example: the bundled boost is not sufficient since it does not have `unordered_map.hpp`.

**Comment by knepley** [comment]
I automated the download and install of all the dependencies that you listed above today. Its in knepley/feature-configure-ibamr-packages. I am submitting the PR now.

**Comment by drwells** [comment]
I looked for this branch but I don't see it here or in your fork. Where is it? I'd like to give it a spin :)

**Comment by knepley** [comment]
https://bitbucket.org/petsc/petsc/branch/knepley/feature-configure-ibamr-packages

I was testing with

./configure --PETSC_ARCH=arch-master-ibamr-debug --download-muparser --download-silo --download-samrai --download-mpich --download-hdf5 --download-boost --boost-headers-only --download-libmesh --download-eigen

Thanks,

    Matt

**Comment by boyceg** [comment]
> https://bitbucket.org/petsc/petsc/branch/knepley/feature-configure-ibamr-packages <https://bitbucket.org/petsc/petsc/branch/knepley/feature-configure-ibamr-packages>
> I was testing with
> 
> ./configure --PETSC_ARCH=arch-master-ibamr-debug --download-muparser --download-silo --download-samrai --download-mpich --download-hdf5 --download-boost --boost-headers-only --download-libmesh --download-eigen
> 
> Thanks,
> 

(Matt is saying this implicitly, but notice that he is talking about a PETSc branch that is able to handle all of the third-party libraries.)

**Comment by drwells** [comment]
I am surprised that the PETSc guys (well, that does include @knepley) are willing to bundle our dependencies for us.

How soon will this version of PETSc be released?

**Comment by drwells** [comment]
Bundle is the wrong word; 'include build instructions' is more accurate.

**Comment by drwells** [comment]
For the sake of record: during my installation run with @masmath yesterday I used spack to intall everything but SAMRAI (it does not support 2.4.4) and things went fairly smoothly.

**Comment by ahmednislam** [comment]
> For the sake of record: during my installation run with @masmath yesterday I used spack to intall everything but SAMRAI (it does not support 2.4.4) and things went fairly smoothly.

I tried the whole process of using spack to install all the libraries as outlined in the "Building on Linux" page, so far everything went smooth,. But question is-->how to set the Debug and the Optimized Build for libraries like Samrai or PETSc. or llibMesh? And when ./configuring up the final IBAMR, where should the export PETSC_ARCH=linux-debug and export PETSC_DIR=<..> should point to?

**Comment by drwells** [comment]
@ahmednislam If you want to use spack then you should install debug libraries like, e.g.,
```
spack install samrai @2.4.4 +debug
```
I think SAMRAI, libMesh, and PETSc default to optimized builds.

At the end of installation spack will print out the installation prefix (including the hash). That is the value you need to provide to the IBAMR configuration script.

**Comment by ahmednislam** [comment]
> @ahmednislam If you want to use spack then you should install debug libraries like, e.g.,
> 
> ```
> spack install samrai @2.4.4 +debug
> ```
> I think SAMRAI, libMesh, and PETSc default to optimized builds.
> 
> At the end of installation spack will print out the installation prefix (including the hash). That is the value you need to provide to the IBAMR configuration script.

Ok, I will try that !!! Thank you !!

**Comment by drwells** [comment]
This is a complex project that definitely won't be ready for 0.8.0.

**Comment by drwells** [comment]
This is now done by https://github.com/IBAMR/autoibamr.
