### ISSUE TITLE
sign issue?

### ISSUE THREAD

**Issue by amneetb** [IBAMR/IBAMR#27]
Ref

https://github.com/IBAMR/IBAMR/blob/d097180162281c0980d266ae43ac2e5259dbad82/src/IB/IBFEMethod.cpp#L1333

This should be F += .... 

The reason being fluid should experience an opposite reaction. Force on the surface of solid is 
```
f_pressure_solid = -p *n * da
f_pressure_fluid = - f_pressure_solid
```
f_pressure_fluid should be spread on the Eulerian grid

**Comment by boyceg** [comment]
> On Aug 4, 2015, at 11:25 PM, Amneet Bhalla <notifications@github.com> wrote:
> 
> Ref
> 
> https://github.com/IBAMR/IBAMR/blob/d097180162281c0980d266ae43ac2e5259dbad82/src/IB/IBFEMethod.cpp#L1333 <https://github.com/IBAMR/IBAMR/blob/d097180162281c0980d266ae43ac2e5259dbad82/src/IB/IBFEMethod.cpp#L1333>
> This should be F += ....
> 
> The reason being fluid should experience an opposite reaction. Force on the surface of solid is
> 
> f_pressure_solid = -p *n * da
> f_pressure_fluid = - f_pressure_solid
> f_pressure_fluid should be spread on the Eulerian grid
> 
This is a loading pressure on the solid. I think the sign is correct. It is easy enough to test.
