### ISSUE TITLE
Document sign convention for surface pressure-like forces in IBFEMethod

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#28]

**Comment by amneetb** [comment]
https://github.com/IBAMR/IBAMR/blob/d097180162281c0980d266ae43ac2e5259dbad82/src/IB/IBFEMethod.cpp#L1341-#L1344

This should be F -= F_s (according to the convention defined for pressure), i.e., whatever F_s is on surface, fluid should experience a negative of it.

**Comment by boyceg** [comment]
I do not agree.

For pressure, we are saying: "this is a distribution of loads along the surface oriented in the normal direction to the surface". My mental picture here is that you are using these loads to "push" on the solid, and the convention in the code is that positive pressures indicate "pushing on the solid" and negative pressures indicate "pulling". I think this is a reasonable convention, but I am willing to be convinced otherwise.

For the surface force, we are saying: "this is a distribution of directional loads along the surface". It seems perverse for the code to reverse the orientations.

**Comment by boyceg** [comment]
Sign conventions are better documented in #168.
