### ISSUE TITLE
A_scale

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#285]
We should clarify in the VC class documentation that `A_scale` is set on a per-level basis.

Incidentally, it looks like the scale factor is set to be uniform in the tests. Is it sufficient to have only one scale factor for all levels?

**Comment by amneetb** [comment]
I can document that.

For air/water system A_scale does not do much. It for extreme ratios like 10^6 where you begin to see the effect. Most/All examples are air/water system, so even A_scale = 1 works.

**Comment by amneetb** [comment]
@boyceg : I have documented it. You can close this issue after reviewing it.

**Comment by boyceg** [comment]
Looks good.
