### ISSUE TITLE
ConstraintIB/flow_past_cylinder_HF gtest takes up too much memory

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#304]
Noted in #269: the memory consumption in this test grows to consume all the memory in my workstation.

**Comment by drwells** [comment]
The default settings for this example program also take up all available memory on the machine.

**Comment by drwells** [comment]
I assigned this to 1.0 in the fall, but lets try to fix it in time for 0.5 instead.

**Comment by amneetb** [comment]
You can remove this test altogether. You can also mark this example as "unsupported"

**Comment by drwells** [comment]
@amneetb Good point; we are going to get rid of the gtest tests soon anyway.

Do you think its worthwhile trying to fix the excessive memory usage in this example program?

**Comment by drwells** [comment]
For what its worth: I did a little bit of profiling and the default settings require more than 64 GB even though the number of coarse grid cells is reasonable (its capped at about 34 million). We run out of memory when we try to do the first fluid solve.

**Comment by drwells** [comment]
Unless there is a plan for fixing this example lets delete it for 0.6. I don't understand why the memory usage is blowing up.
