### ISSUE TITLE
Handling of the bundled dependencies

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#308]
We presently include several dependencies in our own tree (boost, eigen, muparser). These do make installation easier, but they won't be necessary once we have `easy_build.py` up and running which can download and install everything for us.

I think we could lessen our own maintenance burden (i.e., #267, #307, etc) by completely removing these since we will have a good alternative for easily installing dependencies. Thoughts?

**Comment by boyceg** [comment]
I think we would be crazy not to remove this stuff once we have a working alternative.

**Comment by drwells** [comment]
Unless someone objects strongly, then, lets not port #307 to `master` since we will just get rid of the set of directories in the near future anyway.

**Comment by drwells** [comment]
Lets hold off on making a decision here for now - we need to keep the bundled dependencies around as long as we support the autotools based build system (which may be a few more years).
