### ISSUE TITLE
BuildSystem support for setting the dimension at compile time

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#324]
`configure.new` needs either to take in a spatial dimension to compile (2 or 3), or a set of dimensions (e.g. to support both 2D and 3D builds). If we can support both dimensions in the same configuration, then that should be the default.

This choice also affects the SAMRAI libraries that we need to link to (at least in SAMRAI 2.4.4), and the particular FORTRAN kernels that IBAMR builds.

**Comment by drwells** [comment]
Superceded by #1020.
