### ISSUE TITLE
visibility in BuildSystem builds

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#325]
PETSc's visibility settings do not currently play nicely with IBAMR.

`configure.new` needs to be able to determine whether PETSc is configured `--with-visibility=0`, and emit an error if not.

`configure.new` also should default to using `--with-visibility=0`. Further, perhaps `--with-visibility` should not be something that users can set until it works `--with-visibility=1`.

**Comment by knepley** [comment]
Okay, I will fix this first. Let me know if this plan is alright:
1) I will make it impossible to use visibility from configure.new
2) I will check if PETSc was configured with visibility and error if so
I will do it by putting code in config/configure.py

**Comment by boyceg** [comment]
This sounds fine. We are ultimately going to be automatically building PETSc, so we can make sure that PETSc is configured in this way.

It would be good to get the visibility stuff working, but perhaps we can worry about that once BuildSystem is working.

**Comment by drwells** [comment]
Superceded by #1020.
