### ISSUE TITLE
about the spread function in FEDataManager class?

### ISSUE THREAD

**Issue by sharpgao** [IBAMR/IBAMR#338]
Line 578:
for (unsigned d = 0; d < NDIM; ++d)
    {
        TBOX_ASSERT(X_dof_map.variable_type(d) == X_fe_type);
        TBOX_ASSERT(F_dof_map.variable_order(d) == X_order);
    }
Is F_dof_map.variable_order(d) == X_order right?

**Comment by boyceg** [comment]
Yes this is a bug. I will fix it.
