### ISSUE TITLE
Clean up boost checks

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#348]
From #347: I realized here that we never actually use `m4/boost.m4` (we use `m4/boost_configure.m4`), i.e., modifying this file has no effect on `configure`. We should move the header checks into the proper `m4` file and delete `boost.m4` once we are done.

**Comment by boyceg** [comment]
```
$ grep BOOST_REQUIRE configure.ac 
BOOST_REQUIRE([1.57.0],[
$ grep BOOST_REQUIRE */*.m4
m4/boost.m4:# The first macro is BOOST_REQUIRE.  It will simply check if it's possible to
m4/boost.m4:# BOOST_REQUIRE([VERSION], [ACTION-IF-NOT-FOUND])
m4/boost.m4:AC_DEFUN_ONCE([BOOST_REQUIRE],
m4/boost.m4:])# BOOST_REQUIRE
m4/boost.m4:[AC_REQUIRE([BOOST_REQUIRE])dnl
m4/boost.m4:# (eg, >= 1.33) you *must* invoke BOOST_REQUIRE before this macro.
m4/boost.m4:[AC_REQUIRE([BOOST_REQUIRE])dnl
m4/configure_boost.m4:#BOOST_REQUIRE([1.57.0],[AC_MSG_WARN([could not find system Boost library, using bundled Boost library])])
```

**Comment by boyceg** [comment]
`BOOST_REQUIRE` is called from `configure.ac` and provided by `boost.m4`.

**Comment by drwells** [comment]
Also from #347: it looks like we just don't use the header checks, which is why regenerating `configure` after deleting one of them from `boost.m4` had no effect. We should make sure that the rest of the header checks are used.

**Comment by drwells** [comment]
Since the current set up works and we are going to deprecate the current build system this type of improvement is not a good use of time, so lets close this.
