### ISSUE TITLE
Remove GSL

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#353]
AFAICT we do not actually use GSL anywhere in IBAMR, so there is no need to treat it as a ~bundled~ optional package.

Edit: reword sentence ('bundled' is the wrong word)

**Comment by boyceg** [comment]
> AFAICT we do not actually use GSL anywhere in IBAMR, so there is no need to treat it as a bundled package.
> 
I believe that it is used in some of the examples.

**Comment by drwells** [comment]
You're right; its in the `eel` examples. My mistake!
