### ISSUE TITLE
static_cast<unsigned> instead of (unsigned)

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#359]
We should use `static_cast<T>` instead of `(T)` so that the casting semantics are clear. In particular, we do this with `(unsigned)`; see the discussion in #356.

**Comment by drwells** [comment]
We should do the same thing for the fundamental type conversion operators, e.g., write `static_cast<float>(x)` instead of `float(x)`.

**Comment by boyceg** [comment]
I think this is closed by #391.

**Comment by boyceg** [comment]
Now we can close this I think.
