### ISSUE TITLE
Trouble with CCLaplaceOperator

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#364]
I have spent the last few days learning how to use SAMRAI, mostly by working through the manual and some of the IBTK tutorials.

I have been trying to debug something and have been stuck: the `CCLaplace::apply` function does not seem to correctly fill in boundary data when we have more than two levels in the hierarchy. Here is the grid I generated:

![visit0000](https://user-images.githubusercontent.com/3917035/47188169-f21b3780-d304-11e8-9e05-ed99a0d2e21a.png)

detail:

![visit0001](https://user-images.githubusercontent.com/3917035/47188202-1f67e580-d305-11e8-9866-2cba442a064d.png)

Its not clear to me where things have gone wrong in this function. Does anyone have some hints as to where I should look?

**Comment by boyceg** [comment]
> I have spent the last few days learning how to use SAMRAI, mostly by working through the manual and some of the IBTK tutorials.
> I have been trying to debug something and have been stuck: the CCLaplace::apply function does not seem to correctly fill in boundary data when we have more than two levels in the hierarchy. Here is the grid I generated:
> 
>  <https://user-images.githubusercontent.com/3917035/47188169-f21b3780-d304-11e8-9e05-ed99a0d2e21a.png>
> detail:
> 
>  <https://user-images.githubusercontent.com/3917035/47188202-1f67e580-d305-11e8-9866-2cba442a064d.png>
> Its not clear to me where things have gone wrong in this function. Does anyone have some hints as to where I should look
> 

Is this using the CCLaplace example/tester?

Are you using physical boundary conditions or periodic boundary conditions? If this is with periodic boundary conditions, notice that this grid hierarchy is not properly nested, and so bad things will likely happen somewhere.

Does this only happen when the refined region goes all the way up to the boundary?

The thing that fills in ghost cells is HierarchyGhostCellInterpolation, but it doesn’t really do any of the work.

For periodic boundary conditions, HierarchyGhostCellInterpolation is just using SAMRAI’s coarsen and refine infrastructure directly. But, again, this is not a properly nested grid, and so all bets are off. (It would also explain why it works with two levels but not three.)

With physical boundaries, the thing that sets ghost cells at the physical boundary is the IBTK class CartCellRobinPhysBdryOp, which is really just a wrapper for some FORTRAN 77 code. ( Is there a clang-tidy modernize tool for FORTRAN? :-D )

I sure hope you are using periodic boundary conditions!

There is also a IBTK example/tester for the physical boundary filling routines, although IIRC it is not very sophisticated, but if this is a physical boundary issue, that could be a place to start.

**Comment by boyceg** [comment]
>> I have spent the last few days learning how to use SAMRAI, mostly by working through the manual and some of the IBTK tutorials.
>> I have been trying to debug something and have been stuck: the CCLaplace::apply function does not seem to correctly fill in boundary data when we have more than two levels in the hierarchy. Here is the grid I generated:
>> 
>>  <https://user-images.githubusercontent.com/3917035/47188169-f21b3780-d304-11e8-9e05-ed99a0d2e21a.png>
>> detail:
>> 
>>  <https://user-images.githubusercontent.com/3917035/47188202-1f67e580-d305-11e8-9866-2cba442a064d.png>
>> Its not clear to me where things have gone wrong in this function. Does anyone have some hints as to where I should look
>> 
> 
> Is this using the CCLaplace example/tester?
> 
> Are you using physical boundary conditions or periodic boundary conditions? If this is with periodic boundary conditions, notice that this grid hierarchy is not properly nested, and so bad things will likely happen somewhere.

The proper nesting condition just means that fine level L is completely contained within the next coarser level L-1, so that grid cells on level L never directly abut grid cells on levels <= L-2. The condition is relaxed at physical boundaries but not at periodic boundaries (which are not really boundaries at all). I would expect that there are places in SAMRAI and/or IBAMR where something bad will happen on grids that do not satisfy this condition.

If you tag cells for refinement and use SAMRAI’s grid generation algorithm, then the locally refined grids will automatically satisfy the proper nesting condition.

However, I do not know one way or the other if SAMRAI prevents the construction of locally refined grids that do not satisfy the proper nesting condition if you directly construct them using REFINE_BOXES.

> Does this only happen when the refined region goes all the way up to the boundary?
> 
> The thing that fills in ghost cells is HierarchyGhostCellInterpolation, but it doesn’t really do any of the work.
> 
> For periodic boundary conditions, HierarchyGhostCellInterpolation is just using SAMRAI’s coarsen and refine infrastructure directly. But, again, this is not a properly nested grid, and so all bets are off. (It would also explain why it works with two levels but not three.)
> 
> With physical boundaries, the thing that sets ghost cells at the physical boundary is the IBTK class CartCellRobinPhysBdryOp, which is really just a wrapper for some FORTRAN 77 code. ( Is there a clang-tidy modernize tool for FORTRAN? :-D )
> 
> I sure hope you are using periodic boundary conditions!
> 
> There is also a IBTK example/tester for the physical boundary filling routines, although IIRC it is not very sophisticated, but if this is a physical boundary issue, that could be a place to start.

**Comment by drwells** [comment]
This is with the CCLaplace example. I added a lot of explanatory documentation while I was figuring things out; I'll put up a PR when I am done.

I bet its the periodic boundary since the grids are not properly nested there. I'll check in the morning.

**Comment by drwells** [comment]
To answer the other question: I don't know of any modernization tools for FORTRAN 77: I don't know of anything we should change besides writing `IMPLICIT NONE` everywhere.
