### ISSUE TITLE
Overhaul the test suite

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#372]
I had a nice chat with @knepley earlier today and this is something we discussed. We presently have a couple dozen (roughly) tests that check norms to verify that the code works. These tests rely on the gtest framework. I personally run the test suite frequently and use it to check my own work; even this small test suite is extremely valuable. However, this framework has several shortcomings:
1. We don't have a dedicated test runner program: `make -j32 --keep-going --ignore-errors --output-sync` works but is a bit crude (it cannot display output until it finishes). Tests that fail to compile or fail to execute (i.e., experience an exception or system error like a segfault) don't fail; they just don't print `OK` at the end. The previous make command cannot capture this since we have to ignore *all* errors or *no* errors with make. More succinctly: something else should invoke make on each test and record what happens instead of running it recursively.
2. We do not have a way to write unit tests: everything is presently based around compiling the examples in a certain way. It would be nice to check things like the new MPI class in a simple, isolated context (we don't need to run it inside the Eulerian solver to check the max function).
3. We cannot check things that are not easily expressed without assertions: i.e., we cannot verify graphical output.
4. All results must be expressed in the input file itself, which is inflexible.

A comparison: deal.II has a dedicated `tests/` directory containing about 5,000 distinct tests. One can run any subset (specified with a regular expression) via ctest. We use numdiff to verify output with some rounding tolerance. Importantly, ctest is aware of the build system (it is managed by cmake) and can track dependencies of tests to recompile and relink as needed. Additionally, we can run the same test executable with multiple configurations, which is very handy (example: one test can be run several times, each with a different number of MPI processes, to verify that some parallel algorithms).

I propose that we package up the current tests as-is and move them over to a dedicated `tests/` directory to start. We can continue using `make gtest` for the time being as we migrate to something more sophisticated. How does this sound?

**Comment by boyceg** [comment]
Sounds good to me.

@knepley, is it possible to leverage PETSc's new test harness? We started using the Google test framework before PETSc's testing framework was finished.

**Comment by knepley** [comment]
It may be possible. All the SLEPc tests have moved over to it. It a fairly open system (see chapter in the PETSc manual) and produces output in an open standard, so you can use a variety of free tools to look at the report. Its really just a collection of scripts which setup each test, run it, tear it down, and report the result. The advantage is that it is designed to run parallel tests, to run without breaking, and to integrate with the configure system to allow easy specification of what is allowed to run.

**Comment by knepley** [comment]
Luckily, I think supporting both is possible. Autotools uses #defines, just like PETSc, to indicate most of the conditions.

**Comment by boyceg** [comment]
I think I am about 85% of the way towards getting both autotools and BuildSystem coexisting. In the BuildSystem branch, both will compile the library. The main thing that remains is to make it easy for external apps to use either type of build.

I also think that it is OK for the testing framework to be specialized to one.
