### ISSUE TITLE
Replace std::ostringstream with std::to_string

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#388]
This is another easy task to fix that I have seen a lot: there are lots of places where we write, e.g.,

```cpp
std::ostringstream bc_coefs_name_stream;
bc_coefs_name_stream << "u_bc_coefs_" << d;
const std::string bc_coefs_name = bc_coefs_name_stream.str();
```
when, with C++11, we could simply write
```cpp
const std::string bc_coefs_name = "u_bc_coefs_" + std::to_string(d);
```

**Comment by boyceg** [comment]
@roberthunt4 this could be a good one for you.

**Comment by drwells** [comment]
Lets give this to @jabrown893 to give him some practice for #444.
