### ISSUE TITLE
Replace update_and_sync with System::update?

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#395]
I was reading through some documentation for `libMesh::System` when I noticed the function `virtual void libMesh::System::update()`, which is described as 'Update the local values to reflect the solution on neighboring processors.' It might make life easier to rely on libMesh (i.e., this function in particular) to update ghost data.

**Comment by boyceg** [comment]
I think for now we should continue to do this ourselves --- and, in particular, directly use `VecGhostUpdateBegin`/`VecGhostUpdateEnd` where appropriate.
