### ISSUE TITLE
add definitions for common MPI types

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#407]
I have, while working on #396, used the wrong MPI types more than once since I have hacky methods of figuring out the MPI type corresponding to a libMesh type, e.g.,

```cpp
        MPI_Datatype integral_type = 0;
        switch (sizeof(processor_id_type))
        {
        case 1:
            integral_type = MPI_UNSIGNED_CHAR;
            break;
        case 2:
            integral_type = MPI_UNSIGNED_SHORT;
            break;
        case 4:
            integral_type = MPI_UNSIGNED;
            break;
        case 8:
            integral_type = MPI_UNSIGNED_LONG;
            break;
        }
```

We should add a header that figures this stuff out for us to prevent these bugs.

**Comment by drwells** [comment]
This has come up only once or twice so far, deep in the guts of IBAMR. Its not that important. Lets close it for now.

**Comment by boyceg** [comment]
I was actually thinking the _opposite_ recently when reviewing some of the partitioning PRs!! ;-)

But, this is OK with me.
