### ISSUE TITLE
Improve C++11/C++14 detection

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#411]
I just ran into an issue with selecting the correct version flag and libMesh: since newer versions of g++ default to `-std=gnu++14` it is possible, without user intervention, that libMesh gets compiled with C++14 support. The problem with this is we strictly enforce, at the moment, the flag `-std=c++11`.

We should try to detect if libMesh was compiled with C++14 support: if so, and if the compiler supports it, we should use `-std=c++14` too.

**Comment by boyceg** [comment]
Hmmmmmmmmm — this will also affect SAMRAI configuration.

**Comment by drwells** [comment]
I don't think SAMRAI 3.12.0 tries to use anything newer than C++11; does it?

**Comment by boyceg** [comment]
Does it cause any problems if SAMRAI is configured to use C++11 and libMesh/IBAMR are configured to use GNU's C++14 extensions, as long as everything is using the same compiler?
