### ISSUE TITLE
IBStandardInitializer should fail when file exists but not readable

### ISSUE THREAD

**Issue by abarret** [IBAMR/IBAMR#413]
`IBStandardInitializer` quietly ignores files that can't be opened. It should either quit or at least emit a helpful warning message.

C++ seems to be ill equipped to deal with this. As @drwells pointed out, we can either use C++17's file system library (which requires C++17), boost's version of the file system library (which requires a compiled boost build), or stat (which is non-standard). None of these options are ideal, but stat seems to be the least intrusive option. We could also just leave this as a "feature" of IBAMR. @boyceg, do you have any opinions?

**Comment by boyceg** [comment]
How about we do the error checking if configure can find a working stat? This would be a good feature to put into a macro that is only active if stat works.

**Comment by boyceg** [comment]
> On Dec 13, 2018, at 3:58 PM, Boyce Griffith <boyceg@gmail.com> wrote:
> 
> How about we do the error checking if configure can find a working stat? This would be a good feature to put into a macro that is only active if stat works.

Or it could default to C++17 if available...?

**Comment by drwells** [comment]
We are already tied to UNIX; I don't think any platform we can use does not have `stat` :wink: 

I think we should just do a feature check in `configure` for stat and define `IBAMR_HAVE_STAT` if it works. Then we can write

```cpp
void file_exists(const std::string &file_name)
{
#if IBAMR_HAVE_STAT
    stat(file_name.c_str()); // not how stat works but you get the point
#else
    // ???
#endif
}
```
