### ISSUE TITLE
Configuring error in IBAMR

### ISSUE THREAD

**Issue by Vidhumkl** [IBAMR/IBAMR#427]
I am trying to install IBAMR on ubuntu 18.04 with following third party libraries
1. boost 1.60.0
2. Eigen 3.3
3.HDF51.8.16
4. silo 4.10.
5. muParser, MPI & Hypre -installed by Petsc
6. PetSc 3.10.3
7.Samrai 2.4.4
8.Libmesh 1.2.1
And while configuring IBAMR with code
"
cd $HOME/sfw
mkdir ibamr
cd ibamr
git clone https://github.com/IBAMR/IBAMR.git
cd $HOME/sfw/ibamr
mkdir ibamr-objs-dbg
cd ibamr-objs-dbg

export BOOST_ROOT=$HOME/sfw/linux/boost/1.6.0
export PETSC_ARCH=linux-debug
export PETSC_DIR=$HOME/sfw/petsc/3.10.3
../IBAMR/configure \
  CFLAGS="-g -O1 -Wall" \
CXXFLAGS=-std=c++11 \
   FCFLAGS="-g -O1 -Wall" \
   --with-hypre=$PETSC_DIR/$PETSC_ARCH \
  --with-samrai=$HOME/sfw/samrai/2.4.4/linux-g++-debug \
  --with-hdf5=$HOME/sfw/linux/hdf5/1.8.16 \
  --with-silo=$HOME/sfw/linux/silo/4.10 \
  --with-boost=$HOME/sfw/linux/boost/1.6.0 \
  --enable-libmesh \
--with-libmesh=$HOME/sfw/linux/libmesh/1.3.1/1.3.1-debug/ \
  --with-libmesh-method=db   "

Gives configuration error

"
====================================
Configuring optional package libMesh
====================================
checking libmesh/libmesh.h usability... no
checking libmesh/libmesh.h presence... no
checking for libmesh/libmesh.h... no
configure: error: libMesh enabled but could not find working libmesh.h
"

Pls help me on it...

**Comment by boyceg** [comment]
It looks like you may need to use “--with-libmesh-method=dbg” instead of “--with-libmesh-method=db”. Make sure that you have build libMesh with the “dbg” method enabled.

**Comment by Vidhumkl** [comment]
yes. I have used "dbg " only. it is a typographical error on composing
message..

**Comment by drwells** [comment]
Would you please attach the complete `config.log`? That would help determine what is going on.

**Comment by Vidhumkl** [comment]
[config.log](https://github.com/IBAMR/IBAMR/files/2758299/config.log)
Pls find the attached file...

**Comment by drwells** [comment]
It looks like configuration is failing here:

```
configure:23950: g++ -c  -std=gnu++11 -I/home/vidhu/sfw/linux/libmesh/1.3.1/1.3.1-debug/include -I/home/vidhu/sfw/linux/boost/1.6.0/include   conftest.cpp >&5
In file included from /home/vidhu/sfw/linux/libmesh/1.3.1/1.3.1-debug/include/libmesh/libmesh.h:25:0,
                 from conftest.cpp:66:
/home/vidhu/sfw/linux/libmesh/1.3.1/1.3.1-debug/include/libmesh/libmesh_common.h:53:11: fatal error: mpi.h: No such file or directory
```

The best way to fix this is to use the provided MPI compiler wrappers: e.g., before running configure, use
```
export CC=mpicc
export CXX=mpicxx
export FC=mpifort
export F77=mpifort
```
(your version of MPI may give things slightly different names; those are the openmpi compiler wrapper names)

or, alternatively, provide `CC`, `CXX`, `FC`, and `F77` as arguments to configure.

**Comment by Vidhumkl** [comment]
thank you for help. I was down with fever for few days. I am able to build and make ibamr. but while making examples following error came:
collect2: error: ld returned 1 exit status
Makefile:558: recipe for target 'main2d' failed
make: *** [main2d] Error 1

Please help me on this..

**Comment by boyceg** [comment]
Can you send the full error message?

**Comment by Vidhumkl** [comment]
Pls find the attached file
[build error_examples.txt](https://github.com/IBAMR/IBAMR/files/2781327/build.error_examples.txt)

**Comment by boyceg** [comment]
These errors suggest that you compiled SAMRAI and IBAMR with different MPI compiler wrappers.

All libraries that use MPI (PETSc, SAMRAI, libMesh, and IBAMR) need to use the same version of MPI. The easiest way to ensure this is to use the same MPI compiler wrappers (mpicc/mpicxx/mpifort) when building each of these libraries. There is no harm in specifying these as the C, C++, and Fortran compilers when building these libraries.

**Comment by Vidhumkl** [comment]
> These errors suggest that you compiled SAMRAI and IBAMR with different MPI compiler wrappers. All libraries that use MPI (PETSc, SAMRAI, libMesh, and IBAMR) need to use the same version of MPI. The easiest way to ensure this is to use the same MPI compiler wrappers (mpicc/mpicxx/mpifort) when building each of these libraries. There is no harm in specifying these as the C, C++, and Fortran compilers when building these libraries.

thank you will try to complie

**Comment by Vidhumkl** [comment]
I re- built PETSc, SAMRAI and Libmesh with same complier wrappers 
export CC=mpicc
export CXX=mpicxx
export FC=mpifort
export F77=mpifort
But the error resulted the same. Help me on this. Attaching entire make example log.....
[build error_examples.txt](https://github.com/IBAMR/IBAMR/files/2799382/build.error_examples.txt)

**Comment by drwells** [comment]
Most of the errors look like
```
SAMRAI-2.4.4/source/toolbox/parallel/Schedule.C:264: undefined reference to `ompi_mpi_int'
``` 
I am not sure how to fix this, but this is not a problem with IBAMR: it looks like the final program is not linked with the same MPI library as SAMRAI expects. My best guess is that you have compiled SAMRAI with one MPI version and IBAMR with a different IBAMR version, but I don't know for sure what has happened.

**Comment by Vidhumkl** [comment]
Thank you for the help.
I tried using open mpi and it worked. There is a new error came while making optimised build.
posting the error and the entire log.

Makefile:4684: recipe for target '../src/lagrangian/libIBTK2d_a-FEDataInterpolation.o' failed
make[2]: *** [../src/lagrangian/libIBTK2d_a-FEDataInterpolation.o] Error 1
make[2]: Leaving directory '/home/vidhu/sfw/ibamr/ibamr-objs-opt/ibtk/lib'
Makefile:614: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/vidhu/sfw/ibamr/ibamr-objs-opt/ibtk'
Makefile:610: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
[build error_opt_make.txt](https://github.com/IBAMR/IBAMR/files/2838474/build.error_opt_make.txt)
Please help me on it....

**Comment by boyceg** [comment]
This looks like an error related to libMesh and IBAMR using different C++ flags. @drwells, didn't you push something related to this recently?

**Comment by drwells** [comment]
Sorry for the slow response; I missed the latest update to this thread.

@Vidhumkl libMesh will compile itself with C++14 support if it detects that it is available: this is a known problem with certain GCC release on the master branch. I believe the best fix is to simply compile IBAMR with
```
./configure CXXFLAGS="-std=c++14" [...]
```
where `[...]` stands for the rest of the arguments provided to the configuration script.

**Comment by Vidhumkl** [comment]
> This looks like an error related to libMesh and IBAMR using different C++ flags. @drwells, didn't you push something related to this recently?

Thank you for the reply.. When I searched based on error it showed that function is a C++14 version. So I configured with  g14 version and worked fine.

**Comment by Vidhumkl** [comment]
> Sorry for the slow response; I missed the latest update to this thread.
> 
> @Vidhumkl libMesh will compile itself with C++14 support if it detects that it is available: this is a known problem with certain GCC release on the master branch. I believe the best fix is to simply compile IBAMR with
> 
> ```
> ./configure CXXFLAGS="-std=c++14" [...]
> ```
> 
> where `[...]` stands for the rest of the arguments provided to the configuration script.

Thank you for the help. I also got similar input from the search of the error. I configured and made the IBAMR successfully yesterday.... Thank you once again....

**Comment by drwells** [comment]
I'm glad it worked!
