### ISSUE TITLE
Closing vectors in FEDataManager::computeL2Projection

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#429]
We are spending a surprising (about 20% on some processors) amount of time in `libMesh::PetcVector::close` inside the L2 projection. We should look into getting rid of these calls to `close` if possible.

**Comment by boyceg** [comment]
Is this real time spent, or is it load imbalance at synchronization points?

**Comment by drwells** [comment]
I think both: all processes spend between 10-20% of their overall run time in that function. The processors with better workloads (that spend a relatively small amount of time, overall, polling) still spend 10% of their time calling close. The other 10% seems to be from a load imbalance (those processors spend a lot more time polling in other places too).

**Comment by drwells** [comment]
(these numbers are from profiling afterload test 10 with 16 processors, by the way)

**Comment by drwells** [comment]
Yup.

**Comment by boyceg** [comment]
Take a look at #430.

**Comment by boyceg** [comment]
I think this is addressed by #430.

**Comment by drwells** [comment]
Yup. We also have to wait for all processors to finish interpolating velocity, which is the main reason we get stuck here a lot.
