### ISSUE TITLE
More Eigen fixes

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#434]
While writing #428 I missed adding fixes for the Eigen aliases defined in `ibtk_utilities.h`: e.g., `IBTK::Point`, `IBTK::Vector`, etc.

I thought about this some more and I think trying to constantly fix these is a losing battle: any time we add these as member variables we are asking for trouble, since allocating such an object on the heap may cause segmentation faults on reads. Furthermore: enabling vectorization with these objects is not helpful (I suspect vectorization has the potential to help a lot in the IB kernels, but thats a project for later) since we don't have any huge bottle necks with computing centers of mass, rotations, etc.

I think the best fix would be to implement our own `IBTK::Point` and `IBTK::Vector` (which would be identical: `Point` should probably inherit from `Vector`).

Thoughts?

**Comment by boyceg** [comment]
It's OK with me.

Could/should we just re-use the libMesh objects and make libMesh a non-optional dependency?

**Comment by drwells** [comment]
I would prefer to roll our own so that we can implement conversion constructors/operators to and from Eigen objects and libMesh objects, or anything else we need.

**Comment by boyceg** [comment]
OK with me.

**Comment by drwells** [comment]
The Eigen thing is annoying but the compiler catches whenever we try to use things with alignment requirements - its obvious when we mess up. Eigen also has the advantage that it is a complete tensor implementation and has support for quaternions. Hence, since the first issue hasn't really bitten us again over the last year and rolling our own IBTK replacement would require duplicating a bunch of work, there is not enough benefit to make this issue worthwhile.
