### ISSUE TITLE
Running bootstrap updates configuration on master

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#438]
Running the updated `bootstrap` script (see #426) still changes things on master. Should we rerun this script on `master` and push the result? Is this deliberate?

@abarret *ping*

**Comment by abarret** [comment]
Hmmm... It looks like most of the changes are in `ibtk/contrib/muparser` or `ibtk/config` and they seem to be mostly benign (or at least to my untrained eye they do). My guess is that whenever we initially started switching to the newer version of automake we never included these updated config files. I'll create a pull request.

**Comment by drwells** [comment]
Fixed by #451.
