### ISSUE TITLE
the call to setToScalar() in FEDataManager::spread() takes up a surprising fraction of runtime

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#469]
The relevant line is [here](https://github.com/IBAMR/IBAMR/blob/3773d45358d6a2f8ae566d0631e800a3e9151d20/ibtk/src/lagrangian/FEDataManager.cpp#L591).

I tried replacing this with code that uses `std::fill(f_data_pointer_begin, f_data_pointer_end, 0.0)`, which on my Mac was turned into an optimized routine to zero out memory, and it made only a small difference in runtime.

I _think_ that what is going on is that it is slow to zero out the newly allocated array. Perhaps we should cache temporary arrays?

**Comment by drwells** [comment]
If I recall correctly this was fixed by #538.
