### ISSUE TITLE
apparent parallel libMesh periodic BC issue

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#476]
It seems like there is a longstanding bug in handling periodic boundary conditions with `examples/IBFE/explicit/ex1` in parallel. I can reproduce this on a number of different points in the history by setting
```
   largest_patch_size {
      level_0 = N/2,  N  // all finer levels will use same values as level_0
   }
   smallest_patch_size {
      level_0 = N/2,  N  // all finer levels will use same values as level_0
   }
```
and running on four processors. There will be a clear aberration in the x-component of the velocity field at the location where the periodic boundaries of the structure meet.

**Comment by boyceg** [comment]
(This seems likely to be an error in the way that I am setting up the periodic boundary condition specification.)

**Comment by cpuelz** [comment]
any luck with this?

**Comment by boyceg** [comment]
Looks like this needs someone to be assigned to fix it! :-) @cpuelz? :-)
