### ISSUE TITLE
Explicitly partition libMesh data into interaction and non-interaction parts

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#492]
I have been doing some more profiling with callgrind (I recently learned how to use callgrind with MPI, which gives a complete picture of where the process spends it time). It looks like as we scale up to larger processor counts (e.g., 24 with the heart model) we are spending a lot of time exchanging data when interpolating the velocity. A large contributor to this imbalance is the amount of time PETSc spends sorting indices (which, IIRC, is only necessary when we add new entries into a vector that were assumed zero at construction time).

Ultimately, I believe that this is a result of the fact that we do assembly of libMesh vectors in two different ways: we do things in the 'normal' way (where we loop over the cells owned by the current processor) and we do things at interaction points (where we loop over the cells that have support on the locally owned patches). In the later case one cell may have support on multiple patches, so these are, in general, not equal (the interaction set should be a super set of the normal one). I need to do some more experiments to see what the difference is, in practice, between these, but since these sets are not the same we have to insert a lot of data into PETSc vectors corresponding to rows of the linear system that are not locally owned since these sets of dofs are not equal: hence the large amount of communication.

I think that the right way to do this is to set up our own PETSc vectors (plain `Vec`s) with the correct set of dofs for doing interaction (i.e., all dofs on cells that intersect the locally owned patches) as well as our own PETSc `VecScatter` objects which know how to accumulate the interaction vectors into the libMesh system RHS vectors. I think that if we explicitly tell PETSc what to expect we can really improve performance here.

**Comment by drwells** [comment]
A few numbers, from my experiments so far:
1. with 6 processors we spent 29% of our cycles in `interpolateVelocity` and 15% of total cycles in vector assembly.
2. with 12 processors we spent 30% of our cycles in `interpolateVelocity` and 20% of total cycles in vector assembly.
3. with 24 processors we spent 24% of our cycles in `interpolateVelocity`: and 17% of total cycles in vector assembly.

That's 50%, 66%, and 71% of our time in that function being spent on communication. For comparison with a more usual workflow:
1. with 6 processors we spent 13% of our cycles in `computeLagrangianForce` and 0.2% of total cycles in vector assembly.
2. with 12 processors we spent 8% of our cycles in `computeLagrangianForce` and 0.25% of total cycles in vector assembly.
3. with 24 processors we spent 5% of our cycles in `computeLagrangianForce` and 0.21% of total cycles in vector assembly.

This is a stark difference: the sets of elements are nearly the same and we do the same type of operation, but the communication in the former case is 100x as expensive.

I am running much longer experiments with callgrind now (these will take several days to finish): these percentages are a bit inaccurate since I only did 25 time steps (and we spend something like 20% of total time setting stuff up).

**Comment by drwells** [comment]
This would be an excellent project for anyone who wants to do a deep dive into parallel computing :)

**Comment by boyceg** [comment]
I think that the ghosted `Vec`s with the appropriate local entries are already available.

I had a branch, which I apparently have deleted, where I inserted everything into the local form of the ghosted `Vec` and then assembled using `VecGhostUpdateBegin`/`VecGhostUpdateEnd`. If we do that, would it avoid this sorting stuff?

**Comment by drwells** [comment]
I think we have `X` vectors ghosted in the right way somewhere. I'll take a look.

> I had a branch, which I apparently have deleted, where I inserted everything into the local form of the ghosted `Vec` and then assembled using `VecGhostUpdateBegin`/`VecGhostUpdateEnd`. If we do that, would it avoid this sorting stuff?

I think that will work (again, as long as we set up the vectors with the correct ghost regions). Here is what PETSc says:

> To accumulate the ghost region values onto the owning processors and then update the ghost regions correctly, call the later followed by the former, i.e.,
> ```cpp
>       VecGhostUpdateBegin(v,ADD_VALUES,SCATTER_REVERSE);
>       VecGhostUpdateEnd(v,ADD_VALUES,SCATTER_REVERSE);
>       VecGhostUpdateBegin(v,INSERT_VALUES,SCATTER_FORWARD);
>       VecGhostUpdateEnd(v,INSERT_VALUES,SCATTER_FORWARD);
>```
though since we never need to actually read ghost data on the RHS vectors I think we can skip the second two calls.

**Comment by boyceg** [comment]
Everything is ghosted in the right way, otherwise things would break in parallel. :-) We just haven't explicitly used the ghosted representation.

**Comment by drwells** [comment]
> Everything is ghosted in the right way

The vectors we read from to do the IB stuff are (they have to be, as you said) but I don't think the RHS vectors are, which is the source of our trouble. Is this correct?

**Comment by drwells** [comment]
I can confirm that the RHS vectors are not ghosted in this way. I think the right way forward is to set up something like `d_U_rhs_IB_ghost_vecs`, assemble into that, and then copy the local part over to `d_U_rhs_vecs`.

**Comment by boyceg** [comment]
IIRC there are performance differences when using ghosted/unghosted RHS vectors, so this sounds like the right approach.

**Comment by drwells** [comment]
Sounds good.

**Comment by drwells** [comment]
I believe the assembly timings above show that, as long as we use `batch_vec_assemble` and friends, the penalty for using multiple parts is acceptably small: the amount of time we spend assembling in `computeLagrangianForce` is very small, and so is the amount of time we spend in the linear solver (the percentages vary, but the L2 solve only takes about 1/10th the number of cycles that setting up the RHS takes).

Since these are the two main functions that involve loops over the number of parts I have to conclude that having multiple parts doesn't make the linear solves unacceptably expensive.

**Comment by drwells** [comment]
I have made some progress on this. In case people are interested:
1. Setting up IB-ghosted RHS doesn't seem to help. Oddly (this may be a bug) only the first processor seems to own any ghost cells.
2. Caching IB-ghosted vectors doesn't help either.
3. The code for computing what dofs correspond to local assembly is reasonable.

**Comment by drwells** [comment]
I am not sure whether there is something wrong with my code that calculates and prints it, or something wrong with how we set this up. I am looking into it.

**Comment by drwells** [comment]
Yup: I moved the vector of IB dofs before creating the ghosted vector.

A few things to note:
1. In the heart model many processors have more IB ghost dofs than actual dofs. This is very surprising to me, since the IB ghost dofs should be, when we use the SAMRAI partitioner, the dofs on elements that intersect the ghost region of the locally owned patches. What is even more surprising is that using the new SAMRAI box partitioning scheme doesn't help a lot here, which makes no sense at all to me.
2. I don't understand what `FEDataManager::collectActivePatchElements` actually computes: if we want to find all of the elements that have support on a given patch then it should be enough that the bounding box of the element intersects the bounding box of the patch, but we compute a ton of other stuff here after checking bounding boxes.
3. `FEDataManager::collectGhostDOFIndices` does, AFAICT, exactly what it should be doing.
4. AFAICT `VecSetOption(vec, VEC_SUBSET_OFF_PROC_ENTRIES, PETSC_TRUE)`, i.e., assuming that the communication pattern never changes, is the 'right' way to fix this problem. However: I am getting two different MPI problems when this is enabled: I have noticed that some processors don't seem to set this flag, which results in a deadlock, and (on different runs) we get stuck in `VecAssemblyBegin` forever. The former seems like a bug in libMesh or PETSc; I'd argue that the later is a bug in PETSc. Its also possible that I am doing something dumb, but I can only reproduce this problem in the heart model (not by usual ex4 whipping boy).

I am going to keep trying to convince PETSc to preserve the communication problem: right now we spend roughly 60-70% of our time in `VecAssemblyBegin` (when assembling IB-ghosted vectors) rebuilding the communication pattern, which is an all-to-all operation.

**Comment by knepley** [comment]
4) Do you always use the same INSERT_MODE?  Its required for that option. The code is extremely simple for setting options, so I do not think there is a bug there. Are you positive you are calling it collectively? We do not check. For the latter problem, can you get stack traces when you get stuck?

**Comment by drwells** [comment]
@knepley it gets stuck in the following stack:
PMPI_Iprobe and PMPI_Test
PetscCommBuildTwoSidedFReq_Ibarrier
PetscCommBuildTwoSidedFReq
VecAssemblyBegin_MPI_BTS
VecAssemblyBegin

on the *second* call to `VecAssemblyBegin`: the first one works correctly.

I don't think that we ever do anything but `VecSet(... ADD_VALUES)` so it should not be confused on insert modes. There are no checks for rank where I set the option either.

**Comment by knepley** [comment]
That is the scalable consensus algorithm. However, some MPI impls are buggy with this. You can try -vec_assembly_legacy to use Alltoall instead and see if it still hangs.

**Comment by boyceg** [comment]
> A few things to note:
> 
> In the heart model many processors have more IB ghost dofs than actual dofs. This is very surprising to me, since the IB ghost dofs should be, when we use the SAMRAI partitioner, the dofs on elements that intersect the ghost region of the locally owned patches. What is even more surprising is that using the new SAMRAI box partitioning scheme doesn't help a lot here, which makes no sense at all to me.
Are you sure that you are using the new partitioner?

Also, some of the structures have a relatively small spatial extent. For those, it is easy to believe that you wind up with more ghost DOFs than local DOFs.
> I don't understand what FEDataManager::collectActivePatchElements actually computes: if we want to find all of the elements that have support on a given patch then it should be enough that the bounding box of the element intersects the bounding box of the patch, but we compute a ton of other stuff here after checking bounding boxes.
What this is meant to do is to associate with every SAMRAI patch p the active libMesh elems that intersect p in their current (deformed) configuration.

There are two phases to the computation.

First, we build an approximate bounding box around every element e and look for intersections between the bounding boxes and the SAMRAI patches. These are approximately bounding boxes because they are constructed by looking at the nodal coordinates. For linear elements, this is fine. For higher order elements with curved boundaries, we may not actually have a bounding box, because the interpolation is not necessarily bounded by the extents of the nodes.

To get any elements that we may have missed because of their curved boundaries, the second phase uses a growing region algorithm to fill in any missing elements. This is an iterative process. It maintains a set of elements that is being considered; these are elements that have been identified as overlapping with the current patch. In each iteration, we ask whether the current set of elements has neighboring elements that we have not yet considered. Any newly discovered neighboring elements that overlap with the patch are added to the set of elements to consider in the next pass. Once the set of elements to be considered is empty, the process ends.

Does this process make sense? If I had written a proper bounding box code that works with higher-order elements, then phase two could be skipped. You still would probably want to do a two-phase computation: 1) use proper bounding boxes to identify potentially overlapping elements and 2) evaluate quadrature points on the elements to see if an element actually overlaps.

I think that it may be better to store this information directly in the Cartesian grid patches using an IndexVariable, as we also have discussed using for setting the partitioning. The idea would be to maintain index sets in each SAMRAI grid cell a list of the elements that touch that grid cell in their current configuration.
> FEDataManager::collectGhostDOFIndices does, AFAICT, exactly what it should be doing.
> AFAICT VecSetOption(vec, VEC_SUBSET_OFF_PROC_ENTRIES, PETSC_TRUE), i.e., assuming that the communication pattern never changes, is the 'right' way to fix this problem. However: I am getting two different MPI problems when this is enabled: I have noticed that some processors don't seem to set this flag, which results in a deadlock, and (on different runs) we get stuck in VecAssemblyBegin forever. The former seems like a bug in libMesh or PETSc; I'd argue that the later is a bug in PETSc. Its also possible that I am doing something dumb, but I can only reproduce this problem in the heart model (not by usual ex4 whipping boy).
Does it have something to do with having multiple parts in the heart model? It might be good to have a version of ex4 that has multiple structures.

**Comment by drwells** [comment]
@boyceg thanks a lot for writing all of that; the later algorithm makes sense when we have isoparametric mappings. I am pretty sure that this uses the new partitioning code (I get different answers when I turn it off) but I'll check.

I think the deadlocks might be outside our ability to fix.

@knepley setting `-vec_assembly_legacy` fixes the deadlock (I am grateful that you knew that trick). If you don't mind, I have another PETSc question: the current case involves doing a lot of assembly on cells that are not locally owned. Is there any documentation on how to set up `VecStash` in a way that makes it aware of what we need to do? The description for `VecStashSetInitialSize` helps but any extra information would be beneficial.

**Comment by boyceg** [comment]
I think we are on the same page here, but it is worth emphasizing that even if the elements have straight edges in the reference configuration, they may have curved elements in the current configuration if we are using P2 or Q2 elements.

**Comment by knepley** [comment]
I don't know of anything else you can tell the Stash to speed it up. It is just recording all the off-process entries, so knowing the size makes it really fast. It does pack them up at the end, which might take some time, but I do not know of an optimization for that. You can do VecAssemblyBegin/End(v, VEC_ASSEMBLY_FLUSH) to empty the stash in the middle. This could be used to overlap assembly of some ghost cells while you send already assembled ones.

**Comment by drwells** [comment]
@knepley I generated another interesting backtrace when using `VEC_SUBSET_OFF_PROC_ENTRIES`:
```
[6]PETSC ERROR: Petsc has generated inconsistent data
[6]PETSC ERROR: Received vector entry 2 out of local range [82098,85635)]
```
This is in `VecAssemblyEnd_MPI_BTS`. The problem goes away when I use `vec_assembly_legacy`. I thought the communication pattern should be independent of the assembly algorithm, but this doesn't seem to be the case.

**Comment by jedbrown** [comment]
`VEC_SUBSET_OFF_PROC_ENTRIES` is a pledge that the off-process entries in the assembly will always be a subset of those that existed in the first assembly. It allows reuse of some communication patterns. If you're sure this is the case, can you make a minimal test case? (I can build IBAMR to reproduce if needed, but try to make it as small as possible to help me debug.)

**Comment by drwells** [comment]
We (mostly me) are abusing libMesh pretty badly to do a lot of assembly into entries that are not locally owned so its definitely possible that I am doing something wrong. I will write up a test case if I can convince myself that the problem might be outside IBAMR.

**Comment by drwells** [comment]
@jedbrown I came up with a test case independent of IBAMR that demonstrates what I believe is the same issue: I get a different error message on my workstation and this example hangs on my laptop when we save the communication pattern (things work as expected when we do not).

I left a lot of notes in the comments, but the issue only seems to occur when the current processor owns very few or no rows of the vector and does assembly on rows that are not locally owned.

```c
#include <petsc.h>
#include <petscvec.h>

#include <stdlib.h>

// Unlike most finite element applications, IBAMR does assembly on many cells
// that are not locally owned: in some cases the processor may own zero finite
// element cells but still do assembly on a small number of cells anyway. To
// simulate this, this code assembles a PETSc vector by adding contributions
// to every entry in the vector on every processor. This causes a deadlock
// when we save the communication pattern via VecSetOption(vec,
// VEC_SUBSET_OFF_PROC_ENTRIES, PETSC_TRUE).

int main(int argc, char **argv)
{
  // Set this to 1 to enable the bug; set it to zero to disable the bug
  const int save_communication_pattern = 0;

  int ierr = MPI_Init(&argc, &argv);CHKERRQ(ierr);
  ierr     = PetscInitialize(&argc, &argv, NULL, NULL);CHKERRQ(ierr);
  ierr     = PetscPopSignalHandler();CHKERRQ(ierr);

  int rank = 0;
  int n_jobs = 0;
  ierr = MPI_Comm_rank(MPI_COMM_WORLD, &rank);CHKERRQ(ierr);
  ierr = MPI_Comm_size(MPI_COMM_WORLD, &n_jobs);CHKERRQ(ierr);

  Vec load_vector;
  PetscInt *local_lengths = (PetscInt*)malloc(n_jobs*sizeof(PetscInt));
  // This bug is triggered when one of the local lengths is small. Sometimes
  // in IBAMR this value is actually zero.
  for (int rank_n = 0; rank_n < n_jobs; ++rank_n)
    local_lengths[rank_n] = 10;
  local_lengths[0] = 2;
  if (rank == 0)
    {
      printf("local lengths are ");
      for (int rank_n = 0; rank_n < n_jobs - 1; ++rank_n)
        printf("%d ", local_lengths[rank_n]);
      printf("%d\n", local_lengths[n_jobs - 1]);
    }
  PetscInt local_length = local_lengths[rank];
  ierr = VecCreateMPI(MPI_COMM_WORLD, local_length, PETSC_DECIDE, &load_vector);CHKERRQ(ierr);

  for (int assembly_n = 0; assembly_n < 4; ++assembly_n)
    {
      if (save_communication_pattern)
        VecSetOption(load_vector, VEC_SUBSET_OFF_PROC_ENTRIES, PETSC_TRUE);
      VecSet(load_vector, 0.0);
      PetscInt local_start = 0;
      for (PetscInt rank_n = 0; rank_n < rank; ++rank_n)
        local_start += local_lengths[rank_n];
      for (PetscInt i = 0; i < local_length; ++i)
        {
          PetscInt local_index = local_start + i;
          PetscScalar entry = 1.0;
          ierr = VecSetValue(load_vector, local_index, entry, ADD_VALUES);CHKERRQ(ierr);
          // do assembly on all other processors too (the 'neighbors')
          {
            const PetscInt neighbor_length = local_lengths[i % n_jobs];
            PetscInt neighbor_start = 0;
            for (PetscInt rank_n = 0; rank_n < (i % n_jobs); ++rank_n)
              neighbor_start += local_lengths[rank_n];
            for (PetscInt j = 0; j < neighbor_length/4; j+= 3)
              {
                PetscScalar entry = 0.01;
                PetscInt nonlocal_index = neighbor_start + j;
                VecSetValue(load_vector, nonlocal_index, entry, ADD_VALUES);CHKERRQ(ierr);
              }
          }
        }
      VecAssemblyBegin(load_vector);
      VecAssemblyEnd(load_vector);
      PetscReal norm = 0.0;
      ierr = VecNorm(load_vector, NORM_1, &norm);CHKERRQ(ierr);
      if (rank == 0)
        printf("norm is %g\n", norm);
    }

  free(local_lengths);
  ierr = VecDestroy(&load_vector);CHKERRQ(ierr);
  ierr = PetscFinalize();CHKERRQ(ierr);
  ierr = MPI_Finalize();
  if (ierr != 0)
    {
      printf("MPI finalization failed.\n");
    }
}
```

**Comment by drwells** [comment]
Here is the different error message that I can now get on my workstation:
```
[drwells@auricle petsc-comm-test]$ mpirun -np 4 ./a.out
local lengths are 2 10 10 10
norm is 32.22
[1]PETSC ERROR: #1 VecAssemblyEnd_MPI_BTS() line 292 in [...]/petsc-3.10.2/src/vec/vec/impls/mpi/pbvec.c
[1]PETSC ERROR: #2 VecAssemblyEnd() line 178 in [...]/petsc-3.10.2/src/vec/vec/interface/vector.c
[auricle:00344] 3 more processes have sent help message help-mpi-btl-base.txt / btl:no-nics
[auricle:00344] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

**Comment by knepley** [comment]
@drwells @jedbrown I finally ran this and did not crash. I created a branch so that we can all run it:

  https://bitbucket.org/petsc/petsc/branch/knepley/feature-sf-test

you use

  make -f ./gmakefile test globsearch="vec_is_sf_tests-ex2*"

**Comment by drwells** [comment]
@knepley Thanks for adding the test. However, shouldn't the test enable saving the communication pattern? That is what crashed for me (i.e., `saveCommunicationPattern` should be set to `PETSC_TRUE`).

**Comment by drwells** [comment]
Looking back at my test code I mistakenly disabled the bug by defaulting to zero there...

**Comment by knepley** [comment]
@drwells Ah, I fixed it now. 
@jedbrown If you look at the second test, I get deadlock. 2 guys are in VecNorm, so they made it through Assembly. Two guys are in Assembly. One is in VecAssemblyEnd_BTS() proper, and the other is in that too, but stuck in PetscGetNewTag(). It definitely looks like there is a deadlock bug.

**Comment by drwells** [comment]
I thought about this some more over the last week about how we can improve performance in this part of IBAMR. We don't have anything to do immediately, but I want to at least write down the current state of how we can improve this part of IBAMR.
1. Changing the way we handle ghost data is irrelevant to the current performance concerns: when we do `VecSetValues` with entries that are not locally owned, the values are placed in `VecCache` which doesn't know anything about ghosts (since it doesn't make sense to write into a ghosted entry).
2. Related to the first point: since we are doing FEM we already know which entries we will place in the cache. These entries don't change between consecutive calls. It would be nice to extend PETSc with a new function `VecCacheSetIndices`  that sets these indices. We spend a noticeable amount of time (roughly 3% of time in the heart model, though this depends on the number of processors) sorting indices in the cache: setting the indices at the beginning would eliminate that.
3. There is a bug in the `Vec` option for saving the communication pattern that only shows up in pathological cases, which happen to include the heart model (such as one processor owning no entries in the vector but still having a sizeable cache). I  believe we have to live with this for now since, AFAICT, the fix is not in 3.11.

I'd like to address 2 at some point in the future. I will bring some code that does this to the PETSc workshop :)

**Comment by boyceg** [comment]
An alternative is to set values in the ghost region and then use the VecGhost routines to accumulate into the true DOFs? Does that suffer from the same performance issues?

**Comment by knepley** [comment]
So I was trying to understand why my code does not suffer from this. Now I think I understand the difference in formulation with IBAMR.

Right now, PETSc recognizes two linear spaces, which we call "global" and "local". The local space is a direct sum which is overcomplete, meaning it represents and overlapping mesh in the traditional sense. We use vectors from the local space when assembling, and from the global space when solving. To do accumulation after local assembly, we use DMLocalToGlobal(), and to get the solution vector in the local basis for assembly, we use DMGlobalToLocal().

With this strategy, VecSetValues() only happens on local vectors, so no cache. The l2g map is a VecScatter or PetscSF, so no sorting overhead when communicating. This is how all my Plex codes work, and also all the DMDA structured grid codes. I am guessing that right now, IBAMR operates completely in the global space, which is why VecSetValues() communicates. I do stay in global space for matrix assembly, but the DD methods also do a local/global split here.

Does that make sense?

**Comment by boyceg** [comment]
I think there is nothing stopping us from doing everything in the local indexing scheme using ghosted forms of the vectors. You accumulate into the ghosted local form and then accumulate back to the global form.

**Comment by drwells** [comment]
@boyceg 
> An alternative is to set values in the ghost region and then use the VecGhost routines to accumulate into the true DOFs? Does that suffer from the same performance issues?
I didn't think of it before (I did not realize ghost values could be mutable!), but this should work. We could assemble into a ghosted vector and then use
```c
VecGhostUpdateBegin(v, ADD_VALUES, SCATTER_REVERSE);
VecGhostUpdateEnd(v, ADD_VALUES, SCATTER_REVERSE);
VecGhostUpdateBegin(v, INSERT_VALUES, SCATTER_FORWARD);
VecGhostUpdateEnd(v, INSERT_VALUES, SCATTER_FORWARD);
```
to get what we want. This would be faster than using the cache since we can skip the sorting step. This is probably the right way to do things but we will have to be careful to avoid the cache.

@knepley
> I am guessing that right now, IBAMR operates completely in the global space, which is why VecSetValues() communicates. I do stay in global space for matrix assembly, but the DD methods also do a local/global split here.
Yes: we use libMesh's global DOF indexing here. To the best of my knowledge, some communication is always necessary when setting up load vectors in FE codes since a trial function owned by one processor may be integrated on a cell owned by a different processor (this happens when one basis function has support on cells owned by different processors). libMesh and deal.II both rely on `VecCache` to do this: RHS vectors are never assumed to be ghosted at any point (either assembly or when solving).

**Comment by boyceg** [comment]
There is a fairly recent branch of mine that does this. Let me see if I can find it...

**Comment by boyceg** [comment]
Take a look at #419.

**Comment by knepley** [comment]
@drwells I think you are missing my point.

VecGhost IS a local vector, but it has conditions that are sometimes onerous. All the ghost dofs in VecGhost go at the end, whereas for efficiency reasons we sometimes want a reordering of the local vector (that is what DMDA does). Thus DMGlobalToLocal() is a more flexible way of doing the same thing. VecCache is just insane because it has this sorting perf problem.

**Comment by drwells** [comment]
@boyceg Parts of #419 have been superseded but yes, that is what we should do for assembly. I already have a list of things that should be combined into a per-patch data structure represented by a class in `FEDataManager`: it would be relatively straightforward to cache the indexing (i.e., the local vector indices of ghost entries) together with everything else on my list.

I would still like to improve `VecCache` because this sort of thing is annoying to do: however, assembling into a ghosted vector is the right choice to make right now (instead of relying on possible future PETSc functionality) so I will do this.

@knepley I think I understand now: assembly in our case is much more difficult than the structured grid case since we cannot interleave ghost entries and non-ghost entries with `VecGhost` (I suspect that there is no way to do this in general with unstructured grids). With something like DMDA this is much easier. Is this correct?

If we record the dof index translation given by `libMesh::PetscVector::map_global_to_local_index` then we have effectively done a local renumbering of dofs. All the ghost dofs will still be at the end (which is not as processor cache friendly) but at least we will not have to do index translation. I think this is the right way to solve the problem and avoid `VecCache`.

**Comment by knepley** [comment]
@drwells Okay, maybe we better talk on the phone. "I suspect that there is no way to do this in general with unstructured grids" NO! I DO THIS ALL THE TIME. I have example after example in PETSc doing this correctly. I am not sure what I am saying that is making this harder.

**Comment by drwells** [comment]
More seriously: it would be nice to chat but maybe seeing an example would set me straight. Do you have one in mind?

**Comment by knepley** [comment]
If you imagine 2 triangles sharing an edge, which are owned by 2 procs. For P2, the local vectors are each of size 6, and the global vector is of size 9. I might start numbering with the unshared vertices, and number vertices before edges, so that

  proc 0              proc 1
  ------             -------
  local    global    local   global
  -----------    -----------
    0           0          0         3
    1           1          1         2
    2           2          2         1
    3           4          3         7
    4           5          4         5
    5           6          5         8

So we just have independent local and global numberings with no assumptions. You can look at SNES ex13 for the Poisson, but I am not sure how illuminating it will be, although you can print out the numberings.

**Comment by boyceg** [comment]
At some point there was a DM for libMesh; if that code is still viable, it might be worth addressing this kind of stuff in there.

**Comment by knepley** [comment]
I don't think that exists anymore. Right now, they are using a DMShell, but it might be made to respond to this interface.

**Comment by drwells** [comment]
@knepley I think I understand the example you posted. I also read through ex13.

I am not sure if we really need to use any additional renumbering objects: libMesh already calculates the local to global mapping via `ISLocalToGlobalMappingGetIndices`. I think the easiest way to proceed would be to just record all of those indices in our own array and use that to index the ghosted vector directly. What advantage would there be to using another PETSc object here?

**Comment by knepley** [comment]
None. I am saying you should replace VecGhost with a regular Vec, and use the l2g map between that local vec and the global solver vec. That means all insertions into the local Vec are local (no communication) and then there is one comunication (l2g) with no searching/sorting.

**Comment by drwells** [comment]
Would simply indexing into the `VecGhost` via the renumbering be equivalent?

**Comment by knepley** [comment]
Well, you are destroying the Ghost property of the VecGhost, so it would just be better to make it a regular Vec.

**Comment by boyceg** [comment]
> Well, you are destroying the Ghost property of the VecGhost, so it would just be better to make it a regular Vec.

I am not sure that I understand how this usage is destroying the ghost property of the `VecGhost`. I don't think there is anything in the `VecGhost` interface that says that the ghost DOFs are read-only locations -- and, indeed, the `VecGhostUpdateXXX` interface explicitly supports accumulating from the ghosted DOFs.

A pragmatic reason to stick with `VecGhost` is simply that it is directly supported by libMesh's `NumericVector` interface, whereas local `Vec`s are not.

An alternative would be for us to manage our own `Vec`s. This seems like it might be the right way to go anyway, since we are already explicitly relying on the `PetscVector` specialization of `NumericVector` --- and, in fact, are doing some things that are morally dubious with these `PetscVector` objects.

Does it make sense to have something like a `DM` with different "views" for the vectors. (E.g. one for doing standard FE assembly that only involves operations on a single mesh, another for doing interaction between the FE mesh and the background grid, etc.) What I don't like about our current strategy (which, to be clear, is a strategy that I initiated) is that there is a proliferation of different objects that are all essentially different representations of the same underlying data.

(This is approximately the same problem that SAMRAI tries to address through `Variable` and `VariableContext` objects.)

**Comment by jedbrown** [comment]
Trying to catch up on this thread...  Matt and I would recommend that data structures look like Elem -> Local -> Global where the Local -> Global part can be implemented using VecScatter (and DMLocalToGlobal) or via VecGhost. As I understand it, libMesh's dofmap stores Elem -> Global and then needs to either use `VecSetValues` (which supports dynamic communication).

Consequences of using VecGhost:
- limits your choice of ordering for the Local space by requiring that unowned dofs come after owned dofs
- increases the storage needed for your Krylov spaces by storing local data that is not used in Krylov operations (inner products, scaling, and sums).

Additionally, libMesh has some awkward overloads that attempt to keep the ghosted portion synchronized when possible. Presumably the idea was to avoid needing to communicate after axpy-type operations, but this is fragile and is not how PETSc solvers operate. I wish libMesh had given up on blurring the lines between Global (with collective semantics) and Local (with independent semantics) vectors.

**Comment by boyceg** [comment]
> Trying to catch up on this thread... Matt and I would recommend that data structures look like Elem -> Local -> Global where the Local -> Global part can be implemented using VecScatter (and DMLocalToGlobal) or via VecGhost. As I understand it, libMesh's dofmap stores Elem -> Global and then needs to either use `VecSetValues` (which supports dynamic communication).

I think this is correct -- libMesh does not seem to have a built-in notion of local indexing that can be used, for instance, for local assembly into a `Vec`. I do not think that it would be much work to create local vectors and local-to-global maps.

> Consequences of using VecGhost:
> 
> * limits your choice of ordering for the Local space by requiring that unowned dofs come after owned dofs
> * increases the storage needed for your Krylov spaces by storing local data that is not used in Krylov operations (inner products, scaling, and sums).

I *think* that we are careful to use unghosted vectors in Krylov solvers (although this requires explicitly copying between the ghosted and unghosted forms, which I do not like).

**Comment by drwells** [comment]
@jedbrown thanks for following up. I'll address this in more detail later but I would like to make a small clarification: these problems are only noticeable when setting up a load vector since we assemble on a different set of cells than the ones actually owned by the processor. The linear solver itself uses the saner partitioning and does not seem to be as problematic.

**Comment by jedbrown** [comment]
Yes, so if you only have Elem->Global, then Global indices need to be interpreted, which takes a little work (irregular memory access). If you have Elem->Local, then all your local/element processing can use direct indexing (don't even need `VecSetValues`), but you need to be able to set up the Local->Global indexing. Using `VecSetValues` works out that communication pattern on the fly, and should be a pretty efficient algorithm for it. Please let us know if you think it's doing a poor job. I'd be curious to see a detailed profile in any case.

> I think that we are careful to use unghosted vectors in Krylov solvers (although this requires explicitly copying between the ghosted and unghosted forms, which I do not like).

I doubt the cost is significant, but it's a little messy due to the three representations (Global, Global-with-Ghost, and Local form). If you use a Local vector and VecScatter for this, then you only have two forms (Global and Local).

**Comment by drwells** [comment]
I thought about this some more and I think that our best option is to use `VecGhostUpdateBegin`/`VecGhostUpdateEnd`: we should do almost exactly what is in the PETSc manual (page 55 in the 3.11 release) for accumulating values from ghost entries. I am sure that we could devise a less weird indexing scheme for our case, where half of the vector corresponds to ghost entries (and some entries may not be assembled in to at all) via `VecScatter` but I think the simpler option will suffice. We already have ghosted vectors with all the right indices: we just need to write into them directly.

@boyceg 
> in fact, are doing some things that are morally dubious with these PetscVector objects

We are, and I think some of our code no longer works in debug mode because libMesh expects objects to be in a different state. I think libMesh's solvers will close vectors automatically which we don't need to do either (since we synchronize ourselves) I think we should just copy data whenever we directly manipulate `Vec` objects to make libMesh happy again.

> I do not think that it would be much work to create local vectors and local-to-global maps.

Agreed; libMesh stores this indexing inside the `PetscVector` object. It is pretty easy to cache the localized dof indices; this is exactly what I did in #513. We don't even need to create local vectors: we can access the IB-ghosted vectors directly in their local forms (no copies).

@jedbrown 
> As I understand it, libMesh's dofmap stores Elem -> Global and then needs to either use VecSetValues (which supports dynamic communication).

Yes. `libMesh::PetscVector` does store local array indices for direct reads but these are only available one at a time. It uses `VecSetValues` when writing into entries.

> libMesh has some awkward overloads that attempt to keep the ghosted portion synchronized when possible.

Yup; this is part of the reason why we have so much of our manual synchronization code that circumvents the libMesh wrappers.

**Comment by drwells** [comment]
Roadmap for switching over to direct `VecGhost` indexing (for now just for `interpWeighted`):
- [ ] Set up `d_U_IB_rhs` vectors owned by `IBFEMethod`. `FEDataManager` can build these vectors since it knows the IB ghost data indices. Use these for assembly in `interpWeighted` (but still with `VecCache`).
- [ ] Localize the RHS inside `interpWeighted` and write directly into into it (via pointer arithmetic) by translating dof indices one at a time via `libMesh::PetscVector::map_global_to_local_index`. This should remove `VecCache`.
- [ ] Get rid of all on-the-fly index translation via #513 (i.e., memoize all calls to `map_global_to_local_index`).

**Comment by drwells** [comment]
It turns out that on the fly index translation is not particularly expensive. Given the complexity of #513 I don't think its worth implementing at this time. Therefore this is done.
