### ISSUE TITLE
Results vary across identical runs

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#506]
Blocks #494: one of the test programs in the new test suite, based on an IBFE example, gives different results on independent runs: some quantities are only identical up to six decimal places.

I believe the results are still second-order accurate in each case but the lack of consistency is bad for reproducibility (particularly with long time integrations).

**Comment by boyceg** [comment]
Serial or parallel?

**Comment by drwells** [comment]
Parallel. I also need more than two processors to reproduce this.

**Comment by drwells** [comment]
FWIW also added `PetscOptionsSetValue(nullptr, "-ksp_rtol", "1e-14");` to the top of the program; it didn't seem to help.

**Comment by boyceg** [comment]
Make sure you verify that the actual solves are using tight tolerances — run with -ksp_view for the mass matrix solves, which I think are the likely candidates.

There are certain MPI operations involving accumulation of values from multiple processors that can be non-deterministic — eg items are summed in the order they are communicated, which can depend on network traffic. This caused some non-deterministic results in IB that I tracked down ~10 years ago. I need to see if we are doing similar things in IBFE.

(In essence, any parallel accumulation operation can cause this kind of behavior.)

You could try nodal interaction and/or diagonal mass matrices to see if it affects this issue; that could help to track down where this is coming from.

**Comment by drwells** [comment]
One particular line in the output file has a relative error of 10^-3 with the current settings.

Changing all of the residual tolerances to `1e-16` (I did it in the source files) improves this to 10^-9: the CFL number and upper bound on IB displacement have the highest errors.

**Comment by drwells** [comment]
The number of iterations in the stokes solver also changes when go from 3 MPI processes to 4.

**Comment by boyceg** [comment]
You need to make sure that the solvers are themselves configured to give consistent results on different numbers of processors. For multigrid, this requires using smoothers like Jacobi, which is not the default. Also, if you are using multiple grid levels, the AMR grid patches are not guaranteed to be consistent on different numbers of processors.

**Comment by drwells** [comment]
> For multigrid, this requires using smoothers like Jacobi, which is not the default.

Hm.. I guess Gauss-Seidel does depend on the local partitioning. Good point.

> Also, if you are using multiple grid levels, the AMR grid patches are not guaranteed to be consistent on different numbers of processors.

Thats not something I thought would show up.

I think that, at least for the test suite, we need to get the relative error between runs down to 1e-9 or so (lower is better). I think I found where a solver tolerance has a hard-coded value that is rather high. I'll put up a patch to fix it once I confirm.

**Comment by drwells** [comment]
I figured it out (at least part of it, for now): the default tolerances for the stokes solver are very high. Running with `-stokes_ksp_atol 1e-12` fixes it.

That solves the major issue with the test suite: I can now get results that are consistent up to about 1e-9 (instead of 1e-2).

Thanks for the help @cpuelz :)

**Comment by boyceg** [comment]
It is worth putting in some unit tests for IB and IBFE interpolation and spreading operations, to make sure that they are consistent in parallel. Because the IBFE interpolation routine involves a mass matrix solve, we may need to be careful that IBFE interpolation is setup to guarantee exact reproducibility in parallel.
