### ISSUE TITLE
Timer code

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#521]
Should we remove all of the `Timer` objects?

Some reasons to do this:

1. We don't use them for timing!
2. They generate a large number of LOC.
3. They are hard to maintain.

The only reason that I can think of not to do it is that they are already in the code, and so if we ever do want or need to do more intrusive timing, they are ready to go.

**Comment by drwells** [comment]
I have never used these. I think our time would be better spent writing documentation for how to use things like openspeedshop or other 'real' profiling tools.

**Comment by boyceg** [comment]
Should we set up a new "starter project" to remove these things and suggest a student to do it?

**Comment by drwells** [comment]
Sounds reasonable to me. We can just label this issue as such.

**Comment by drwells** [comment]
It's been over a year and quite frankly recompiling everything with openspeedshop is such a pain that we should keep these - they have been very useful and don't really cost much to keep around.

**Comment by boyceg** [comment]
OK with me. In that case, however, we should maybe go back and be more systematic with deploying them (and maybe add some infrastructure to make it easier?). Are there clever ways to make setting these things up require less boilerplate code?

**Comment by drwells** [comment]
We could use RAII where the ctor starts the timer and the dtor stops it.
