### ISSUE TITLE
Should INSHierarchyIntegrator::regridProjection be public?

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#527]
Followup discussion from #524.

**Comment by amneetb** [comment]
If regridProjection() is not public, then it should be called just before first time step and not at the place where it is getting called now. 

I made it public to have a fine control on the process.

**Comment by boyceg** [comment]
I don't think it needs to be `public`. It should be fine to keep it `protected`. Time steppers should be able to call it when they need to.

**Comment by amneetb** [comment]
I am fine with this. But we need to move the location of the initial call in the all the current INS integrators.

**Comment by boyceg** [comment]
OK, great. @amneetb, can you put in a PR with the needed changes once #524 is merged?
