### ISSUE TITLE
Infrastructure for caching Eulerian data

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#533]
We should consider making it easier to cache Eulerian data, to avoid repeatedly allocating/deallocating data on the AMR grid hierarchy, perhaps by having an `AMRDataCache`(?) object that allows callers to "check out" and "return" data with a particular layout/depth/ghost cell width.

**Comment by drwells** [comment]
Should we do this before #472 ?

**Comment by boyceg** [comment]
I think we need to think a little bit about whether it is a good idea to have either a global or local data management class that tracks these data. I was originally thinking that it would be a global manager class (like SAMRAI's VariableDatabase), to maximize data reuse, but perhaps it is cleaner to have a local caching class, similar to some of the FE data management classes.

**Comment by boyceg** [comment]
This is addressed in #538 and #572.

**Comment by boyceg** [comment]
I am going to close this because the infrastructure now exists.
