### ISSUE TITLE
Remove deprecated libMesh calls in examples

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#554]
I forgot to look for deprecated libMesh functions in the examples in #500. We should go back and get rid of, e.g., calls to `get_node`.

**Comment by boyceg** [comment]
In fact, I think that the examples do not currently compile with libMesh master unless libMesh is compiled with deprecated functions enabled.

**Comment by drwells** [comment]
This is pretty easy to do so I will label it as `starter project`.

The easiest way to do this is to compile libMesh without support for deprecated functions. That will turn all of our usages into compile errors. The substitutions are all the same as those in 589f73621caf4fd358906454bff6c165eb74246c.
