### ISSUE TITLE
Advection diffusion solver iterates when there is no diffusion.

### ISSUE THREAD

**Issue by abarret** [IBAMR/IBAMR#573]
The advection diffusion solver will iterate even if the diffusion coefficient is set to 0. Since we are using explicit time stepping for advection, we should skip the ksp solve in this case.

**Comment by boyceg** [comment]
@abarret @drwells this should be easy to fix --- can we try to get a fix in before 0.5?

**Comment by abarret** [comment]
Yes. I already have a fix for this. I just wanted to convert some adv_diff examples to tests before I create a PR.

**Comment by drwells** [comment]
It sounds like you know what to do. Let me know if you need any help with the tests.

**Comment by drwells** [comment]
@abarret *ping*
