### ISSUE TITLE
Permit the structure to live on more than one Eulerian level

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#581]
From a conversation in today's meeting: we really want to be able to assign different subdomains to different mesh levels. In particular: we want the valves to talk to something even finer than what we use now.

We should be able to do this by, instead of just looping over the finest level, determining the relevant levels and then looping over those.

There are some other important questions to resolve here, e.g., its not immediately clear which interpolation scheme to use to avoid spurious rotations.

**Comment by boyceg** [comment]
@drwells, before doing this, could you try to create a unit test for the RT0-like coarsen/refine operators?

**Comment by drwells** [comment]
I'll take a look.

**Comment by drwells** [comment]
I forgot that we talked about this last year. This was tracked and fixed in #1112.
