### ISSUE TITLE
Make attest less laconic

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#588]
We should add an equivalent of `ctest`'s `V` or `VV` flags to `attest` so that, when we run in verbose mode and a test fails, we can print the error message to the screen. This would be more convenient then digging through the temporary directory `attest` creates.

**Comment by amneetb** [comment]
https://github.com/IBAMR/IBAMR/blob/master/tests/multiphase_flow/rotating_barge_cib.cpp#L130

Dumb question: Anything before this line is executed just by processor 0? When does the SIMD part start? With `mpirun -np 4 rotating_barge_cib free_falling_cyl_cib.mpirun=4.input` won't all the 4 processors write out this file?🤔

**Comment by drwells** [comment]
All four processors attempt to write, but only one gets the file handle and can actually produce output (the other three wait for the file handle from the OS). I think. I'll go back and add barriers so that this is clearer.

**Comment by amneetb** [comment]
Why barrier? Why not just have processor 0 write this out? Once the file is written, no need to write this again from other processors.

**Comment by drwells** [comment]
You're right, we don't need barriers. Either way: its now fixed.

**Comment by drwells** [comment]
#1289 implemented verbose mode so this is now fixed.
