### ISSUE TITLE
Detect opt/debug mismatch between libmesh, SAMRAI, (maybe also PETSc), and IBAMR during configure stage of IBAMR.

### ISSUE THREAD

**Issue by amneetb** [IBAMR/IBAMR#591]

**Comment by drwells** [comment]
@amneet Is this the same issue you mentioned by email?

Its not clear to me how we should proceed here: in particular, since libMesh is *much* slower in debug mode in parallel I would prefer to permit mismatches. What do you propose we implement?

**Comment by amneetb** [comment]
If SAMRAI is in debug mode and libMesh is in opt mode, then there is incompatibility between NDEBUG symbol used by both libraries. This leads to linkage error down the road. 

We can check that all 3 (SAMRAI, libMesh, and IBAMR) libs are in either opt or dbg mode. I think we already do this with IBAMR and libMesh through the use of —with-methods. We just need to check for SAMRAI (I think)

**Comment by drwells** [comment]
Got it.
