### ISSUE TITLE
restarts are intermittently broken on master

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#600]
I am getting (most of the time) either segmentation faults or SAMRAI errors when writing restart files on master. I need to spend some more time bisecting since the failure seems to be intermittent, but my current best guess is that changes in or near 7c1ed1b broke this. This might be wrong since I might have marked a commit as good when I simply got lucky.

We need to write some tests that verify that we can write restart data, since its not at all clear where the problem is: we haven't really touched any restart code recently AFAIK.

**Comment by drwells** [comment]
This is a fascinating bug: I have now been able to produce the following behavior on master:
1. Sometimes things complete normally.
2. Sometimes HDF5 fails to open a file.
3. Sometimes PETSc catches a segmentation fault.

This is all with the heart model.

**Comment by cpuelz** [comment]
weird.  what branch of the heart model are you using?  can you point me to the input file you are using?

can you replicated any of this behavior with one of the working IBAMR examples?  maybe an IBFE one?

**Comment by cpuelz** [comment]
was there a point in time that you are sure restart was working with the heart model?

also, can you tell me how you are restarting, i.e. what command line options are you using?

**Comment by drwells** [comment]
@cpuelz to be clear, I am pretty sure that this is a bug in IBAMR, not the heart model.

I am using `master` in the heart model. I have a modified version of contraction14 that does very few time steps. I set the restart to something insanely low (every 10 time steps) to get this behavior.

I will try with an IBFE example next.

**Comment by cpuelz** [comment]
okay cool.  did you have a look at some of the restart scripts in the heart model directory to compare with your command line options?  I am only pestering since I recall having some issues getting restart working.

there are also multiple things in the heart model that need to be restarted, like the circulation model and the fluid sources, in addition to the FE and fluid data, and those implementations may need to be double checked.

**Comment by cpuelz** [comment]
also, contraction14 on a newer branch of the heart model may not work correctly.  maybe try contraction38 or contraction39.

**Comment by drwells** [comment]
Why did you break my input files :crying_cat_face:

More relevantly: I am running some IBFE examples now. So far so good.

**Comment by drwells** [comment]
I cannot reproduce this with any of the IBFE examples so it looks like my out-of-date input file for the heart model is the culprit.

**Comment by cpuelz** [comment]
@drwells sorry for the pain!
