### ISSUE TITLE
Improve FEDataManager::buildL2ProjectionSolver

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#622]
I think it would be a good exercise for one of the graduate students to go through this function and check that:
1. We are enforcing hanging node/dirichlet boundary/other algebraic constraints on the dofs correctly
2. We end up with an SPD matrix
3. We use, where possible, some of our own caches (like `FECache`) to avoid unnecessary recomputation of things
4. We set up the sparsity of the underlying PETSc matrix correctly so that assembly is quick
5. We always use the same preconditioner (block Jacobi)
6. We always use CG (since the mass matrix better be SPD)

Regarding 2 and 6: it looks like we are setting some values explicitly to 1.0 in the matrix, which is going to make the condition number not so nice.

**Comment by boyceg** [comment]
Perhaps this is something that @benlvr could work on. I’ve asked him to investigate the role of consistent-vs-lumped mass matrices in both computing elastic forces and in velocity restriction.

**Comment by drwells** [comment]
Sounds good. Its not a very good comparison if we have a nonoptimal solver for the consistent case :)

**Comment by drwells** [comment]
@benlvr are you willing to tackle this? We can meet to chat about it.

**Comment by benlvr** [comment]
@drwells @boyceg Yes, I can work on this and would be happy to meet.

**Comment by drwells** [comment]
See the branch https://github.com/IBAMR/IBAMR/tree/drwells/improve-l2-solver for some notes on how to set the solver to CG.

**Comment by drwells** [comment]
We addressed this in a couple of other commits like #916, #1029, and #1052.
