### ISSUE TITLE
Add a simple Brinkman test code

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#627]
We should add a very basic example that demonstrates how the new Brinkman code works (since it is a very useful tool for a bunch of different applications) and a corresponding test: it doesn't have to be fancy.

**Comment by drwells** [comment]
@amneetb This didn't happen in time for 0.7: how do you suggest we proceed?

**Comment by amneetb** [comment]
@nishantnangia is adding support for inhomogeneous Neumann and Dirichlet boundary conditions using Brinkman penalization in a WIP branch `nishant/brinkman-adv-diff` for a general advected and diffused variable. This will be ready post 0.7 release and we will add tests then.

**Comment by drwells** [comment]
Fixed by #1132.
