### ISSUE TITLE
Different RHS vectors in IBFEMethod::interpolateVelocity

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#636]
I am getting slightly different RHS vectors in parallel when the only thing I change is the version of PETSc (in this case 3.7.7 vs. 3.11.0). The differences are pretty large: the L2 norm of the RHS vector changes in the fifth significant digit, which is way larger than it should be if the issue were purely from roundoff error accumulation.

This causes the maximum pointwise error to vary in the second significant digit, which is bad w.r.t. the test suite.

**Comment by drwells** [comment]
Another interesting problem is that only one component is effected by this: the error in the first component is consistent, but not the error in the second component.

**Comment by drwells** [comment]
This also means that if we want to actually use the test suite now, it only really works with recent releases of PETSc.

**Comment by drwells** [comment]
The good (or maybe bad?) news is that this also happens on a single MPI process.

**Comment by knepley** [comment]
Hmm, I thought this was going to be reordering. If it happens in serial, is it possible that there is some aux solve used in constructing the RHS?

**Comment by drwells** [comment]
My first post was slightly inaccurate: I also used libMesh 1.3.0 for one set of calculations and libMesh 1.3.1 for another set. Its possible that something relevant changed there too.

**Comment by drwells** [comment]
There is no auxiliary solve used to set up the RHS: the RHS comes from interpolating the Eulerian data.

**Comment by knepley** [comment]
Ah, that sounds like it might be interpolators in LibMesh. I can't think of anything serial in PETSc that would do this.

**Comment by boyceg** [comment]
This is the same IBAMR code but two different versions of libMesh and PETSc?

**Comment by drwells** [comment]
Yes.

**Comment by drwells** [comment]
libMesh 1.3.0 and 1.3.1 give the same output. I'll try varying PETSc versions.

**Comment by drwells** [comment]
OK, I get the same failures with PETSc 3.11 and 3.7.

I am starting to think that the problem comes from muparser.

**Comment by drwells** [comment]
no, thats not it either.

**Comment by drwells** [comment]
I spent most of today looking at this and I still don't have an answer. For now, I think we will have to accept that the test suite only works with a very specific combination of libraries. We will have to fix this (we should not have 10% differences in point errors) in the future.

**Comment by drwells** [comment]
@boyceg it might be due to me using `-march=native`.

**Comment by boyceg** [comment]
Oooh. You are living dangerously there.

**Comment by drwells** [comment]
Another thing to do would be to implement `--relax-tolerances` for the test runner to run things in a way that a 25% relative difference is acceptable.

**Comment by boyceg** [comment]
I am not sure if there are any of these tests where 25% differences are expected. With uniform grids, I would expect very small differences in parallel because of lack of associativity of floating point arithmetic. With AMR grids, the actual grid that is generated can be different with different numbers of processors, and that can lead to relatively large differences. However, those are not the kinds of differences it sounds like we are talking about here...

**Comment by drwells** [comment]
The other thing to keep in mind is that I generated all of the output files with one particular setup that all the other setups I have happen to disagree with. Its possible that, for whatever reason, that setup is just an oddball (perhaps due to `-march=native` or something else).

**Comment by boyceg** [comment]
Should the results be generated with all compiler optimizations turned off?

**Comment by drwells** [comment]
That should not matter, but I cannot rule it out yet. `-march=native` shouldn't matter either since its still *supposed* to follow the rules for floating point arithmetic (I did not use `-ffast-math`).

**Comment by drwells** [comment]
OK, the problem is with libMesh: keeping everything else constant, the tests pass with 1.2.1 and 1.3.1 but fail with 1.4.1 (again, not by a lot: the error changes by about 10%). This is with my self-compiled versions: for reasons I don't understand things also fail with my spack-installed libMesh 1.3.1.

I might bisect this later.

**Comment by drwells** [comment]
Problematic tests:
```

    IBFE/interpolate_velocity_01_3d.a.mpirun=4.input
    IBFE/interpolate_velocity_01_3d.b.mpirun=4.input
    IBFE/interpolate_velocity_01_2d.b.mpirun=4.input
    IBFE/interpolate_velocity_01_3d.c.mpirun=4.input
    IBFE/interpolate_velocity_01_3d.c.ghosted.mpirun=4.input
    IBFE/interpolate_velocity_01_2d.a.mpirun=4.input
    IBFE/interpolate_velocity_01_3d.c.cached.mpirun=4.input
    IBFE/interpolate_velocity_01_2d.d.mpirun=4.input
    IBFE/interpolate_velocity_01_2d.d.cached.mpirun=4.input
    IBFE/interpolate_velocity_01_2d.d.ghosted.mpirun=4.input
```

**Comment by drwells** [comment]
My new best guess is that libMesh changed something with either partitioning or quadrature rules between 1.3.1 and 1.4.1.
