### ISSUE TITLE
Missing rpath arguments

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#639]
It looks like, when we have external dependencies that are shared object files, we don't always set rpath correctly. This came up on the mailing list recently. I think that we don't usually run into this problem because PETSc and libMesh add rpath to their exported link flags, which we also use: for that reason I can only reproduce this problem with my shared object copy of silo.

For reasons I don't fully understand, I can compile the examples without linkage problems, but (like on the mailing list) I cannot successfully link against silo with the provided makefile.

**Comment by drwells** [comment]
OK, I think I see how to fix this: `AC_LIB_HAVE_LINKFLAGS` will add the correct rpath information to the link variables, but `AC_CHECK_LIB` does not.

**Comment by boyceg** [comment]
Yes, that is why I use that macro to figure out linker flags! :-D The only alternative that I could find XX years ago when I started using Autotools was to use Libtool, which at that time did not play nicely on many HPC systems.

**Comment by drwells** [comment]
You're absolutely right. One day, I will be able to fix a build system on the first try, but this has not happened yet.

**Comment by boyceg** [comment]
Perhaps there is now a better way to do this. The last time that I seriously looked into this was > 10 years ago.

**Comment by drwells** [comment]
Since we want to support custom makefiles we really need to assemble these linker flags in this way: I don't know a lot about libtool, but since we just export a list of link flags I think that we cannot rely on users calling libtool on their executables to link things correctly.
