### ISSUE TITLE
Pair opening istreams with checks

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#643]
From our group meeting today: `std::istream` (or, more relevantly, `std::ifstream`) can stream in junk if the file name we gave it does not correspond to a file that actually exists. This is pretty easy to check: we just need to do
```cpp
std::ifstream input("filename");
TBOX_ASSERT(input);
```
to verify that the stream is good.

**Comment by boyceg** [comment]
Can we close this issue?

**Comment by drwells** [comment]
Yup.
