### ISSUE TITLE
Update muParser to use unique_ptr

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#645]
With the recent changes (like #644 and #610) we are doing a much better job with external warnings: one of the big remaining ones is muParser's `auto_ptr` usage. We should either upgrade our bundled version of muParser or switch to a newer one that uses `unique_ptr`.

**Comment by boyceg** [comment]
If there is a newer version that uses C++11, then we should switch versions.

**Comment by boyceg** [comment]
The muParser source code is now on GitHub (see [here](https://github.com/beltoforion/muparser)), and it now uses `unique_ptr` instead of `auto_ptr`.

**Comment by drwells** [comment]
AFAICT since the new version of muParser switched to CMake we will have to (in order to continue bundling it) essentially write our own build system for muParser (yuck). I have a partial fix based on libtool but it needs some more work.

**Comment by drwells** [comment]
Update: we now compile our bundled copy of muParser in the same way as everything else in IBTK which is much simpler than writing our own build system.

**Comment by boyceg** [comment]
One thought — we have tried to allow users to provide an external muParser. Are they still able to do this?

**Comment by drwells** [comment]
Yup!
