### ISSUE TITLE
Refactor FEDataManager to not expose Eulerian data

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#647]
This comes from some thoughts I have had while working with FEDataManager and IBFEMethod this week.

We use FEDataManager in two different ways: we use it to access libMesh data and also to do some FSI stuff (i.e., the loop that collects IB points). It would be easier to avoid shooting ourselves in the foot if we separated these a bit better: users should really not be calling `interpWeighted` directly. We could reimplement what we have as a base class that contains all the libMesh stuff and then an inheriting class with all the more internal stuff (and SAMRAI data) to be used by IBFEMethod.

I am not sure if this is reasonable but I want to at least write down the idea for future consideration somewhere.

**Comment by drwells** [comment]
I thought about this some more in the context of #654's primary issue (dealing with postprocessors). The fundamental issue is that a postprocessor should not need to know about the scratch hierarchy that IBFEMethod needs for performance reasons: in fact, the postprocessor doesn't really need to do any IB calculations at all so it might want to deal with Eulerian data in a completely different way. We can do this correctly if we use the same set of libMesh data structures for the postprocessor and IBFEMethod but each object maintains its own "FEDataManager" object which only reads libMesh data and keeps its own set of patch-to-element maps, SAMRAIDataCache, etc.

**Comment by drwells** [comment]
This changes would not be backwards compatible but they would make future work with these classes a lot simpler.

**Comment by boyceg** [comment]
Sounds good to me.

**Comment by drwells** [comment]
We more-or-less have this done now in a way that doesn't massively break user codes, so I think that now that we have #704 this is done.
