### ISSUE TITLE
Excessive memory usage in applications

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#657]
@boyceg @marshallrdavey Lets collect what we know in one place. I spent some more time poking around yesterday and I have a few ideas on how to proceed.

For those who are new to the discussion: under some circumstances on some machines the heart model exhibits a (slow) linear growth in the amount of memory (as measured by `getrusage`) over time.

The bad news is that I ran a few tests with a memory sanitizer and I have not yet been able to actually detect any *leaks*: the memory is allocated and (at least for IBFE/explicit/ex4) still deallocated at the end of the program. MPI does leak a little bit of memory, but it only does it in two places and it is not substantial enough to cause our current problems.

Hence, I don't think valgrind or the compiler's leak sanitizer are going to help us find this bug.

My current plan is to run the heart model for a long time on my workstation with `heaptrack`, which intercepts calls to `malloc` and then records the results. I attached a graphical depiction of our memory usage in `ex4`. *warning*: I haven't used this tool before: it generates nice plots but tools built around libunwind sometimes print obviously nonsense answers, so its possible this is misleading us. I'll assume for the rest of the discussion that its reasonably accurate, but we should do more testing.

Here is a visualization of our memory usage generated by heaptrack:
![heaptrack-screenshot](https://user-images.githubusercontent.com/3917035/63180780-f85d6b80-c01c-11e9-8a63-05f43dd2098f.png)
This is a flamegraph describing where we allocate memory: most of our allocations come from doing stuff with SAMRAI. We allocate and deallocate an incredible amount of memory: heaptrack measured that, for this 32^3 grid, we allocated/deallocated nearly a terabyte over a thousand timesteps, which seems wrong (but nevertheless here we are!)

My current best guess is that we are breaking SAMRAI's memory pool implementation with our incredible number of allocations and deallocations, but we need to investigate further before I will be sure.

**Comment by drwells** [comment]
The previous picture is for one MPI process. I'll post more data when I get it.

**Comment by knepley** [comment]
Note that you can use Massif (part of valgrind) to do the same job. I have liked its interface.

**Comment by abarret** [comment]
You should consider tracking the number of calls to `PatchLevel::allocatePatchData` and `PatchLevel::deallocatePatchData` where SAMRAI does most of its data allocation. Currently, I think we allocate and deallocate pretty freely. We could probably do a more efficient job of maintaining data storage.

**Comment by drwells** [comment]
Those show up very prominently in the profile.

**Comment by boyceg** [comment]
At every time step, SAMRAI data are set up in `preprocessAdvanceHierarchy()` and torn down in `postprocessAdvanceHierarchy()`. (This memory allocation pattern was recommended to me long ago when I first started working with SAMRAI.) It should be fairly easy to change this to use `SAMRAIDataCache`, to "recycle" allocated data. I think that reallocation is unavoidable when level configurations change, however.

Speaking of which, I wonder if the relatively new `SAMRAIDataCache` caching mechanism is somehow responsible.

**Comment by boyceg** [comment]
For "state" variables, there are typically three "realizations" that are available in a given time step, `CURRENT`, `SCRATCH`, and `NEW`. Scratch and new data are allocated in the pre-step routine. The post-step routine swaps the current and new data (so that the new data at step `n` becomes the current data at step `n+1`), and then deallocates the scratch and new data.

I think that this is now all handled in the `HierarchyIntegrator` base class, and so it should not be too painful to change the way that it works.

**Comment by abarret** [comment]
In particular, the convective operators deallocate and allocate scratch data during each call of `applyConvectiveOperator`. Other places where scratch data are used that are not "state" variables follow this same pattern of "allocate when needed then deallocate when finished."

**Comment by boyceg** [comment]
> In particular, the convective operators deallocate and allocate scratch data during each call of `applyConvectiveOperator`. Other places where scratch data are used that are not "state" variables follow this same pattern of "allocate when needed then deallocate when finished."

Ah yes, I forgot about these. These could also all be replaced by appropriate calls to a `SAMRAIDataCache`.

**Comment by drwells** [comment]
@marshallrdavey Could you try running the heart model with IBAMR 0.4.1? That release predates the inclusion of SAMRAIDataCache.

**Comment by marshallrdavey** [comment]
I'm currently running v0.4.1 on longleaf. Is there another build you would like me to try?

**Comment by drwells** [comment]
Well, that rules of `SAMRAIDataCache`. I can't think of anything else to check at the moment besides using mastif or heaptrack.

**Comment by boyceg** [comment]
How does 0.4.1 handle temporary libMesh vectors? Is it still using my ugly old code with raw pointers and manual deallocation?

It might be worth making a big dumb 3D model using IBMethod to see if this is specific to IBFEMethod.

Likewise, it should be possible to see if it is related to SAMRAI data management by making a big Navier-Stokes example. Probably you would want something with actual dynamic mesh refinement over a very long simulation --- perhaps BCs that setup an unsteady shear layer in 3D?

**Comment by drwells** [comment]
> How does 0.4.1 handle temporary libMesh vectors? Is it still using my ugly old code with raw pointers and manual deallocation?
Nope: we use `std::unique_ptr` in IBFEMethod for 0.4.1.

> Likewise, it should be possible to see if it is related to SAMRAI data management by making a big Navier-Stokes example.

Good idea.

**Comment by boyceg** [comment]
> > How does 0.4.1 handle temporary libMesh vectors? Is it still using my ugly old code with raw pointers and manual deallocation?
> 
> Nope: we use `std::unique_ptr` in IBFEMethod for 0.4.1.

OK, well, it still might be worth instrumenting the libMesh NumericVector class with a static member variable to track how many are currently allocated.

**Comment by boyceg** [comment]
Can you easily track down where these things are being allocated? There are a number of Krylov solvers that are used, and these may carry around temporary vectors.

Perhaps you could instrument PETScSAMRAIVectorReal to report the number of allocated vectors.

**Comment by boyceg** [comment]
In particular, I would recommend matching up MPI libraries (including the same version) and compilers.

**Comment by marshallrdavey** [comment]
Here are some comparisons between longleaf and kardia1 for memory output. For reference:
longleaf:
	-n 36
	-libmesh 1.4.1
	-petsc 3.10.5
	-IBAMR 0.4.0-rc1
	-openmpi 4.0.1
	-gcc 6.3.0
	-branch davey/dashpot
	-full heart model, 9 exodus files
kardia1:
	-n 36
	-libmesh 1.4.0
	-petsc 3.10.0
	-IBAMR 0.4.0-rc1
	-openmpi 3.0.0
	-gcc 5.4.0
	-branch origin/memory
	-afterload model, only pulmonary artery and aorta with corresponding valves, 2 exodus files
![memoryComp](https://user-images.githubusercontent.com/42808017/63961790-901c7a00-ca5f-11e9-935b-96412f87336c.png)

**Comment by drwells** [comment]
The main difference between these runs is the number of exodus files. @marshallrdavey is going to set up some more experiments where the only difference between the runs is the number of exodus files.

**Comment by boyceg** [comment]
Also the afterload only model should be much smaller?

But a good test could be to turn off all viz output.

**Comment by marshallrdavey** [comment]
I'm starting kardia1 without viz or restart output right now, afterload model still

**Comment by marshallrdavey** [comment]
The memory growth looks the same for the afterload model with and without writing visualization files during the simulation.

**Comment by drwells** [comment]
@marshallrdavey I can see the memory usage grow from about 1.92779e+07 KB to 2.23814e+07 KB over 11,000 time steps. I used 8 MPI processes. Is this near what you observed?

**Comment by marshallrdavey** [comment]
I observed growth from 1.12e07 KB to 1.32e08 KB in the same span using 32 mpi processes.

**Comment by drwells** [comment]
I set up @marshallrdavey's example and can now get the memory usage to increase at each time step. I am going to leave this running with massif for a few days.

**Comment by drwells** [comment]
I'm not happy with this conclusion, but ultimately neither @marshallrdavey or myself were able to figure out the cause of this. In particular, no tool I tried could reproduce the behavior we observed on the cluster in a way that we could determine the cause of the memory usage growth.

Hence, since there is nothing we can do, there is no reason to keep this open.
