### ISSUE TITLE
configuration broken when libMesh is compiled without netCDF

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#671]
This came up on the mailing list today. I think that we rely on detecting netcdf to set up libMesh's link flags correctly: i.e., we can only configure with libMesh if netcdf is available.

I'm taking a look at this now.

**Comment by boyceg** [comment]
Oops.

I think that without NetCDF, libMesh also does not have ExodusII. Does that sound right? I think all IBFE examples expect libMesh to have ExodusII.

**Comment by drwells** [comment]
Yes (I think netCDF is required by exodus). I think we permit compiling without exodus (we just don't save any libMesh output, which is not terribly useful).

**Comment by knepley** [comment]
Yes, ExodusII requires NetCDF.

**Comment by drwells** [comment]
My machine includes a copy of this library so disabling it is going to be tricky.

**Comment by drwells** [comment]
I am not sure if its related, but we currently pick up the system version of netcdf and also libMesh's:
```
[drwells@learch ex4]$ ldd main2d | grep net
        libnetcdf.so.7 => /home/drwells/Applications/libmesh-1.1.0.g/lib/libnetcdf.so.7 (0x00007f34a2065000)
        libnetcdf.so.15 => /lib/libnetcdf.so.15 (0x00007f349c8d7000)
[drwells@learch ex4]$ 
```
I am surprised that this even works due to the duplicate symbols. We need to prevent linkage against the system copy of netcdf: I am not sure if this the cause of this issue but we need to prevent it.

**Comment by drwells** [comment]
I do not know of any way to reproduce this issue: I have not seen it on any other Macintosh. We explicitly add libMesh's link flags by using their own shell script to print them out so if this fails to include the path to libMesh itself then something has gone wrong that is outside of our control. Hence, unless someone can reproduce this, I suggest we close the issue since we have no way to fix it.

**Comment by drwells** [comment]
I am aware of multiple IBAMR installations on macs that do not have this issue. Since none of us can reproduce it I am pretty sure the original problem was due to something outside of our control. Hence I am going to close this until there is more evidence of a problem.
