### ISSUE TITLE
muParser warnings

### ISSUE THREAD

**Issue by boyceg** [IBAMR/IBAMR#676]
I am now seeing a bunch of muParser warnings:
```
/Users/boyceg/code/IBAMR/ibtk/contrib/muparser/include/muParserBytecode.h:51:7: warning: anonymous types declared in an anonymous union are an extension [-Wnested-anon-types]
```

**Comment by drwells** [comment]
I thought this looked familiar: we need to redo

https://github.com/dealii/dealii/commit/9c42acfb6a976436b004bf3ff9c065d6443d4343

here.
