### ISSUE TITLE
CIBFEMethod doesn't work

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#721]
I tried to write a test for CIBFEMethod based on `examples/CIBFE/ex0/example.cpp` but then realized that this class has some serious problems: there will always be a segmentation fault in the constructor since it tries to add a system to the `EquationSystems` object which is not set up until we actually call `initializeFEEquationSystems`.

I suspect that this is already known and is why we did #193. We should either fix this class or remove it.

**Comment by amneetb** [comment]
This class needs a dedicated PhD student to work on. Suggest marking it as a WIP class.

**Comment by amneetb** [comment]
I agree. We can also do this for codes like CIBStochasticMethod in other branch.
