### ISSUE TITLE
Forgotten c++11 updates

### ISSUE THREAD

**Issue by abarret** [IBAMR/IBAMR#726]
This is something that never got changed during the c++11 updates. We discussed at one point changing `> >` to `>>`, but that change never got implemented. Is this something that we still want to change? Also related, the .clang-format file uses the standard `Cpp03` instead of `Cpp11`.

I caught this while running clang-format on the complex fluid code. I have a script somewhere to make this change, so it could be done quickly.

**Comment by boyceg** [comment]
Let's hold off on changing the clang format settings until we get these lingering PRs handled. I am going to work on NWT over the next week. I also think that @AminKolah is working with @drwells on getting his IIM branch ready to merge. Perhaps we can update the clang format settings once we get all of that stuff done.

**Comment by drwells** [comment]
I'm going to merge this into #1299.
