### ISSUE TITLE
Improve spreading in IBFEMethod/FEDataManager

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#737]
From #654: during review we pointed out that the way we handle force spreading in IBFEMethod is pretty inefficient (with multiple parts). It would be better to resolve the accumulation of forces spread outside the domain once inside IBFEMethod instead for each part separately in FEDataManager.

**Comment by drwells** [comment]
Another idea: since we add spread data we do not need to communicate from the primary hierarchy to the scratch hierarchy: right now FEDataManager immediately swaps whatever force data is put in and then swaps back and adds. We could get around this by calculating the new force contribution on the scratch hierarchy, communicating that to a scratch index, and then adding that to the existing force values.

**Comment by boyceg** [comment]
> Another idea: since we add spread data we do not need to communicate from the primary hierarchy to the scratch hierarchy: right now FEDataManager immediately swaps whatever force data is put in and then swaps back and adds. We could get around this by calculating the new force contribution on the scratch hierarchy, communicating that to a scratch index, and then adding that to the existing force values.

Yes, exactly.

For spreading, just communicate Eulerian force data from the scratch hierarchy to the primary hierarchy.

For interpolation, just communicate Eulerian velocities from the primary hierarchy to the scratch hierarchy.

**Comment by drwells** [comment]
From an email @boyceg sent me earlier (I don't want this to get lost in my inbox):

```cpp
// Communicate ghost data.
for (const auto& u_ghost_fill_sched : u_ghost_fill_scheds)
{
    if (u_ghost_fill_sched) u_ghost_fill_sched->fillData(data_time);
}

if (d_use_scratch_hierarchy)
{
    assertStructureOnFinestLevel();
    getPrimaryToScratchSchedule(
        d_hierarchy->getFinestLevelNumber(),
        u_data_idx,
        d_ib_solver->getVelocityPhysBdryOp())
        .fillData(data_time);
}
```

Probably can be simplified to either do one or the other based on whether the scratch hierarchy is used or not.

Specifically, if the scratch hierarchy is not used, then ghost data should be communicated using the provided `u_ghost_fill_sched`.

On the other hand, there is no need to execute the `u_ghost_fill_sched` if data are being moved from the primary hierarchy to the scratch hierarchy, because those ghost values on the primary hierarchy will never be used in the interpolation routine.

In `IBFEMethod::spreadForce()`:
```cpp
if (d_use_scratch_hierarchy)
{
    assertStructureOnFinestLevel();
    // TODO: we don't need a RefinePatchStrategy here, right?
    getPrimaryToScratchSchedule(d_hierarchy->getFinestLevelNumber(), f_data_idx).fillData(data_time);
}
```
can probably be removed. I would suggest zero-initializing the data that are being spread to, and then add them back.```cpp
// Communicate ghost data.
for (const auto& u_ghost_fill_sched : u_ghost_fill_scheds)
{
    if (u_ghost_fill_sched) u_ghost_fill_sched->fillData(data_time);
}
