### ISSUE TITLE
Post nwt-final: summarize work in changelogs

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#748]
We need to write changelog entries for all of the stuff in #744. I think @amneetb is the right choice for describing these changes :)

We can either add these to #744 directly or handle it afterwards in a followup commit.

**Comment by drwells** [comment]
@amneetb You understand the changeset that went into this set of patches better than anyone else. Would you please write the accompanying changelog entries? I would like to get this in before the next release (i.e., by the end of this week would be great)

**Comment by amneetb** [comment]
> @amneetb You understand the changeset that went into this set of patches better than anyone else. Would you please write the accompanying changelog entries? I would like to get this in before the next release (i.e., by the end of this week would be great)

Sure. What do I need to do? Which file should I put this too? Is there an existing example?

**Comment by drwells** [comment]
The best way to do it is to put one feature in each file. We have three folders for changes: major, minor, and incompatibilties (most of NWT, e.g., FESurfaceDistanceEvaluator, should be in major).

For example, see 

https://github.com/IBAMR/IBAMR/blob/master/doc/news/changes/major/20191031DavidWells

They go in separate files to prevent merge conflicts (i.e., the alternative is to have everyone edit one changelog file; thats not going to work with git).

**Comment by drwells** [comment]
@amneetb I would like to put out a release candidate today or tomorrow (so that we can get the release out by the end of the week). Will this be done in time to put it in the candidate?

**Comment by amneetb** [comment]
I will do it today by the end of the day. Finals week here ☹️

**Comment by drwells** [comment]
Fixed by #804.
