### ISSUE TITLE
Get the test suite working on my desktop

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#773]
Subj.

For whatever reason, I get different results for some tests on my workstation than I do on my personal desktop. Some of the differences (like for linear spreading and interpolation) are quite large. Some are very small: e.g., one processor will have one more quadrature point and another will have one less. I will get this sorted out before the release.

**Comment by abarret** [comment]
For what it's worth, I noticed the same thing on my laptop yesterday.

**Comment by drwells** [comment]
@abarret I think that I found a bug - valgrind reports that `spread_01_3d.discontinuous_linear.input` has a conditional jump that depends on uninitialized input. This is a test that yields consistent but different results for me on different machines. Could you verify that this test is problematic for the same reasons for you?

**Comment by abarret** [comment]
These are the tests that fail for me on my workstation:

```   IBFE/explicit_ex4_2d.mpirun=5.input
    IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.input
    spread/spread_01_3d.piecewise_constant.input
    spread/spread_01_3d.discontinuous_linear.input
    IBFE/interpolate_velocity_01_2d.b.piecewise-constant.input
    IBFE/interpolate_velocity_01_2d.b.discontinuous-linear.input
```

I have confirmed that valgrind reports a conditional jump that depends on uninitialized input for the test `spread_01_3d.discontinuous_linear.input`

**Comment by drwells** [comment]
Its super weird that those interpolation tests don't fail for me - I'd bet the same bug is present in those kernels.

**Comment by drwells** [comment]
Could you manually run `numdiff` on the output of `IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.input` and paste the result here?

**Comment by drwells** [comment]
If you're not sure how to do that let me know - it should only take a moment.

**Comment by abarret** [comment]
It's pretty long. It looks like different numbers of quadrature points and resulting finite precision differences.
[numdiff_output.txt](https://github.com/IBAMR/IBAMR/files/3941635/numdiff_output.txt)

**Comment by drwells** [comment]
It looks like its the same issue as the rest of the `ex4` tests: one quadrature point seems to be within roundoff.

If you do
`numdiff -r 1e-6 -a 1e-10 output explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output`

then what do you get?

**Comment by abarret** [comment]
```
[barrett@mathid2948 IBFE]$ numdiff  -r 1e-6 -a 1e-10 output explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
----------------
##48      #:7   <== 1250
                ==> 1249
@ Absolute error = 1.0000000000e+0, Relative error = 8.0064051241e-4
----------------
##50      #:7   <== 1257
                ==> 1258
@ Absolute error = 1.0000000000e+0, Relative error = 7.9554494829e-4
----------------
##52      #:7   <== 1250
                ==> 1249
@ Absolute error = 1.0000000000e+0, Relative error = 8.0064051241e-4
----------------
##54      #:7   <== 1257
                ==> 1258
@ Absolute error = 1.0000000000e+0, Relative error = 7.9554494829e-4
```

**Comment by drwells** [comment]
Good :)

**Comment by drwells** [comment]
The following tests fail due to memory corruption problems (i.e., valgrind complains):
- [ ] spread/spread_01_3d.discontinuous_linear.input
- [ ] spread/spread_01_3d.piecewise_constant.input
- [ ] adv_diff/adv_diff_01_2d.input

I think these might also have memory problems, but valgrind does not complain on my desktop:
- [ ] IBFE/interpolate_velocity_01_2d.b.discontinuous-linear.input
- [ ] IBFE/interpolate_velocity_01_2d.b.piecewise-constant.input

**Comment by drwells** [comment]
I was working on this late last night and realized an interesting trend: the partitioning seems to vary between machines a lot only before the first time step: after we regrid then things agree. I think this issue is independent of the 'off by a quadrature point' issue that ex4 sometimes has.
[desktop-output.tar.gz](https://github.com/IBAMR/IBAMR/files/3945512/desktop-output.tar.gz)

Here are the output files for four tests that fail on my machine.

**Comment by boyceg** [comment]
Hmmm. It might make sense to force regridding before doing any tests.

**Comment by drwells** [comment]
The problem is that we verify a bunch of stuff by checking log files, which are presently printing out partitioning information - in fact, I would like to keep printing this out for checking things like the scratch hierarchy, computation of the number of IB points, etc.

I think the best approach is to add code which conditionally disables this type of logging in `IBFEMethod` before the first real time step. Its a bit hacky but it keeps the test output useful.

**Comment by boyceg** [comment]
Is this just for libMesh-related partitioning? Are we using a partitioner with a random seed?

**Comment by drwells** [comment]
Nope, its related to SAMRAI partitioning: we get a different number of quadrature points in different patches on different machines. I can check more carefully, but I am pretty sure that this means that the initial patch generation (prior to the first regrid) has machine-dependent partitioning.

**Comment by drwells** [comment]
I also get some suspicious uninitialized memory warnings for `IBFE/explicit_ex8_2d.postprocessor.scratch_hier.mpirun=4.input` when I run it with valgrind.

**Comment by drwells** [comment]
@boyceg Here is some confirmation regarding distribution of patches. I added some extra code to call `PatchHierarchy::recursivePrint()` in ex4 and logged the result. I get this, before timestepping begins, on my workstation:
```
Rank 0
    Number of levels = 2
    Level 0/2
    	Number of patches = 1
    	Patch 0/1
    		[(0,0),(9,9)]	dims: 10 X 10	size: 100
    Level 1/2
    	Number of patches = 1
    	Patch 0/1
    		[(0,0),(39,39)]	dims: 40 X 40	size: 1600
    Total number of patches = 2
    Total number of cells = 1700

Rank 1
    Number of levels = 2
    Level 0/2
    	Number of patches = 1
    Level 1/2
    	Number of patches = 1
    Total number of patches = 2
    Total number of cells = 1700

Rank 2
    Number of levels = 2
    Level 0/2
    	Number of patches = 1
    Level 1/2
    	Number of patches = 1
    Total number of patches = 2
    Total number of cells = 1700

Rank 3
    Number of levels = 2
    Level 0/2
    	Number of patches = 1
    Level 1/2
    	Number of patches = 1
    Total number of patches = 2
    Total number of cells = 1700
```
and on my laptop:
```
Rank 0
    Number of levels = 2
    Level 0/2
    	Number of patches = 1
    	Patch 0/1
    		[(0,0),(9,9)]	dims: 10 X 10	size: 100
    Level 1/2
    	Number of patches = 3
    	Patch 0/3
    		[(0,0),(7,7)]	dims: 8 X 8	size: 64
    Total number of patches = 4
    Total number of cells = 1700

Rank 1
    Number of levels = 2
    Level 0/2
    	Number of patches = 1
    Level 1/2
    	Number of patches = 3
    	Patch 1/3
    		[(0,8),(7,39)]	dims: 8 X 32	size: 256
    Total number of patches = 4
    Total number of cells = 1700

Rank 2
    Number of levels = 2
    Level 0/2
    	Number of patches = 1
    Level 1/2
    	Number of patches = 3
    	Patch 2/3
    		[(8,0),(39,39)]	dims: 32 X 40	size: 1280
    Total number of patches = 4
    Total number of cells = 1700

Rank 3
    Number of levels = 2
    Level 0/2
    	Number of patches = 1
    Level 1/2
    	Number of patches = 3
    Total number of patches = 4
    Total number of cells = 1700
```

**Comment by drwells** [comment]
I am going to move the problems due to uninitialized memory into a new issue - the original intent of this was to just track the partitioning problem.
