### ISSUE TITLE
Get the new JacobianCalculator working with surface elements

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#775]
It looks like the current code ends up being called by `IBFESurfaceMethod` for codimension 1 surfaces, which are explicitly not implemented (yet). It should be easy to add these (and slightly modify the API of `JacobianCalculatorCache`).

This problem exposes an issue with undertesting: we have zero test code for `IBFESurfaceMethod`. We should also convert `IBFE/explicit/ex5/` into a unit test to verify that we don't break this in the future.

**Comment by AminKolah** [comment]
We don't have zero test for `IBFESurfaceMethod` though. `IBFE/explicit/ex5/`  is a test for both `IBFEMethod` and `IBFESurfaceMethod` . The way I look at this is that we only use `boundary_mesh`  if we want to run with `IBFESurfaceMethod` and it's turned off otherwise to be used with `IBFEMethod`.

**Comment by AminKolah** [comment]
There are also a ton of other examples using IIM that I can either add them to `IBFE/explicit/` or  if we decide to create a new `IBFESurface/explicit/` folder I can add them there.
