### ISSUE TITLE
Reimplement force spreading accumulation from ghost cells

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#830]
Background: when we do force spreading, on a given patch we calculate contributions from points outside the patch that can spread into the patch: i.e., if a point can spread into the patch interior we compute its contribution. A long time ago IBAMR instead had each patch compute its own contributions (including values spread into ghost cells) and then did a parallel reduction to get the correct values on each locally owned patch interior.

I talked about this with @boyceg yesterday and, after mulling it over this morning, I am convinced that we should switch back to something like the old algorithm. A fundamental problem with IBFE is that we end up with a huge number of elements on more than one processor: a mesh may have 200k elements, but since elements will show up on multiple patches we will have (e.g., in ex4 in 3D) 400k elements to loop over when we do force spreading. Its very difficult to load balance this correctly since SAMRAI does not have a notion of additional work done at interfaces, only workload per cell.

One way to think of this is is to note that if we have a ghost width of 3, then 16 x 16 x 16 = 4096 becomes 22 x 22 x 22 = 10648, but with a ghost width of 1 we have 18 x 18 x 18 = 5832. That is, we do nearly twice as much work when we consider the full ghost region as when we consider a ghost region with one adjacent cell.

The reason this was (rightly) removed previously was that the summation was done in an arbitrary order - values were not reproducible between runs since values were accumulated in an order dependent on traffic. AFAICT SAMRAI does not implement the algorithm we need, which is roughly as follows:
1. As every processor has a copy of the complete set of boxes, each processor can determine which processes can contribute values into its own patch interiors and also determine where it needs to send its own ghost data.
2. By growing boxes and computing intersections each processor can compute the regions in index space where there are overlaps: e.g., processor 0 can determine which processors have relevant ghost values to it and where its own ghost values should go.
3. Pass messages with `MPI_Isend` and `MPI_Irecv` into dedicated buffers per processor. Do an MPI_Wait before proceeding.
4. Sum passed ghost values into array interiors in a predetermined order independent of traffic.

I don't know what equivalent algorithm SAMRAI implements, but since SAMRAI doesn't use `MPI_Isend` or `MPI_Irecv` in any places relevant to solving this problem I think that we need to implement this on our own.

**Comment by drwells** [comment]
To get good load balancing with this example we need nearly 6x as many IB elements as we have active elements.

**Comment by knepley** [comment]
Note that instead of Isend/Irecv you can use VecScatter from PETSc. You get Isec/Irecv, but also Alltoallv() and windows. The Alltoall() is considerably faster on some architectures and at the scales I think you are using. Also, VecScatter should be easier to setup.

**Comment by drwells** [comment]
I actually read through the `VecScatter` implementation to check that this plane is sane (as well as deal.II's own Partitioner class).

Do we need to give every number we transfer an index if we use `VecScatter`? I imagine one advantage of just using Isend/Irecv directly is that I can just send blocks corresponding to slices of SAMRAI boxes and not bother with indices for the most part.

**Comment by boyceg** [comment]
Note that we do have routines that will assign DOF ids to SAMRAI data and synchronize values on shared locations. Would probably require copying between representations however.

**Comment by boyceg** [comment]
You might want to take a look at PETScVecUtilities. It will setup DOF indices for different types of data centerings, generate PETSc Vac’s with the right number of DOFs, and copy SAMRAI data to/from PETSc vectors. It is used, e.g., in the PETScLevelSolver implementations.

OTOH, there may be some benefit to doing things on a patch-by-patch basis.

**Comment by knepley** [comment]
You can have blocks in VecScatter (like Vecs and Mats), but not arbitrary MPI types. You can have those in PetscSF, which is why I use that in Plex.

**Comment by drwells** [comment]
Good ideas - it looks like `PETScVecUtilities::constructPatchLevelDOFIndices` does what I want.

**Comment by boyceg** [comment]
I don't think that the old strategy predates our use of git -- I don't think it is worth hunting around for it.

I think that this is a different approach than what you are planning, but a thing that could be done is to make a scratch hierarchy with overlapping patches that covers the current configuration of the FE mesh in **whatever** partitioning is being used by libMesh.

You could synch the DOF indices from the real patch hierarchy to the scratch hierarchy. Spread from each element only once, but use a `VecScatter` to do the accumulation. (This would probably mean reimplementing spreading in C++.) Potentially a lot of communication but may make it easier to load balance.

Of course, all of these operations could be encoded as a `Mat` that directly relates the two data representations.

**Comment by drwells** [comment]
That's not what I had in mind and it would resolve the problem where we have to do a lot of duplicated work due to elements in ghost cells.

I think I would prefer to do the original proposal first, though, because
1. Different elements have different numbers of quadrature points based on the deformation so we would need to write a partitioner for libMesh to account for this. I'm not sure how big a deal this would be but I think that its generally true that the workload per element varies quite a bit.
2. We still have to deal with the problem where an element intersects multiple patches: even if we compute on each element exactly once we will have to do an accumulation into an arbitrary number of patches from each element, which sounds hard.
3. Reimplementing spreading in C++ is going to take much longer than the above set of code :cat:

**Comment by boyceg** [comment]
> I think I would prefer to do the original proposal first, though, because
> 
> 1. Different elements have different numbers of quadrature points based on the deformation so we would need to write a partitioner for libMesh to account for this. I'm not sure how big a deal this would be but I think that its generally true that the workload per element varies quite a bit.

I agree that load balancing would still be a challenge.

> 2. We still have to deal with the problem where an element intersects multiple patches: even if we compute on each element exactly once we will have to do an accumulation into an arbitrary number of patches from each element, which sounds hard.

IIRC, the `Vec` representation of the SAMRAI data avoids this issue by assigning only a single DOF to each shared location. There is code that then understands how to synchronize values at those shared locations.

> 3. Reimplementing spreading in C++ is going to take much longer than the above set of code 🐱

I agree, although there is already code to make spreading operators as `Mat`s for `IBMethod`, and so it will be less work than you think. I think that we also could possibly take advantage of partitioners exposed by PETSc if we represent the operation as a `Mat`.

I would rather make the current approach work, but if that proves to be too hard, this is an alternative that may be worthwhile.

**Comment by drwells** [comment]
> IIRC, the Vec representation of the SAMRAI data avoids this issue by assigning only a single DOF to each shared location. There is code that then understands how to synchronize values at those shared locations.

Oh, I think I understand now - if we work with that representation then we can sum ghost values easily. That makes more sense.
