### ISSUE TITLE
Build failure using bundled boost

### ISSUE THREAD

**Issue by abarret** [IBAMR/IBAMR#845]
I'm using IBAMR's bundled boost, and libmesh is configured without boost. I'm getting a build error that looks like

`../../IBAMR/lib/../src/wave_generation/WaveDampingFunctions.cpp:26:10: fatal error: boost/math/tools/roots.hpp: No such file or directory
 #include <boost/math/tools/roots.hpp>`

It appears that our bundled copy of boost isn't complete. We should either remove this dependency from `WaveDampingFunctions` or update our bundled boost.

**Comment by boyceg** [comment]
We should update the bundled boost.

**Comment by drwells** [comment]
It is a bit tricky for me to fix this since I have system copies of boost on all of my machines - could someone who uses the bundled copy of boost please take a look?
