### ISSUE TITLE
IB-6 kernel disagrees with inlined version

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#853]
I noticed this while working on #615 - when I tried to inline the delta function I got different results than the ones I get with `master`. We should investigate and figure out which version is right.

**Comment by boyceg** [comment]
At some point there definitely was a bug in the `IB_6` kernel.

There is a reference implementation for both 5- and 6-point kernels available [here](https://github.com/stochasticHydroTools/DFIB/blob/master/Kernels_MEX/Kernels.c). They are the "flex" kernels.
