### ISSUE TITLE
Get rid of triangle in spread tests

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#859]
I spent most of yesterday trying to figure this out. For reasons I don't completely understand, I get different vertex orderings on my desktop computer than on my workstation - this shouldn't be an issue, but since some of our quadrature rules have anisotropy [1] we end up with different quadrature points and therefore different force values.

Fortunately, the numberings used in the `MeshGeneration` functions are much less variable - those functions work by hard-coding in the coarse grid and then refining that mesh a set number of times. There is no variability here in node numberings.

[1] Quadrature rules for triangles derived from rules for quadrilaterals accumulate points near one node: hence, if there are more quadrature points near node 1, we get an equivalent but different set of quadrature points after we map them to the deformed element if we use different node numberings.

**Comment by drwells** [comment]
We currently verify the spread functions (mostly to make patches like #852 testable) by just printing out the computed force values. Hence moving quadrature points causes the tests to fail.

**Comment by drwells** [comment]
This issue is also a good reminder of the fact that we really need to derive a new family of low-order quadrature rules that are more evenly spaced than Gauss rules for IB applications...

**Comment by drwells** [comment]
Clarification: here 'triangle' refers to the mesh generation program - it generates high-quality meshes from a set of boundary points.

**Comment by boyceg** [comment]
It would be worth thinking about whether there are alternative constructions that make more sense for these integrands. It would be a surprise to me if vanilla Gauss rules are optimal.

**Comment by drwells** [comment]
I'm sure there are - libMesh's quadrature rules are optimized for low numbers of points at a given order, which is the opposite of what we want (we want to fix order and then use whatever number of points is necessary for IB considerations).

**Comment by drwells** [comment]
Fixed by #876.
