### ISSUE TITLE
Add an IBTK example that explains ghost filling algorithms

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#892]
I was talking about this with @fuhuifang earlier today - she asked me a question about how we should fill ghost values and I didn't have a great answer. We should add a well-documented IBTK example that explains how to use ghost values, e.g.,
```cpp
using ITC = HierarchyGhostCellInterpolation::InterpolationTransactionComponent;
std::vector<ITC> ghost_cell_components(1);
ghost_cell_components[0] = ITC(u_cc_idx,
                               "LINEAR_REFINE",
                               true,
                               "CONSERVATIVE_COARSEN",
                               "LINEAR",
                               false,
                               {}, // u_bc_coefs
                               nullptr);
HierarchyGhostCellInterpolation ghost_fill_op;
ghost_fill_op.initializeOperatorState(ghost_cell_components, patch_hierarchy);
ghost_fill_op.fillData(/*time*/ 0.0);
```
(from `interpolation_01.cpp`). It would be great if we also showed how to do this in a manual way.

**Comment by abarret** [comment]
I've been playing around with ghost cells recently. I can put something together, but I'm not entirely sure what you want the example to do.

> It would be great if we also showed how to do this in a manual way.

What do you mean by in a manual way?

**Comment by drwells** [comment]
As in with a loop (i.e., we would put our own values in it) instead of relying on some filling algorithm provided by SAMRAI.

**Comment by abarret** [comment]
I don't think this is a trivial thing to do in simulations with AMR since it's not easy to tell whether you're at a coarse-fine interface, a physical boundary, or a patch boundary with the same level of refinement.

I could write an example that shows how to write a `CoarsenOperator` and `RefineOperator` and use them with the SAMRAI infrastructure?

**Comment by drwells** [comment]
I agree, but I want something much easier - we should show how to loop over ghost data in a box even if we don't know what it corresponds to.

> I could write an example that shows how to write a CoarsenOperator and RefineOperator and use them with the SAMRAI infrastructure?

That would be great!

**Comment by abarret** [comment]
I've got an idea to do both of these in one example :)

**Comment by drwells** [comment]
> it's not easy to tell whether you're at a coarse-fine interface, a physical boundary, or a patch boundary with the same level of refinement

Even just documenting that these are the possibilities would be a huge win in my opinion for people who are trying to learn how IBAMR and SAMRAI work.
