### ISSUE TITLE
Switching order in initializeCompositeHierarchyData

### ISSUE THREAD

**Issue by nishantnangia** [IBAMR/IBAMR#895]
Hi folks,

Would there be undesirable consequences if we switch the order of calls in HierarchyIntegrator::initializeCompositeHierarchyData ([here](https://github.com/IBAMR/IBAMR/blob/master/ibtk/src/utilities/HierarchyIntegrator.cpp#L701)) to initialize the child integrators first _before_ the parent?

The reason I ask is because I was working with [multiphase/ex3](https://github.com/IBAMR/IBAMR/tree/master/examples/multiphase_flow/ex3) and noticed some undesirable behavior with the current order of the calls. In this example, the initial velocity field is set to 1 inside a circular bubble, and 0 outside. This velocity field should get projected to a divergence free one via a density-weighted Poisson solve [here](https://github.com/IBAMR/IBAMR/blob/master/src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp#L1020).

However, to set the correct density field, the level set data needs to be set on the hierarchy first, which is managed by the advection-diffusion integrator. But since child integrators initialize their data _after_ the parent, the level set values are junk, leading to junk densities, leading to an incorrect projection solve.

If I switch the order of the initialization to child-first, then everything looks right, but could there be cases in which we would want the parent to go first?

**Comment by drwells** [comment]
Good question: I am not sure if we have such a case but do any tests (aside from the usual suspects) that fail if we change it?

**Comment by boyceg** [comment]
I think that instead of switching from one arbitrary order to another, I would suggest introducing an optional way to override the default behavior and set the order that things happen. One possibility would be to assign integrators “priority” and process in a corresponding ordering.

**Comment by nishantnangia** [comment]
I like the idea of assigning priority — makes things more flexible (and in
fact, I think we did something similar for the callback functions in
adv-diff integrator.

I think I can cook something up and write some tests.

**Comment by nishantnangia** [comment]
Apologies for the delay on this.

I spent some time re-familiarizing myself with this code and couldn't think of a nice way to enforce 'priority' since all the calls to child integrators are carried out recursively. Moreover, I realized that this problem is pretty easy to fix for multiphase_flow/ex3: we can just specify a level set initial condition in the input file. I opened a PR with this fix here: https://github.com/IBAMR/IBAMR/pull/919

I'll leave it up to @boyceg and @drwells if you want to change this interface in the future; if you do, at least now we have a test for it :-)

**Comment by drwells** [comment]
Conceptually, to me, the different integrators should not need to send data to each-other in the initialization phase - the data dependencies are just too hard to track correctly.

Since we found a different way to fix the problem in this particular instance I am going to close this issue for now. We can always try to cook something up later if we need it.
