### ISSUE TITLE
Several issues with CIBMethod

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#906]
@fuhuifang pointed out to me on Thursday that `CIB/ex1/` worked until recently. I bisected and found that #880 caused this example to stop working (it now segmentation faults).

The failure could be unrelated to #880. When I looked at it I found several issues:
1. `d_rho` is never set, resulting in undefined behavior in every timestepping method.
2. `d_constraint_force_is_initialized` is read in `CIBMethod::spreadForce` before it is initialized, also resulting in undefined behavior.
3. Something is similarly wrong with `d_lag_velvec_is_initialized`.

We should take some time to review this class and make sure the examples run cleanly and correctly on `master` under valgrind. Once that is done we can quickly copy-and-paste `CIB/ex1/` into the test suite. @amneetb @fuhuifang you two know this code best - would one of you please take this on as a release task?

**Comment by amneetb** [comment]
@drwells: Can you confirm that even `CIB/ex0` is not working with current master?

**Comment by boyceg** [comment]
Perhaps @fuhuifang can help with this?

**Comment by boyceg** [comment]
@amneetb I cannot pull up the conversation in the branch related to c122fc9, but could you post a PR to fix CIBStaggeredStokesOperator?

**Comment by drwells** [comment]
@amneetb yup: @fuhuifang pointed out to me last week that it crashes on master. I can consistently reproduce this problem.

**Comment by drwells** [comment]
Fixed by #926.
