### ISSUE TITLE
Call FEDataManager::reinitElementMappings() by request for each system

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#947]
I ran callgrind on TAVR again over the weekend and took a look at the results. I don't have time to work on this now but I figured we should summarize the problem so that we don't forget about it.

Some applications add a lot of their own libMesh systems to the EquationSystems object managed by FEDataManager - most of these never need to access the IB-ghosted partitioning, but we still unconditionally compute this partitioning for them in `reinitElementMappings()`. This problem is made worse by use of the scratch hierarchy where we do everything for both the primary and scratch partitioning. Since the TAVR code regrids a lot this ends up occupying 15% of our total run time.

We should modify the logic to only compute `d_active_patch_ghost_dofs` and `d_system_ib_ghost_vec` on demand instead - this should largely resolve the problem since we rarely access this information for more than two systems (instead of assembling it, for the TAVR case, for about 10 systems).

**Comment by drwells** [comment]
@jabrown893 would you be interested in taking a stab at this?

**Comment by jabrown893** [comment]
@drwells I don't think I have the bandwidth to do it super soon. I'm also not sure I have the knowledge to do it myself. But, maybe down the road when you have time to return to it, I can help out and learn a little more about it?

**Comment by drwells** [comment]
Sure.

Briefly, what we need to do is move the 'enumerate IB DoFs' code from `reinitElementMappings()` to `buildIBGhostedVector()` - it shouldn't be too hard to work it out.

**Comment by boyceg** [comment]
I think I just did it.
