### ISSUE TITLE
cib_plate.mpirun=4 fails intermittently

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#949]
I ran this test with two different configurations of IBAMR on my workstation - with one if fails about 33% of the time and with the other about 12% (I ran the test 100 times for each).

@amneetb would you please take a look or assign a student to take a look?

**Comment by amneetb** [comment]
Do you mean the input output does not match or the solver does not work? In the former we might want to crank up the solver tolerance.

**Comment by amneetb** [comment]
Also I my case 99.9%  times student = me.

**Comment by drwells** [comment]
The program runs correctly but attest fails at the diff stage.

**Comment by drwells** [comment]
i.e., the output doesn't match.

**Comment by amneetb** [comment]
Then it is the solver tolerance. Can you crank it up by changing it over here?
https://github.com/IBAMR/IBAMR/blob/master/tests/CIB/petsc_options.dat#L10

**Comment by drwells** [comment]
I can give it a try but I suspect that's not it - `cib_double_shell.mpirun=4` passes 100% of the time.
