### ISSUE TITLE
CUI operator gives large errors in some cases

### ISSUE THREAD

**Issue by abarret** [IBAMR/IBAMR#965]
From #962, `CUI` gives apparent first order convergence rates with large errors in certain cases.

When used as a component of an advection example, e.g. `examples/adv_diff/ex0`, errors and convergence rates are similar to other convective operators.

However, when looking at the test `tests/adv_diff/adv_diff_convec_opers_2d` the errors from applying the convective operator to a known function and velocity field, we get relatively large errors and a slowed convergence rate. Below is a picture showing the original function (left), the computed operator (middle), and the error (right). It's currently unclear what's causing this since, as mentioned before, we get good accuracy in advection simulations. The same feature occurs with the 3D operator.
![error_cui](https://user-images.githubusercontent.com/8540922/78948387-55fb6800-7a85-11ea-9227-b99ab5532111.png)

**Comment by amneetb** [comment]
Ok, @nishantnangia, @Raamkrishnan and I investigated this and found that it is a feature of CUI and not a bug. 

Basically all CBC schemes become upwind in presence of an extrema, i.e, when `dQ/dx` or `dQ/dy` is zero. In this particular example, we have this condition. 

If we switch to an unbounded scheme like `QUICK` the problem disappears as it assumes a monotonic profile in all cases. The problem re-appears when we bound `QUICK`, i.e., use the  `SMART` scheme.

**Comment by abarret** [comment]
I'm closing this since it appears to be a feature and not a bug.
