### ISSUE TITLE
clang-format messes up Matlab scripts

### ISSUE THREAD

**Issue by amneetb** [IBAMR/IBAMR#98]
@boyceg: Can .m files be excluded in .clang-format?

**Comment by boyceg** [comment]
@amneetb this is not a bug --- .m files are the extension for Objective C, which clang-format knows how to format. I updated the default pre-commit hook in #100 only to check files with the extensions C, c, cpp, and h. The message printed when clang-formatting is needed also now reports the command to use that updates only those files (which is "git clang-format --extensions=C,c,cpp,h").
